### ISSUE TITLE
Use django-environ for parsing environment variable

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#1036]
Currently we use `os.getenv` in Django settings.py which is cumbersome to get all the details such parsing it in a case insenstive way, the right format of the environment variable, etc.

Using [django-environ](https://django-environ.readthedocs.io) we can easily specify the type and default value let django-environ handle everything. This will also give better error messages when the environment variable isn't the right type.

**Comment by ammar92** [comment]
Sounds good. Looks a lot like Pydantic's `BaseSettings`, but is a bit more convenient to use for this purpose and also supports the more "complex" types such as URLs and DB URLs/DSNs
