### ISSUE TITLE
Comments in config files

### ISSUE THREAD

**Issue by RobboRob** [minvws/nl-kat-coordination#105]
Please add in the config files (e.g. in /etc/kat) comments per configurable item including:

- purpose
- possible values (including what its effect will be)

**Comment by RobboRob** [comment]
Voorbeeld was bv de http setting in /etc/kat/rocky.uwsgi.ini waar http = localhost:8000 veranderd moest worden in 0.0.0.0:8000

Hier zou vermeld kunnen worden waar deze setting voor is en wat de verschillende mogelijkheden qua gebruik zijn:
# Gebruik localhost om via een browser op de eigen machine via poort [port] openKAT te benaderen
# http = localhost:[port] 
# Gebruik 0.0.0.0 om openKAT van een willekeurig IP adres via poort [port] te benaderen
# http = 0.0.0.0:[port] 
# Gebruik [IP adres] om openKAT vanaf een specifiek adres via poort [port] te benaderen (bv middels een reverse proxy)
# http = [IP adres]:[port]

**Comment by underdarknl** [comment]
@ring-ring-ring wil jij deze flaggen bij de devs ophalen en beschrijven? Dan voegen we ze daarna toe aan de docs en de example configs.

**Comment by ring-ring-ring** [comment]
Done, see: https://docs.openkat.nl/technical_design/environment_settings/index.html
