### ISSUE TITLE
Design for new severity levels

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-coordination#1054]
With the [recent effort to move FindingType metadata to Octopoes](https://github.com/minvws/nl-kat-coordination/issues/1030), Findings can be categorized into two new severity levels. 'Pending' and 'Unknown'.

The severity level `Pending` is introduced to indicate the transitory state between the moments:
- that KAT knows that _'a Finding with FindingType X is present'_ 
  - and:
- that the metadata (such as `severity` and `score`) of `FindingType X` is fetched by a Boefje and known by KAT

The severity level Unknown represents the situation where an external authority does not (yet) have value available for the  severity or score fields.

Currently these states are not yet represented in the design:
![Screenshot 2023-05-25 at 14 20 48](https://github.com/minvws/nl-kat-coordination/assets/9639395/b0771c24-7a38-4e60-9c7f-dd67f9388f80)

**Describe the solution you'd like**
A design on how these states should be visualized and communicated to the user. 
- What color should be communicated 
- How high should these states be ranked in the sorting

**Comment by NoemiOverdijk** [comment]
@underdarknl Do you have an opinion on how high these new states should be ranked?

**Comment by NoemiOverdijk** [comment]
The design for this issue has been reviewed and approved


![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/3f61a3a8-4e02-42d6-a87f-354f4636463f)



You can find the design here:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=472%3A26085&t=64nds0bpwjoltvpI-1](url)

If you want to comment, you can do so here:
[https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=731%3A87692&t=TvlIXT4QaT1LA1Im-1](url)
