### ISSUE TITLE
Versie nummer niet voor alle modules correct op Health pagina

### ISSUE THREAD

**Issue by RobboRob** [minvws/nl-kat-coordination#106]
Op de health pagina wordt na de update naar de 1.4.0 Debian release voor niet alle componenten 1.4.0 vermeld.

![signal-2023-01-03-165319_002](https://user-images.githubusercontent.com/5878046/210794402-a085bb56-0999-486b-934a-0efe4c038150.png)

**Comment by praseodym** [comment]
Fixed by #737
