### ISSUE TITLE
Incorrect icons are rendered

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#1073]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
Sometimes the icons aren't rendered as expected. 

**To Reproduce**
On seemingly random refreshes the icons will all be incorrect and replaced with different content.
![Screenshot 2023-05-30 at 16 46 32](https://github.com/minvws/nl-kat-coordination/assets/11405133/5ee31399-ee6c-4758-be1e-97828bc3c875)

**Expected behavior**
Redering the icons we selected: 
![Screenshot 2023-05-30 at 16 48 24](https://github.com/minvws/nl-kat-coordination/assets/11405133/895c6b9c-ceb4-47c2-9020-01a1cf519621)

**OpenKAT version**
Currently the issue has been seen on manon update branch. (Haven't tested it on main yet) 
https://github.com/minvws/nl-kat-coordination/pull/548 

**Additional context**
Found some insight in the following threads: 
https://github.com/FortAwesome/Font-Awesome/issues/10842

**Comment by Rieven** [comment]
Found this in rocky: 
Could not load content for http://localhost:8000/assets/src/bundles/app/css/themes/soft/fonts/tabler-icons/tabler-icons.scss (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

The font icon is not loading:
![Image](https://github.com/minvws/nl-kat-coordination/assets/30832687/c6a25714-4bce-4b17-b876-8815e9854b79)
