### ISSUE TITLE
LaTeX report large findings go outside pdf margin

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1081]
**Describe the bug**
When larger findings (with long names, or mentioning a filename) are present, they extend outside the pdf margin, making the exact finding effectively unreadable.

**To Reproduce**
1. Create a finding on a URL path of decent length
2. Generate pdf report
3. Notice the URL path is not fully readable

**Expected behavior**
A readable finding.

**OpenKAT version**
1.8.0.1 & 1.9rc1

**Comment by ammar92** [comment]
Good suggestion. Word wrap usually works best with whitespace separation. I think the natural key should then be adapted since (most?) human-readable properties already have whitespace.
