### ISSUE TITLE
Manage scheduled report creation (celery?)

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#1085]
Given that we received [this](https://github.com/minvws/nl-kat-coordination/issues/708) feature request several times, perhaps we should consider:
- Adding a job scheduling tool such as celery-beat (or another, perhaps simpler tool) to Rocky that can schedule report generation from the admin interface.
- Given the number of services and the fact that Keiko does not contain a lot of logic, I would opt for incorporating Keiko into a separate Django app in Rocky. Celery could handle failovers in that case. It would make it easier to add logic around querying reports without having to pass information through an extra HTTP API as well. It would also reduce the number of KAT services to manage.

**Comment by underdarknl** [comment]
Wouldn't this be something easily handled by using a cron job, or systemctl timer, or in clouds a periodic job? We'd also need to include same delivery path of the produced reports, which would add more features that we need to keep track of ourselves.

Adding more jobs to celery sounds like adding more stuff KAT needs to manage, instead of moving this to the Ops department who already do various jobs like this and can easily schedule this, and produce their own version of a delivery path fitting their organizations whishes.

**Comment by Donnype** [comment]
Depends on whether we as OpenKAT decide to provide this functionality, which in turn might depend on how difficult it is for users needing this functionality to go through operations to make these updates.

If that's a no I do think using celery instead of a whole separate AIP & service for Keiko will offer a lot of benefits in the long run if we discover the need to do more asynchronous processing in Rocky.

**Comment by praseodym** [comment]
I don't think using Celery is the way to go. We already have a task scheduling system, so why not manage all tasks through that system instead?

**Comment by Donnype** [comment]
I am not sure if we should make Mula more generic to also schedule jobs that should be handled in Rocky and duplicate consumer logic into Rocky. As I understand, the requested feature is to be able to schedule report generation/distribution jobs in an interface. Such job management sounds like a problem that has been solved many times before. I do not necessarily opt for Celery, but mainly opt for using a proven solution if we want to support this from the interface.

One could argue however that we do not want to have such an interface in KAT, but provide the required connection API's to e.g. download reports. Then external tools or extensions could provide such an interface. On the other hand I can see that users would want an app that continuously monitors your systems to have periodic reporting functionality built in.

**Comment by praseodym** [comment]
It could be as simple as letting Mula periodically call an API endpoint in Rocky to create a report. If Rocky then saves all created reports in Bytes, we can provide a web interface to let the user download any created report.

My reasoning for letting Mula do this periodic scheduler is not that I want to make Mula more complicated, but that I think it's weird to have several components within KAT do their own scheduling. This makes it hard to debug issues, e.g. if the Octopoes Beat worker is dead there's no way to tell for the user, except from features like clearance level inheritance being mysteriously broken.

**Comment by underdarknl** [comment]
As decided, Mula will do periodic (flexibly scheduled) reporting based on 'recipes' that include a list of input-oois' or a query , some settings (name of report etc), and a list of requested reports. These recipes will then be scheduled as periodic jobs based on their interval.

**Comment by underdarknl** [comment]
There are new tickets for this, im closing this one.
