### ISSUE TITLE
use dockers hosted deb repository instead of downloading a specific version

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#110]
**Describe the bug**
We currently tell the user to download the latest version of Docker from their website. We should instead tell them to use the supplied repository if avaliable for their OS.
See
https://docs.docker.com/engine/install/debian/#install-using-the-repository

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)
