### ISSUE TITLE
Do not recreate rabbitmq channels in Bytes

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#1127]
See https://github.com/minvws/nl-kat-coordination/pull/1003#discussion_r1219668951

**Comment by Donnype** [comment]
> This might be similar to what I observed in #632.

Could be, but I had a look at Octopoes and saw that the channel was a property on the event manager class. Since your logs show new connections being created (not channels), this might mean we are creating new event manager instances on each request/batch/?. I Will have a quick look today!

**Comment by praseodym** [comment]
I've created #1162 for the Octopoes API issue.
