### ISSUE TITLE
Using the Z-A filter on the KAT-alogus page shows incorrect text

### ISSUE THREAD

**Issue by vstanojcic** [minvws/nl-kat-coordination#1129]
**Describe the bug**
When selecting the filter option "Z-A" on the "KAT-Alogus" page the result is that there are 0 available plugins. When changing the filter to "A-Z" it shows that there are 29 available plugins. 

**To Reproduce**
1. Go to "KAT-alogus"
2. Click on "Sow filter options"
3. Select "Z-A" 
4. Filtering shows the following text "0 available plugins" 
5. Select "A-Z" filter option
6. Filtering shows the following text "29 available plugins" 

**Expected behavior**
Expected to see 29 available plugins regardless which filter option I select (A-Z or Z-A)

**Screenshots**
A-Z filter
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/6137791c-d914-458f-8852-d1cbb314d477)

Z-A filter
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/6d122aa9-7776-46bf-b226-2237a2532cc2)

**OpenKAT version**
1.8.1 

**Desktop (please complete the following information if relevant):**
 - OS: Windows
 - Browser: Chrome

**Comment by TwistMeister** [comment]
Fixed in https://github.com/minvws/nl-kat-coordination/pull/1279
