### ISSUE TITLE
Drop Crux DB support in Octopoes 

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-coordination#1133]
**Is your feature request related to a problem? Please describe.**
Crux backwards compatibility regression tests are failing (silently)
E.g. https://github.com/minvws/nl-kat-coordination/actions/runs/5201556114/jobs/9381890026?pr=1118

**Describe the solution you'd like**
Drop the regression robot tests and internal support for Crux.

**Comment by underdarknl** [comment]
Agreed. by now everyone should have moved to XTDB anyway.

**Comment by originalsouth** [comment]
This should have been resolve by @dekkers in a7e7af0c6f16a7f3fbc35c977d44131bb2524121. I think this issue can be closed.

**Comment by originalsouth** [comment]
> What is the reason this needs to be discussed instead of just closed?

Because nobody responded to this

> This should have been resolve by @dekkers in [a7e7af0](https://github.com/minvws/nl-kat-coordination/commit/a7e7af0c6f16a7f3fbc35c977d44131bb2524121). I think this issue can be closed.

and I think the ticked can be closed. I do not want to close tickets solely on my own volition. Hence I wanted to very briefly mention it next discussion -- but I guess we can also discuss about the discussion.
