### ISSUE TITLE
'False positive' in onze bevindingen: geen ssl-certificaat gevonden, echter is deze wel aanwezig

### ISSUE THREAD

**Issue by jordy-kennisnet** [minvws/nl-kat-coordination#116]
'False positive' (dubbel) geconstateerd in onze bevindingen:
1. Finding: KAT-NO-CERTIFICATE @ [https://maken.wikiwijs.nl.:443](https://maken.wikiwijs.nl./) @ 145.97.38.108: No SSL certificate found
2. Finding: KAT-INTERNETNL @ maken.wikiwijs.nl: This hostname has at least one website with the following finding(s): This website does not have an SSL certificate

Extra informatie: de normalizer 'kat_ssl_certificates_normalize' van het boefje 'ssl-certificates' blijft op status 'depached' staan. Het lukt blijkbaar niet op het certificaat op te halen.

Wellicht dat het te maken heeft met een redirect die ingesteld staat op https://maken.wikiwijs.nl.

N.B. Daarnaast wordt het niet hebben van een SSL certificaat geregistreerd als twee aparte 'findings'. 

OpenKAT versie: 1.4.0

Disclaimer: gaarne het domein niet gebruiken voor andere testen, anders dan voor dit issue met het boefje ssl-certificaten.

**Comment by zcrt** [comment]
Regarding the false positive part of the issue: releases 1.5.1/1.6rc2 provide a fix for triggering a bit on attribute change. This should help overcome this problem since a bit should be triggered when a `Certificate` attribute is added to a `Website` object.

**Comment by zcrt** [comment]
Does not seem to be solved yet:
```python
[2023-02-16 12:39:22 +0000] [8] [INFO] [job_handler] Handling normalizer kat_ssl_scan_normalize[0ca4725ac6ef471a9cdc8ea8475fc129]
[2023-02-16 12:39:22 +0000] [9] [INFO] [local] Running local normalizer plugin
[2023-02-16 12:39:22 +0000] [9] [ERROR] [app] An error occurred handling scheduler item 4ef39934f97a433ba49635eabe6d9a02
Traceback (most recent call last):
  File "/app/boefjes/boefjes/app.py", line 101, in start_working
    item_handler.handle(p_item.data)
  File "/app/boefjes/boefjes/job_handler.py", line 175, in handle
    results = self.job_runner.run(normalizer_meta, raw)
  File "/app/boefjes/boefjes/local.py", line 70, in run
    return self._parse_results(normalizer_meta, results)
  File "/app/boefjes/boefjes/local.py", line 73, in _parse_results
    parsed: List[NormalizerResult] = [self._parse(result) for result in results]
  File "/app/boefjes/boefjes/local.py", line 73, in <listcomp>
    parsed: List[NormalizerResult] = [self._parse(result) for result in results]
  File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 46, in run
    certificates, certificate_subject_alternative_names, hostnames = read_certificates(
  File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 124, in read_certificates
    cryptography.hazmat.backends.openssl.x509.rsa.RSAPublicKey,
AttributeError: module 'cryptography.hazmat.backends.openssl' has no attribute 'x509'
```

**Comment by jordy-kennisnet** [comment]
Na installatie van v1.7rc1 nog steeds dezelfde bevinding. Daarnaast nu ook extra findings gekregen over certificaten die gevonden  en verlopen zijn, ondanks dat er wel minimaal één geldige aanwezig is.

**Comment by noamblitz** [comment]
Die verlopen certs finding is helaas op dit moment met huidige bits een keuze. Alle findings krijgen een cert omdat met de vorige keuze vaak geen findings werden getoond. Heb je ook de error van missende cert terwijl er wel een aanwezig is? Dat zou wel opgelost moeten zijn namelijk en wil ik de release van 1.7 dan voor uitstellen

**Comment by ammar92** [comment]
> Does not seem to be solved yet (on main branch 16 February):
> 
> ```python
> [2023-02-16 12:39:22 +0000] [8] [INFO] [job_handler] Handling normalizer kat_ssl_scan_normalize[0ca4725ac6ef471a9cdc8ea8475fc129]
> [2023-02-16 12:39:22 +0000] [9] [INFO] [local] Running local normalizer plugin
> [2023-02-16 12:39:22 +0000] [9] [ERROR] [app] An error occurred handling scheduler item 4ef39934f97a433ba49635eabe6d9a02
> Traceback (most recent call last):
>   File "/app/boefjes/boefjes/app.py", line 101, in start_working
>     item_handler.handle(p_item.data)
>   File "/app/boefjes/boefjes/job_handler.py", line 175, in handle
>     results = self.job_runner.run(normalizer_meta, raw)
>   File "/app/boefjes/boefjes/local.py", line 70, in run
>     return self._parse_results(normalizer_meta, results)
>   File "/app/boefjes/boefjes/local.py", line 73, in _parse_results
>     parsed: List[NormalizerResult] = [self._parse(result) for result in results]
>   File "/app/boefjes/boefjes/local.py", line 73, in <listcomp>
>     parsed: List[NormalizerResult] = [self._parse(result) for result in results]
>   File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 46, in run
>     certificates, certificate_subject_alternative_names, hostnames = read_certificates(
>   File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 124, in read_certificates
>     cryptography.hazmat.backends.openssl.x509.rsa.RSAPublicKey,
> AttributeError: module 'cryptography.hazmat.backends.openssl' has no attribute 'x509'
> ```

That's strange. I've just pulled the latest main and your stack trace seems to show different code (there are line number mismatches, and there's no reference to an `x509` attribute in the current main code as suggested by the stack trace). Does this come from a development setup or production?

**Comment by noamblitz** [comment]
This bug is fixed already @ammar92 

> > Does not seem to be solved yet (on main branch 16 February):
> > ```python
> > [2023-02-16 12:39:22 +0000] [8] [INFO] [job_handler] Handling normalizer kat_ssl_scan_normalize[0ca4725ac6ef471a9cdc8ea8475fc129]
> > [2023-02-16 12:39:22 +0000] [9] [INFO] [local] Running local normalizer plugin
> > [2023-02-16 12:39:22 +0000] [9] [ERROR] [app] An error occurred handling scheduler item 4ef39934f97a433ba49635eabe6d9a02
> > Traceback (most recent call last):
> >   File "/app/boefjes/boefjes/app.py", line 101, in start_working
> >     item_handler.handle(p_item.data)
> >   File "/app/boefjes/boefjes/job_handler.py", line 175, in handle
> >     results = self.job_runner.run(normalizer_meta, raw)
> >   File "/app/boefjes/boefjes/local.py", line 70, in run
> >     return self._parse_results(normalizer_meta, results)
> >   File "/app/boefjes/boefjes/local.py", line 73, in _parse_results
> >     parsed: List[NormalizerResult] = [self._parse(result) for result in results]
> >   File "/app/boefjes/boefjes/local.py", line 73, in <listcomp>
> >     parsed: List[NormalizerResult] = [self._parse(result) for result in results]
> >   File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 46, in run
> >     certificates, certificate_subject_alternative_names, hostnames = read_certificates(
> >   File "/app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py", line 124, in read_certificates
> >     cryptography.hazmat.backends.openssl.x509.rsa.RSAPublicKey,
> > AttributeError: module 'cryptography.hazmat.backends.openssl' has no attribute 'x509'
> > ```
> 
> That's strange. I've just pulled the latest main and your stack trace seems to show different code (there are line number mismatches, and there's no reference to an `x509` attribute in the current main code as suggested by the stack trace). Does this come from a development setup or production?
