### ISSUE TITLE
bootstrap_octopoes creates new AMQP connection for every API request

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#1162]
The `bootstrap_octopoes` function is used as a FastAPI dependency in the Octopoes API. This function creates a new AMQP (RabbitMQ) connection for every API request, even though connections can be shared and not every API call requires an AMQP connection.

Relates to #632, #1127, #1128

**Comment by Lisser** [comment]
We could probably utilize the `startup` event and `app.state` to create a global connection.
```python
@app.on_event("startup")
async def startup():
    rabbit_connection = pika.BlockingConnection(pika.URLParameters(settings.queue_uri))
    channel = rabbit_connection.channel()
    channel.queue_declare(queue="create_events", durable=True)
    app.state.rabbit_connection = rabbit_connection
```

**Comment by praseodym** [comment]
Let's make sure that reconnects also work properly, so that Octopoes doesn't have to be restarted when its connection to RabbitMQ breaks.

**Comment by Donnype** [comment]
@Lisser If we ran FastAPI 0.93.0 we could also use [lifespan events](https://fastapi.tiangolo.com/advanced/events/).
