### ISSUE TITLE
Investigate periodic failure of normalizer tasks being created

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1170]
**Describe the bug**
It seems sometimes the normalizer queue remains empty on some runs on KAT.

**To Reproduce**
1. No idea, start a scan
2. wait for boefje to complete
3. notice normalizer job to not trigger

**Comment by jpbruinsslot** [comment]
I received some logging from @Lisser working on a potential fix here: https://github.com/minvws/nl-kat-coordination/pull/1156

At the moment trying to trigger it locally

**Comment by jpbruinsslot** [comment]
Wasn't able to trigger it locally, the PR https://github.com/minvws/nl-kat-coordination/pull/1156 could potentially fix this. ILet me know if this continues to occur and perhaps if some logging from the scheduler is available when it happens can be helpful.

**Comment by jpbruinsslot** [comment]
Closing. Error seems to be resolved
