### ISSUE TITLE
uWSGI can cause bad gateway error when scaling down number of workers

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#1183]
We are currently using uWSGI in Rocky to handle requests. There seems to be a problem that when scales down the number of workers it might kill a worker that is still handling a request. In the uWSGI log you will see

```
Jun 14 14:30:57 kattest02 kat-rocky[14762]: [busyness] 10s average busyness is at 0%, cheap one of 2 running workers
Jun 14 14:31:05 kattest02 kat-rocky[14762]: worker 1 killed successfully (pid: 819791)
Jun 14 14:31:05 kattest02 kat-rocky[14762]: uWSGI worker 1 cheaped.
```

And there is a 502 in the nginx log:

```
[14/Jun/2023:14:31:05 +0200] "GET /en/test/ HTTP/2.0" 502 150 "https://kattest02.openkat.dev/en/test/kat-alogus/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0)  Gecko/20100101 Firefox/114.0"
```

There seems to be a problem with threading and/or cheaping as described in https://github.com/unbit/uwsgi/issues/1702 and https://github.com/unbit/uwsgi/issues/1804. We could disable both, but then there is not much advantage of using uWSGI compared to other servers like gunicorn and uWSGI is also in maintance-only mode / not much development is going on.

We could switch to gunicorn what we also use for the other services or maybe switch to granian which is a new Python http server in rust and seems to be faster than gunicorn: https://github.com/emmett-framework/granian

**Comment by underdarknl** [comment]
related:
https://github.com/minvws/nl-kat-coordination/pull/1784
