### ISSUE TITLE
Improve environment settings and documentation

### ISSUE THREAD

**Issue by ammar92** [minvws/nl-kat-coordination#1266]
**Is your feature request related to a problem? Please describe.**
It appears to me that over time inconsistencies in the environment settings have grown. For example, some services use DSN parameters while others don't. But also the documentation is not up to date, and sometimes unclear whether a setting is required or not or missing a good example. It could also use more strict validation upon starting. If we validate certain parameters such as URLs then we don't have to wait until the first request to be informed of an incorrect URL setting.

**Describe the solution you'd like**
What I would like to see in the environment settings of the project:
- Consistency in naming
- Better validation
  - For Rocky we already use `django-environ`
  - For the other services where we for example use Pydantic's `BaseSettings` we should use stricter types e.g. URIs, DSNs, Paths (with optionally existence checks), hostnames, etc.
- Up-to-date documentation
  - On what the environment key is used for
  - What type it is (including a helpful example)
  - Whether it's required or not
- Improve `make env`

**Comment by Darwinkel** [comment]
Regarding the documentation, some time ago you made the excellent suggestion to include the sample `.env-dist` directly in the documentation as a code literal. It's a good way to get a single source of truth.
