### ISSUE TITLE
Unify (online) environment variable documentation

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#1276]
Parent: https://github.com/minvws/nl-kat-coordination/issues/1266

Community members have mentioned that expanding KAT's documentation would be nice. This looks like a step in the right direction.

I'm somewhat fond of what PHP does with `php.ini`. It's a self-explanatory config file thanks to the many comments. I think `.env-dist` could employ a similar strategy, which would save us the trouble of having to refer to other resources when discussing/describing config options.

This issue entails:
- [ ] Extending `.env-dist` with some additional comments and context
- [ ] Including `.env-dist` in the online documentation
- [ ] Making sure the online docs contain a single source of truth with regards to describing variables

**Comment by ammar92** [comment]
I like the idea. I think we should also try to avoid using empty environment settings if they're somehow used for automatically generating a `.env` file (e.g. using `make env`).

**Comment by Darwinkel** [comment]
After discussing, we decided to work on this ticket first: https://github.com/minvws/nl-kat-coordination/issues/1299
