### ISSUE TITLE
Scanning large IP-ranges

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1281]
**Describe the bug**
Currently the solution for scanning IP ranges is done by `Nmap`. The current implementation of this tool in KAT does not scale very well for larger IP ranges.

**To Reproduce**
1. Add a fairly large IP-range (e.g. IPv4 /16)
2. Scan with KAT (e.g. TCP top 250)
3. Wait for days

**Expected behavior**
A first indication on which IPs have a reply in about a day for larger ranges. It may be useful to add a tool such as [Masscan](https://github.com/robertdavidgraham/masscan) or [Zmap](https://github.com/zmap/zmap).

**OpenKAT version**
1.9

**Comment by underdarknl** [comment]
closed by https://github.com/minvws/nl-kat-coordination/pull/1340/files
