### ISSUE TITLE
implement Katalogus API filtering/searching/pagination

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1285]
**Is your feature request related to a problem? Please describe.**
We need a clean restfull api on our katalogus server which is to be consumed by the katalogus client in rocky.
This api needs to allow filtering, searching and pagination, to make sure that this is not done in the Rocky frontend.

**Comment by Donnype** [comment]
@underdarknl Could you specify if this applies generically to all Katalogus models or for instance mainly to the database models (`settings`, `organisations`, `repositories`) or the plugins? And if any of these have priority given the current issues for users or in the code?

**Comment by Donnype** [comment]
Related: https://github.com/minvws/nl-kat-coordination/issues/1277

**Comment by underdarknl** [comment]
related: #498
