### ISSUE TITLE
TLS Cipher Suites

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#1302]
We want to include the Cipher Suite Guidelines from [this](https://english.ncsc.nl/binaries/ncsc-en/documenten/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1/IT+Security+Guidelines+for+Transport+Layer+Security+v2.1.pdf) document. To check this (and things about TLS), I want to use [this](https://github.com/drwetter/testssl.sh) tool, which has a nice docker container. 

To check the Key Exchange, Certificate Verification, Bulk Encryption, and Hashing algorithms I will yield the Cipher suite strings with a Cipher Suite mime-type. A Cipher Suite normalizer (with its katalogus settings when deviating from NCSC standards), will then analyze these strings and create findings when certain parts of the suite do not comply with new standards. 

I will look for tools that cut the Cipher Suite strings into parts, and if I cannot find that, I will split the string myself.

**Comment by underdarknl** [comment]
Make sure to test each ip/port (that speaks tls or ssl) for used ciphers instead of just the websites.

**Comment by noamblitz** [comment]
PR: https://github.com/minvws/nl-kat-coordination/pull/1381
