### ISSUE TITLE
Add indemnification on objects that are imported through a Boefje from an external source (e.g. DADB)

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#131]
Currently, adding objects and setting their indemnification level are two separate actions.
We only allow boefjes to set objects, and have the graph / a user set indemnifications for objects because this should be a user initiated action.
However, in the case of using a CMDB like Zcerts DADB as a source of truth, we can safely allow the objects created from that source to be given an indemnification.
I guess we need an option (false by default) which allows a user to toggle wither or not a given boefje can set indemnifications for objects that it created), and we would need a way to store those indemnifications with the inserted data and process them.
Since the given indemnifications will not be set by a user, this means we need to make sure we keep track of its origin (as we are also going to add for manual declarations).

**Comment by Lisser** [comment]
I think this could tie together with some other functionalities like:
- Manual creation of objects from Rocky
- Other sources that 'declare' objects, like Haven or Calvin


It could perhaps be generalized in the following way:

Introduce a new mime-type and associated format, JSON-encoded, which encapsulates:
- one or multiple OOIs 
- declaration type
- scan level

The normalizer can then interpret this and upload it to Octopoes.

Not sure if this already exists though @Donnype ?

**Comment by Lisser** [comment]
Other possibilities: 
- Filter objects created by a certain Boefje (DADB), across organisations
- Set the scan-levels in bulk on those objects

**Comment by underdarknl** [comment]
I agree that for now we can work around this by giving filtering options in the list view, or by allowing the user to see all ooi's directly generated by the DADB normalizer / boefje.

**Comment by Lisser** [comment]
> I agree that for now we can work around this by giving filtering options in the list view, or by allowing the user to see all ooi's directly generated by the DADB normalizer / boefje.

Steps to implement this:
- store the normalizer and boefje name/ID in Octopoes (from normalizer worker)
- add search field in Octopoes API that can search this field
- add search field in Rocky that uses the Octopoes API field
-

**Comment by underdarknl** [comment]
> > I agree that for now we can work around this by giving filtering options in the list view, or by allowing the user to see all ooi's directly generated by the DADB normalizer / boefje.
> 
> Question, currently normalizer ID is already stored in the graph. Boefje ID not yet. Is this required?

No, this boefje will have an accompanying normalizer, which we can target in this query.

**Comment by TwistMeister** [comment]
A UI with the appropriate filters to manually set clearance on newly discovered OOI's from a certain boefje/normalize from DADB would solve this, before doing this automatically.

**Comment by zcrt** [comment]
For now it would be nice to have the option per organisation to:
- [ ] Automatically give pre-defined indemnification on objects yielded from a specific boefje. (E.g. all objects from External Database boefje are to be trusted and given level 3)
- [ ] Show an overview in Rocky of all new assets yielded by a specific boefje that do not have an indemnification, with the option to change indemnification in bulk (with select/deselect boxes)

In addition:
- [ ] On login to KAT show an overview of all new objects that need to be reviewed for all organisations

**Comment by originalsouth** [comment]
After discussion with @underdarknl and @Donnype , it will be our aim to proceed with this as follows: 
- Boefjes that are whitelisted may yield indemnifications
- A maximum indemnification level per Boefje will be respected
- Yielded indemnifications are applied to their referenced OOI

**Comment by Donnype** [comment]
To add to that, we want that systems administrators are able to configure the whitelist (as a safeguard) and not the users.
