### ISSUE TITLE
[mula] Backoff timer multiplier support

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1318]
**Is your feature request related to a problem? Please describe.**
Some boefjes should be ran more often, and some less often. Currently we have 1 setting for the whole scheduler, but more flexibility is needed.

**Describe the solution you'd like**
I propose we allow the boefje-config to contain a multiplier value applied on top of the global scheduler setting to modify the backoff timer when scheduling new jobs.
This modifier doesn't really make sense to include for boefjes by default (I think) so I'd say we allow this setting to be set by the user on the boefje-detail page as wanted, and store it in the katalogus as a setting.
Currently, we dont have 'global' boefje settings, but this would be reasonable to include as a generic configurable for all boefjes, and as such does not need to be included in the main boefje schema but rather in a global setting schema.

**Describe alternatives you've considered**
None yet

**Comment by zcrt** [comment]
Possible duplicate: https://github.com/minvws/nl-kat-coordination/issues/205

**Comment by jpbruinsslot** [comment]
Related implementation: https://github.com/minvws/nl-kat-coordination/issues/204
