### ISSUE TITLE
Some translations are missing in 1.9.0

### ISSUE THREAD

**Issue by vstanojcic** [minvws/nl-kat-coordination#1334]
Waar is de bevinding geconstateerd? (Geselecteerde taal is NL)

1. Bij Account gegevens  "Account details" boven in de paarse balk
"Withdraw acceptance up to level 4 clearance and responsibility" onder aan de pagina

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/e171dbe9-63f7-4e5f-ba51-c4b9fd3a0e3a)

2. Bij Leden  "Members"  boven in de paarse balk
	"An overview of "BRBA" its members."
	Tabel kop -> Diverse attributen in Engels, zoals: "Added", "Assigned clearance level", etc..

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/46477d05-fd72-4b02-86e1-3912fa54a615)

3. Bij Instellingen "Settings" boven in de paarse balk
	"An overview of "BRBA". This shows general information and its settings."
	Knop "Rerun all bits"

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/e37e457e-5566-42ec-8cb3-eb813e6c894f)

	
4. Bij Crisis Room - voor een specifieke organisatie 	"An overivew of the top 10 most severe findings OpenKAT found. Check the detail section for additional severity informaation"
	Kopje: "Top 10 most severe Findings"
	"Weergeven van 10 van 10 objecten" -> dit moet zijn "bevindingen"
	Bij details van een bevinding: "Source OOI" -> Dit moet zijn "Bron OOI"
	Hoofdscherm: "Crisis Room: Brba (brb)" -> Dit moet zijn "Crisis Room: BRBA" (dus niet lowercase en geen organisatie code)

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/ddbf8d0d-bac3-464d-8ab6-54033a7a181d)

	
5. Bij bevindingen	"Objectenlijst" -> moet zijn "Lijst met bevindingen"
	"Weergeven van xx van xx Objecten" -> Dit moet zijn "Bevindingen"
	
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/6bd57829-c2d9-4684-b1db-62b9a8401b60)

6. Bij bevindingen, bij een specifieke bevinding 	"Finding: ...."
	Regel begint met NL en eindigt in EN -> "Overzicht van bevindingen..... This shows general information and its related objects. It also....."
	Details van de bevinding (object type, Proof Description, Reproduce) zijn in het Engels
	"Geen scans gevonden voor dit object" -> Deze zin mist een afsluitende punt!
	
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/ea3e8f82-72c7-446c-9336-f6f65dc1058f)

7. Bij Objecten, filteropties 	2e filter optie -> "Filter by clearance level"
	3e filter optie -> "Filter by clearance type" 
	Geerfd -> moet zijn "Geërfd" (er mist een trema op de e)

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/f03359a0-75ed-4692-b1c1-4f274d73dd39)

8. Bij objecten	"Een overzicht de huidige objecten" -> hier ontbreeekt "van"

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/69662c89-6a38-4217-9ec4-ff33ba660a78)

	
9. Bij objecten, doorklikken op specifiek OOI	Tekst "Overzicht van bevindingen" -> dit moet zijn "Overzicht van objecten" (of object, enkelvoud)
	Bij kopje Scans, als er geen scans wordt gevonden -> Tekst wordt niet netjes afgesloten met een punt.
	Bij kopje Bevindingen -> Tekst is mixed NL/EN en eerste regel eindigt op " en het niveau" zonder dat deze zin netjes wordt afgesloten met 'en het niveau van de bevinding." oid.
	Bij geactiveerd boefje: "Clearance level inheritance"
	Bij geactiveerd boefje: "Show clearance level inheritance"
	
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/1b00e5a1-3b2b-44b4-9dd5-07c44840caed)

10. Drop down lijst van organisaties "All organizations" 

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/75a0cb93-33a3-496e-b270-b70c4e5ee89b)
	
11. Bij sorteer opties staat ""Uitgeschakeld"" en ""Uitschakelen"", deze vertalingen zijn beide niet correct dit moet waarschijnlijk ""Ingeschakeld-Uitgeschakeld"" en ""Uitgeschakeld-Ingeschakeld"" zijn. "
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/793b9c93-cde9-4ed8-a9c6-2ddecaae916e)

12 Filteren in papiamento geeft verkeerde vertaling bij de sorteer opties. Er staat tweemaal "Desaktiva-Aktiva" ipv "Desaktiva-Aktiva" & "Aktiva-Desaktiva"

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/e292a51c-afbb-44ea-a5e6-e775cfea158e)

**Comment by dekkers** [comment]
Translations in rocky that were outdated/wrong have been updated in PR #1439 so this ticket can be closed. Ticket #1443 has been created for translation of other parts that currently don't have translation implemented at all.
