### ISSUE TITLE
Crisis room title camelcases proper names

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1380]
**Describe the bug**
See screenshot and title.

**To Reproduce**
1. Create an organisation with capitals in the name
2. Note the title of the organisation crisis room

**Expected behavior**
Obey the capitalization.

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/78b4cc30-5f7b-437a-b664-a87c551e499f)

**OpenKAT version**
~1.11 Main branch (12/06/23)

**Additional context**
Problem may exist on other places also

**Comment by Rieven** [comment]
I have tested this in main and:

<img width="1122" alt="image" src="https://github.com/minvws/nl-kat-coordination/assets/30832687/a55f5792-5759-4855-9ab1-7d192df69cad">

**Comment by zcrt** [comment]
Seems to have been resolved in newer versions indeed
