### ISSUE TITLE
Display version number of KAT install in web interface

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#139]
_Please add one or more of the following labels to your issue:_
`frontend backend`

**Is your feature request related to a problem? Please describe.**
Various pentesters have the dire request to view the installation number (eg. 1.6RC2) in the KAT GUI. This makes it easier to perform pentests (e.g. we know what has changed since the previous release), but also gives more context to the current features to the admin of the server. 

**Describe the solution you'd like**
A version number in the GUI. 

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by underdarknl** [comment]
The various health endpoints should already show the currently installed release, or the commit hash.
The health end points are usually location on /health but for rocky its on /health/v1 I think.
On the other hand, various pentesters also give us remarks about this version information at all. How should we reconcileboth these questions?

**Comment by Darwinkel** [comment]
Related issue: https://github.com/minvws/nl-rt-tim-abang-rocky/issues/738.

We're looking into integrating `setuptools_scm` which would provide this exact feature.

**Comment by underdarknl** [comment]
resolved in 
https://github.com/minvws/nl-kat-coordination/pull/737
