### ISSUE TITLE
Unclear what a valid dict is for a Config OOI

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1444]
**Describe the bug**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/ae930d15-216d-45bc-8dbe-2d59ccd88912)

**To Reproduce**
1. Try adding the above config.

**Expected behavior**
Seeing the value of the config as a valid dict, or documentation what a valid dict consists of in KAT.

**Screenshots**
See above.

**OpenKAT version**
1.10.0rc2

**Additional context**
I tried to follow https://github.com/minvws/nl-kat-coordination/pull/1172#issuecomment-1614616038

**Comment by underdarknl** [comment]
fix should now be backported to 1.10
