### ISSUE TITLE
Check for clearence level when enabling boefjes

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#1488]
Currently, someone has permission to enable or disable boefjes without checking for clearance levels. This can become problematic in the following situation:

- Alice has clearance level 4
- Alice adds an OOI with clearance level 4.
- Half a year later, Bob, who has clearance level 2 get access to the environment. Meanwhile, a new boefje has been added with clearance level 4. 
- Bob can now enable this boefje which will run on Alice's clearance.

**Comment by TwistMeister** [comment]
Duplicate of #1424 ?

**Comment by noamblitz** [comment]
Yes.
