### ISSUE TITLE
cannot activate boefjes, cannot view boefje detail (as admin)

### ISSUE THREAD

**Issue by ring-ring-ring** [minvws/nl-kat-coordination#1492]
I cannot activate boefjes: 

![image](https://github.com/minvws/nl-kat-coordination/assets/76487016/0377350a-8302-43ea-8877-f061247e8a1e)

I cannot view the boefje detail page, it gives a 403. 

I am admin, clearance L4 on 1.10rc2.

**Comment by Darwinkel** [comment]
Fixed in #1502
