### ISSUE TITLE
strange password rules

### ISSUE THREAD

**Issue by ring-ring-ring** [minvws/nl-kat-coordination#1493]
I must comply to specific password rules when entering a password. Can we use our own password generator @ https://github.com/minvws/horsebattery-laravel ? 

![image](https://github.com/minvws/nl-kat-coordination/assets/76487016/ab635c8f-5988-4cd4-abd2-a03cc0e1c5d6)

**Comment by praseodym** [comment]
Relates to https://github.com/minvws/nl-kat-coordination/issues/942
