### ISSUE TITLE
Deleting a plugin setting doesn't work

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#151]
A confirmation is shown, after confirming the deletion. But the setting remains...

Expected behaviour is the settings value being emptied.

https://user-images.githubusercontent.com/16188579/217838494-1a8ba91a-2845-426f-88b4-d2b83e2c4fc1.mov

**Comment by Rieven** [comment]
@TwistMeister I could not re-create this bug. I have pulled and did make kat for the latest changes.
