### ISSUE TITLE
[Mula] Cleanup unused Boefje fields for tasks in scheduler

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#155]
See `scheduler/models/boefje.py`, a lot of the optional fields will never be passed through bytes.

**Comment by jpbruinsslot** [comment]
@Donnype is there an example that I can check of what fields that I can clean up?

**Comment by Donnype** [comment]
The only fields parsed by runners are defined in `boefjes/boefjes/job_models.py`, so for a Boefje field in a BoefjeMeta we only parse the id and version, etc.
