### ISSUE TITLE
Store clearance levels + description

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#1561]
Store clerance levels + desriptions in an env variable or database so we can make it configurable per KAT-install or per organization, and have a pagein the UI of KAT where the levels get explained to the user.

**Comment by underdarknl** [comment]
same as https://github.com/minvws/nl-kat-coordination/issues/443 ?

**Comment by TwistMeister** [comment]
Exactly like #443 . My bad, I came across this feature in one of my notes and didn't recall making an issue already. Will close this one since it's an exact duplicate.
