### ISSUE TITLE
[Mula] Parallel workers pick up the same task

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#157]
Here we see from the PID that both process 8 and 9 pick up task `21bd137283204f3cb6f9938957cecb38`:

![Image](https://user-images.githubusercontent.com/46660228/218513037-f0159f97-6567-4d60-815b-d498b21cb2a4.png)

**Comment by underdarknl** [comment]
Great find!
A task should be pop-ed from the queue once any worker has been given the task. Rescheduling in case of worker failure will happen after a while anyway, right?

**Comment by jpbruinsslot** [comment]
@Donnype could you check out https://github.com/minvws/nl-kat-coordination/pull/293 and see if the problem persists?

**Comment by Donnype** [comment]
@jpbruinsslot I will check this this afternoon!

**Comment by Donnype** [comment]
Seems quite stable on my laptop, will try my PC (where I initially found this) tomorrow.

**Comment by Donnype** [comment]
Seems quite stable on my PC as well!
