### ISSUE TITLE
Downloading the meta of a dispatched boefje task results in a type error: Object of type Task is not JSON serialisable

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#1588]
When a boefje task is running we provide the option to download its meta before it's completed. This currently doesn't work and results in an error:

![Image](https://github.com/minvws/nl-kat-coordination/assets/16188579/bf32f572-164d-4707-8876-3dd2638ea3dc)

**Comment by praseodym** [comment]
Duplicate of #1523
