### ISSUE TITLE
We need a way for uploaded raw files to target a specific normalizer

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#161]
For our regular scan cycle normalizers we specify in the normalizer which boefjes and other mime-types they consume. 
Not all normalizers might have a diret coupling to a boefje though, and some input programs cannot be ran as boefjes, which in turn forces the user (or some process) to insert raw files directly (or via rocky) into bytes.
These raw files still need to be picked up by the correct normalizer, and I propose to have the normalizers also check for any raw files that have a mimetype in the form of: `normalizer/$normalizer-name` and or `normalizer/$normalizername-$normalizer-version`

This should be a fairly straight forward change in the normalizer runner, however we need to make sure we have a unique name for each normalizer.
currently multiple normalizers are allowed for each boefje, so using the boefje or folder name doesn't work.

once implemented, we can add a 'upload for this normalizer' form on the normalizer detail page in the katalaogus for easy user access to this feature which automatically sets the mime-type of the uploaded raw file.

**Comment by Donnype** [comment]
@underdarknl We could use the normalizer's id? That one should be unique by definition

**Comment by noamblitz** [comment]
This is then something that has to be implemented in the scheduler. Normalizer ID should indeed be fine. Only thing is that an input ooi should be given and that the origins should either be observation or declaration depending on this, which is way less trivial.

**Comment by noamblitz** [comment]
> This should be a fairly straight forward change in the normalizer runner, however we need to make sure we have a unique name for each normalizer. currently multiple normalizers are allowed for each boefje, so using the boefje or folder name doesn't work.

Normalizers do not schedule themselves, so this cannot be done in the normalizer runner

**Comment by Donnype** [comment]
I think if we use the normalizer id this feature is merely changing this in boefjes:

![image](https://user-images.githubusercontent.com/46660228/219055263-c3023625-91e2-4473-9afc-152417e681f5.png)

(or `normalizer.consumes.append(f"normalizer/{normalizer.id}"`)

@noamblitz Perhaps keeping most mime-type constructions in one service is more consistent?

**Comment by noamblitz** [comment]
So that a normalizer always consumes "itself", that sounds like a great idea

**Comment by underdarknl** [comment]
Yup, that's what I was thinking! Seems like an easy new feature, and something that we can easily also expose in the frontend. Once Normalizers gain versioning information, we can add a second mime-type with that info if someone wants to target a specific version.
Input OOI's could and should be optional, and are a separate feature imho.
