### ISSUE TITLE
Linux user kat has /etc as its home directory in /etc/passwd

### ISSUE THREAD

**Issue by kwoot** [minvws/nl-kat-coordination#1612]
**Describe the bug**

Linux user kat has /etc as its homedirctory in /etc/passwd.

**To Reproduce**
1. install openkat

**Expected behavior**
It is not customary to have /etc as the user's homedirectory.
Although the user is configured with nologin as its login process, as soon as an attacker could gain shell access they will be immediately located in the /etc directory. Also if they could perform an scp or ftp action, there would be no need to add a path to extract /etc/passwd and /etc/shadow.

Usually the homedirectory used for an application is its data directory. Like /var/lib/postgres for PostgreSQL.

**Screenshots**

**OpenKAT version**
1.10.1

**Comment by kwoot** [comment]
AFAIK, setting a nonexistent homedir for a user means the shell will default to the root directory. Are you sure you want this?

**Comment by underdarknl** [comment]
On debian / ubunu systems the folder /nonexistent is the default location for users who do not need a homedir.

https://www.debian.org/doc/debian-policy/ch-opersys.html#non-existent-home-directories

**Comment by kwoot** [comment]
I learned something new. Thank you.
