### ISSUE TITLE
Filtering on the findings page does not work correctly - BTVWS

### ISSUE THREAD

**Issue by vstanojcic** [minvws/nl-kat-coordination#1621]
When trying to filter on the findings page there are no filters to be set. 
There are also two buttons to set filters, while one should be sufficient. 

Version used; v1.10.1 

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/9bd32a40-1589-43c4-9737-4f716b871e00)

**Comment by Rieven** [comment]
This one is already resolved
