### ISSUE TITLE
At time-information to object page

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1652]
**Is your feature request related to a problem? Please describe.**
On an object page, there does not seem to be information available on the timing of an object. E.g; when was this object seen for the first time, at which moments in time was it noticed again, etc.

**Describe the solution you'd like**
There are multiple (partial) solutions possible:
- [ ] Adding a simple `first seen` label to an object
- [ ] Showing a simple graph of when an object was seen in time (e.g. selectable last n months/weeks)
- [ ] Selecting the view of an object in a point in time from the object page

**Describe alternatives you've considered**
Maybe a database somewhere already has the answer

**Comment by underdarknl** [comment]
There is a design ticket open for this: https://github.com/minvws/nl-kat-coordination/issues/1544
