### ISSUE TITLE
Findings appear in report despite beind muted & No way to unmute a finding - BTVWS

### ISSUE THREAD

**Issue by vstanojcic** [minvws/nl-kat-coordination#1659]
**Describe the bug**
Muted findings still appear in reports and once a finding is muted there is no simple way to unmute this. 

**To Reproduce**

Report and muted findings 
1. Mute a finding (NO-X-FRAME-OPTIONS & NO-X-PERMITTED-CROSS-DOMAIN-POLICIES) 
2. Make a report 
3. Observe the muted finding still existing in the report 
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/01d52a6c-3e61-473a-9699-77c8bd2cd61c)

No option to unmute 
1. Mute a finding 
2. Filter on the finding page to see the muted findings (Show muted findings) 
3. See the muted finding with no options to unmute 
![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/8efbc3e5-fef6-4649-9d61-34449f06216a)

Double mute prompt
5. Mute another finding 
6. Go to the muted findings page again and see a prompt to double mute these findings 

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/c35cf54e-3094-449f-840e-3339b40ef87b)

**Expected behavior**
Expected to mute and unmute findings with ease. 
Muted findings not reappearing in the report, or atleast give them a "Muted findings" section in the report. 

**OpenKAT version**
1.11.0rc1

**Comment by underdarknl** [comment]
Hm, interesting, Can we check if we use the same query for both these routes?

**Comment by dekkers** [comment]
The muted findings that should not be in the report is fixed in #1791. Easier unmuting will be implemented in #1696.
