### ISSUE TITLE
User interface issues (language NL) - BTVWS

### ISSUE THREAD

**Issue by vanbuum** [minvws/nl-kat-coordination#1666]
**Describe the bug**
There are still a number of user interface issues using the NL language

**To Reproduce**
See screenshots below

**Issue 1.**
Organization name is missing at the end of the sentence. 

![OpenKat 01](https://github.com/minvws/nl-kat-coordination/assets/124354589/dd0ab197-ae53-41f2-b005-0d9bc4811d26)

**Issue 2.**
Use of the sentence “Een overzicht van uw organisatie objectenlijst” is not correct. The displayed objects are not belonging to the user (“uw”) but are related the the specific organization. So it is better to use something like “Een overzicht van objecten voor organisatie “test”.

![OpenKat 02](https://github.com/minvws/nl-kat-coordination/assets/124354589/abac3548-cf98-48b3-9f97-82be82b178a6)

**Issue 3.**
Object filtering works as expected however the displayed filtering at the top of the screen (“momenteel gefilterd op: Alle”) only displays the OOI-types filtering selected and not the clearance level and/or type when used.

![OpenKat 03](https://github.com/minvws/nl-kat-coordination/assets/124354589/f1a501fd-bb0c-42e6-8bc9-330906969d22)

**Issue 4.**
The first explanatory text at the top of the KAT-alogus screen has an incorrect letter size compared to the other menu options within KAT and the width (scaling) of the text box is not correct. Width is roughly 50% of the overall width of the window and therefore multiple lines are used for the text and leaving a lot of white space besides the text.

![OpenKat 04](https://github.com/minvws/nl-kat-coordination/assets/124354589/31d816b9-ce0b-471a-8671-393979f77110)

**Issue 5.**
Within the KAT-alogus, selecting details of a plug-in: Within the sentence just below the objectenlijst 2 indications are used for clearance level (vrijwaringsniveau), namely (2) and L2 (as an example). Terminology should constant and in this case L2 should be used. Furthermore, spacing should be correctly applied preceding the second instance of the clearance level.

![OpenKat 05](https://github.com/minvws/nl-kat-coordination/assets/124354589/057dcd05-fdbb-4082-9eb0-aaa80702c93d)

**Issue 6.**
Are we using a trailing dot at the end of a sentence yes or no? Anyway, within KAT there should be one method to be used and therefore inconsistency should be avoided.

![OpenKat 06](https://github.com/minvws/nl-kat-coordination/assets/124354589/2f0d4531-4dae-4e44-af4a-01f4a434e37f)

**OpenKAT version**
v1.11.0rc1

**Comment by Rieven** [comment]
- Issue 4: There is a new design for KAT-alogus coming in 1.12
The texts are shorter and bigger. It has to do with the alignment of the settings button
![image](https://github.com/minvws/nl-kat-coordination/assets/30832687/26848aa8-ed91-4e15-81a3-52ba9e98d94f)

- Issue 6: That is not a inconsistency, labels and headings does not end with a dot, only paragraphs. I have added a dot on the enable plugin message.
