### ISSUE TITLE
Makefile clone and clone-main point to an invalid repository

### ISSUE THREAD

**Issue by svenoq** [minvws/nl-kat-coordination#17]
### Describe the bug, issue or concern

When building OpenKAT with the make kat command, it results in multiple errors because the Make file clone and clone-main point to an invalid repository. This results in the following errors:

ERROR: build path /home/ubuntu/nl-kat-coordination/nl-kat-octopoes either does not exist, is not accessible, or is not a valid URL.
ERROR: build path /home/ubuntu/nl-kat-coordination/nl-kat-octopoes either does not exist, is not accessible, or is not a valid URL
ERROR: build path /home/ubuntu/nl-kat-coordination/nl-kat-octopoes either does not exist, is not accessible, or is not a valid URL.

This error is because of the following entries, which has a duplicate minvws/ in the URL.
clone:
	-git clone https://github.com/minvws/minvws/nl-kat-boefjes.git
	-git clone https://github.com/minvws/minvws/nl-kat-bytes.git
	-git clone https://github.com/minvws/minvws/nl-kat-octopoes.git
	-git clone https://github.com/minvws/minvws/nl-kat-mula.git
	-git clone https://github.com/minvws/minvws/nl-kat-rocky.git

clone-main:
	-git clone --branch main https://github.com/minvws/minvws/nl-kat-boefjes.git
	-git clone --branch main https://github.com/minvws/minvws/nl-kat-bytes.git
	-git clone --branch main https://github.com/minvws/minvws/nl-kat-octopoes.git
	-git clone --branch main https://github.com/minvws/minvws/nl-kat-mula.git
	-git clone --branch main https://github.com/minvws/minvws/nl-kat-rocky.git

### To Reproduce
1. git clone https://github.com/minvws/nl-kat-coordination.git
2. cd nl-kat-coordination
3. make kat

### Expected behavior
Build OpenKat

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by confiks** [comment]
Oops, my mistake in #15, sorry.

**Comment by underdarknl** [comment]
this has now been fixed. Thanks for noticing and sending the patch.
