### ISSUE TITLE
KAT creates specific findings on domains that do not exist.

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1701]
**Describe the bug**
When a given domain is found to not exist, this is reported correctly by KAT. However, KAT will also report other information including missing DNS records on the non-existent domain. While technically correct, this is not useful.

**To Reproduce**
1. Scan an NXDOMAIN
2. Notice the findings

**Expected behavior**
A single finding that the domain does not exist, no additional mentions of missing SPF/DKIM/DMARC/....

**OpenKAT version**
1.10.2

**Comment by underdarknl** [comment]
Interesting. KAT sees the domain as valid since it exists as an OOI. It then is consumed by the various boefjes. Those boefjes should probably return NXDomain, and the BITS that run on this information should take into account an existing NXDomain ooi.

**Comment by TwistMeister** [comment]
We'll look into SPF/DKIM/DMARK for now, if there are others where you said "..." we'd like to know which ones specifically.
