### ISSUE TITLE
Refinement of raw file uploads functionality

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#173]
I think the issues @Darwinkel found address a fair point: do we want to be able to optionally link an `input_ooi` when uploading a raw file or are we going to restrict this feature to normalizers creating declarations? And: are we going to assume users needing/using this page often built the normalizer they want to trigger themselves, so they know what the raw file should look like, or do we provide raw file examples (possibly displayed at new Normalizer pages in the Katalogus)? CC @underdarknl

_Originally posted by @Donnype in https://github.com/minvws/nl-kat-rocky/issues/247#issuecomment-1431190680_

**Comment by underdarknl** [comment]
Showing raw files for earlier jobs, their mimetypes and related normalizers is already in the design at our figma.
Adding raw files specific for a given normalizer is handled in another issue, but we should investigate adding raw files bound to a given Input OOI for sure. This seems like a good way to help users start with their 'out of bounds' scan tools, which OpenKAT can not (yet) use directly.

**Comment by underdarknl** [comment]
further work can be done in https://github.com/minvws/nl-kat-coordination/issues/2531
