### ISSUE TITLE
Add front-end insight into Bytes Database

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1733]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to inspect the current status of the Bytes Database from the front-end. As this is the database that holds the raw scan results, having front-end insight into this database can help end-users of KAT inspecting the quality of scans.

**Describe the solution you'd like**
Maybe a new tab in the interface where raw scan results can be inspected, searched, viewed and filtered from the interface.

**Describe alternatives you've considered**
Hoping that KAT will always parse all scan output completely and correctly.

**Additional context**
Issue from the old list (April)

**Comment by underdarknl** [comment]
We already have issues for this. Please search for them.
