### ISSUE TITLE
Clearance level inheritance for Level 0.

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1739]
**Is your feature request related to a problem? Please describe.**
To find the origin of an object one can use the clearance level inheritance option. However, this option is not available for objects with L0. When an object is created from an object with clearance level inheritance, but got L0, it is still useful to know where the inheritance of 0 came from (just as it is from L2 to L1).

**Describe the solution you'd like**
Showing the trail/graph path/inheritance for L0 objects.

**Describe alternatives you've considered**
None

**Additional context**
Following up on https://github.com/minvws/nl-kat-coordination/issues/501

**Comment by originalsouth** [comment]
Quick fix for now in #2705. Will address inheritance rules and multi object inference in forthcoming issues.
