### ISSUE TITLE
Aggregate report

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1741]
**Is your feature request related to a problem? Please describe.**
Currently, one can generate a report from individual objects or from an organisation. I would like the option to generate an aggregated report on the whole KAT-installation, respecting any organisation tags (and allowing tag filtering).

**Describe the solution you'd like**
More work is needed here but a report showing some statistics, such as number of organisations, their amount of objects, their number of findings, and a list of critical findings from the last month would be a good start.
In the future, this could extend to a trend report.

**Additional context**
This would be a different type of report compared to an organisation-level technical- or ISO-report.

**Comment by underdarknl** [comment]
I agree. Reports over all organizations should be possible. This is something we'd like to work on after we get the reports per organization to a higher level.
