### ISSUE TITLE
Rocky static files 302

### ISSUE THREAD

**Issue by tobiasBDO** [minvws/nl-kat-coordination#1758]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
After building OpenKAT my Rocky can't reach the static files which results in a weird UI.

**To Reproduce**
1. `make down` bringing down broken environment
2. `cp .env .env-defaults /tmp` save environment for current volumes
3. `docker rmi -f $(docker images -a -q)` remove all images to force complete rebuild
4. `sudo rm -rf nl-kat-coordination` remove all files
5. `sudo git clone --depth 1 --branch v1.11.0 https://github.com/minvws/nl-kat-coordination.git` clone v1.11 again
6. `sudo chown -R tobias:root /nl-kat-coordination` set right ownership
7. `mv /tmp/.env* /nl-kat-coordination` bring back env
8. `cd /nl-kat-coordination && make kat` build environment
9. Check the webpage which is exposed via an Nginx proxy over ssl

**Expected behavior**
I expect the webpage to be the fully functional OpenKAT login page/UI.

**Screenshots**
![afbeelding](https://github.com/minvws/nl-kat-coordination/assets/123560075/a83dbeb9-ff4e-4c55-a01a-7977bdf7abcf)

**OpenKAT version**
v1.11.0 built with `make kat`

**Desktop (please complete the following information if relevant):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 117

**Additional context**
```sh
[08/Sep/2023 08:56:21] "GET /nl/ HTTP/1.0" 200 6265
[08/Sep/2023 08:56:21] "GET /static/dist/app.css HTTP/1.0" 302 0
[08/Sep/2023 08:56:21] "GET /static/dist/manon.js HTTP/1.0" 302 0
[08/Sep/2023 08:56:21] "GET /static/img/keiko.jpg HTTP/1.0" 302 0
[08/Sep/2023 08:56:21] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:21] "GET /static/img/kat_logo.png HTTP/1.0" 302 0
[08/Sep/2023 08:56:21] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:21] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:21] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:22] "GET /static/js/dropdown.js HTTP/1.0" 302 0
[08/Sep/2023 08:56:22] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:22] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:28] "GET / HTTP/1.0" 302 0
[08/Sep/2023 08:56:28] "GET /nl/ HTTP/1.0" 200 6265
[08/Sep/2023 08:56:29] "GET /static/dist/app.css HTTP/1.0" 302 0
[08/Sep/2023 08:56:29] "GET /static/js/dropdown.js HTTP/1.0" 302 0
[08/Sep/2023 08:56:29] "GET /static/dist/manon.js HTTP/1.0" 302 0
[08/Sep/2023 08:56:29] "GET /static/img/kat_logo.png HTTP/1.0" 302 0
[08/Sep/2023 08:56:29] "GET /static/img/keiko.jpg HTTP/1.0" 302 0
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 7013
[08/Sep/2023 08:56:29] "GET /nl/login/ HTTP/1.0" 200 701
```

**Comment by praseodym** [comment]
Could you try removing the static files using `rm -Rf rocky/node_modules rocky/assets/dist rocky/.parcel-cache` and then running `make kat` again?

**Comment by tobiasBDO** [comment]
> Could you try removing the static files using `rm -Rf rocky/node_modules rocky/assets/dist rocky/.parcel-cache` and then running `make kat` again?

I already tried this taking the command from the Makefile, does not help sadly.

**Comment by ammar92** [comment]
I've been going through the code and compared versions, and now it makes sense. The path should be `dist/imports/manon.js`. This and some other references have already been fixed recently, but it's not included in 1.11 yet, unfortunately.

**Comment by tobiasBDO** [comment]
> I've been going through the code and compared versions, and now it makes sense. The path should be `dist/imports/manon.js`. This and some other references have already been fixed recently, but it's not included in 1.11 yet, unfortunately.

But does that explain why I am also getting 302 found instead of 200 on the other existing resources (in the right path)?

```python
tobias@Openkat-test:/nl-kat-coordination/rocky/assets/dist/imports$ curl -i 127.0.0.1:8000/static/img/kat_logo.png
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 07:11:38 GMT
Server: WSGIServer/0.2 CPython/3.11.5
Content-Type: text/html; charset=utf-8
Location: /en/login/
Content-Length: 0
Vary: Accept-Language, Cookie
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

tobias@Openkat-test:/nl-kat-coordination/rocky/assets/dist/imports$ curl -i 127.0.0.1:8000/static/dist/app.css
HTTP/1.1 302 Found
Date: Tue, 12 Sep 2023 07:11:52 GMT
Server: WSGIServer/0.2 CPython/3.11.5
Content-Type: text/html; charset=utf-8
Location: /en/login/
Content-Length: 0
Vary: Accept-Language, Cookie
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
```

**Comment by tobiasBDO** [comment]
for example, a normal working OpenKAT env:

```python
$ curl -i 127.0.0.1:8000/static/img/kat_logo.png
HTTP/1.1 200 OK
Date: Tue, 12 Sep 2023 07:14:08 GMT
Server: WSGIServer/0.2 CPython/3.8.17
Content-Type: image/png
Content-Length: 46258
Content-Disposition: inline; filename="kat_logo.png"
Last-Modified: Wed, 07 Jun 2023 09:23:37 GMT

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

**Comment by ammar92** [comment]
> But does that explain why I am also getting 302 found instead of 200 on the other existing resources (in the right path)?

Yes and no, the 302 is basically telling you to authenticate before reaching any other URL within that directory/ prefix

**Comment by tobiasBDO** [comment]
> > But does that explain why I am also getting 302 found instead of 200 on the other existing resources (in the right path)?
> 
> Yes and no, the 302 is basically telling you to authenticate before reaching any other URL within that directory/ prefix

Is there a way to debug Rocky under the hood? since trying to login with the borked UI doesn't work either. It just goes back to the login

**Comment by tobiasBDO** [comment]
Overview of the network tab while fetching the main page: `https://x.x.x.x/nl/`

![afbeelding](https://github.com/minvws/nl-kat-coordination/assets/123560075/aba78bc5-0885-41c3-b43a-4560a0ce3f37)

**Comment by praseodym** [comment]
> I've been going through the code and compared versions, and now it makes sense. The path should be `dist/imports/manon.js`. This and some other references have already been fixed recently, but it's not included in 1.11 yet, unfortunately.

The move of the JS file and change of the path in the script tag were both done in 2656aa1291340fac677bdb8d211f6c6790d6333a and that commit is not part of v1.11.0. I can only see this being a problem when changing between the `main` and 1.11 branches without `make clean`, because that leaves old static artefacts behind.

**Comment by tobiasBDO** [comment]
It just seems like the whole build process does something funky, when trying to login without the static files it sends a POST request with a 200 response and nothing happens, no errors in the logs nothing.

For now I've edited my `docker-compose.yml` to take the Rocky section from the `docker-compose.release-example.yml` to pull the ghcr.io/minvws/nl-kat-rocky on v1.11.0/

**Comment by dekkers** [comment]
I think the problem is that you have set DEBUG to False. You need to set DEBUG to True, the django runserver command that is used in the development environment will only serve static files if DEBUG is set.
