### ISSUE TITLE
Show more task related metrics for scheduler

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#1768]
Create endpoint that gives overview of task metrics over the past 24 hours. That can be rendered in the front end. Additionally, we want this information to be available  at the metrics endpoint.

**Comment by jpbruinsslot** [comment]
### Backgrounnd

This issue has 2 parts:
1. statistics / aggregation endpoint that can be referenced by rocky
2. task / queue statistics added to the metrics endpoint to be referenced by prometheus

Writing the queries for 1. can also re-used for point 2.

1. How many items are currently on the queue for a scheduler (`qsize`)
2. Aggregation on date range with buckets of every hour for every task status how many items are there

### Discussion

By the nature of how tasks are persisted in the scheduler. Any information on state changes of a task is lost when it's updated. Specifically, the nature of how tasks are managed can result in the loss of information regarding their state changes, making it difficult to perform aggregations over date ranges. This would require us to keep track of those events. 

To address this issue and answer questions such as the current state of the scheduler, the number of items in the queue, the count of schedulers in operation, and the distribution of tasks by their status, we can do this on a request basis, at that moment in time. This information can then be referenced by Rocky. Additionally, we can expose this data via the metrics endpoint that is compatible with Prometheus so this can be leveraged for aggregations on date ranges.

**Comment by jpbruinsslot** [comment]
@underdarknl

**Comment by underdarknl** [comment]
Could you do a Group by on the last update date grouped by hour?
Then we'd be able to see for each of the last 24 hours (eg, 1 default cycle of the scheduler)  how many tasks ended up in the various status groups per hour. Obviously this result would have more pending jobs in the most recent hour, which as you mention would then turn into completed or failed jobs if the user would refresh.

**Comment by jpbruinsslot** [comment]
Metrics endpoint response

```javascript
# HELP app_settings_info Scheduler configuration settings
# TYPE app_settings_info gauge
app_settings_info{katalogus_cache_ttl="30",monitor_organisations_interval="60",pq_grace_period="86400",pq_max_random_objects="50",pq_maxsize="1000"} 1.0
# HELP scheduler_qsize Size of the scheduler queue
# TYPE scheduler_qsize gauge
scheduler_qsize{scheduler_id="boefje-dev"} 0.0
scheduler_qsize{scheduler_id="normalizer-dev"} 0.0
# HELP scheduler_task_status_counts Total number of tasks
# TYPE scheduler_task_status_counts gauge
scheduler_task_status_counts{scheduler_id="boefje-dev",status="pending"} 0.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="queued"} 0.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="dispatched"} 0.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="running"} 0.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="completed"} 12.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="failed"} 0.0
scheduler_task_status_counts{scheduler_id="boefje-dev",status="cancelled"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="pending"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="queued"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="dispatched"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="running"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="completed"} 14.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="failed"} 0.0
scheduler_task_status_counts{scheduler_id="normalizer-dev",status="cancelled"} 0.0
```

**Comment by Darwinkel** [comment]
(Initial round of QA done - feedback will be processed)
