### ISSUE TITLE
Minor visual bug during the onboarding due to slightly too aggressive rounded borders

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#1777]
**Describe the bug**
See screenshot. Minor formatting issue that popped up recently, maybe because of the stylelint changes or something. 

**To Reproduce**
1. `make reset`
2. Enter the onboarding
3. Notice the odd layout

**Expected behavior**
The table should have slightly less aggressive rounded corners, or improved margins/padding.

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/33f87238-34c9-41a7-ae75-7857a0ea9a74)

**OpenKAT version**
Has been on `main` for a while.

**Comment by HeleenSG** [comment]
I can't reproduce this issue on a new branch from main. I have seen it before. The issue you're showing is missing padding on the tile element. 

![Screenshot 2023-09-14 at 12 04 57](https://github.com/minvws/nl-kat-coordination/assets/11405133/eb89b25c-af7d-4969-a343-ec71743c637c)

**Comment by HeleenSG** [comment]
Found and fixed the issue.
