### ISSUE TITLE
OOI detail doesn't show enabled boefjes

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#1778]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
No boefjes show up on the OOI detail.

**To Reproduce**
1. Enable DNSRecords boefje
2. Add hostname
3. Give L2 to hostname

**Expected behavior**

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/43830693/2bdd7ed6-bc28-49ba-ad77-c1d9061071b0)
![image](https://github.com/minvws/nl-kat-coordination/assets/43830693/455525a3-a2b0-41c5-948c-009031b43c73)
![image](https://github.com/minvws/nl-kat-coordination/assets/43830693/73b1a97c-23be-4dc9-a580-63343c6290dc)

**OpenKAT version**
Note the release tag (and if possible: the installation method) here.
If it concerns an in-development version, note the branch(es) and commit hash(es) here as well.

**Desktop (please complete the following information if relevant):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information if relevant):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Darwinkel** [comment]
I can reproduce this.

**Comment by vstanojcic** [comment]
Working fine when I try to reproduce this. 

1. Add a new hostname (mispo in this case)
2. Declare clearance level 2 
3. See the option to enable DnsRecords. 

![image](https://github.com/minvws/nl-kat-coordination/assets/106070140/9f0adea7-ed9b-4ef2-b39e-b8920772a72a)
