### ISSUE TITLE
Mula environment docs are broken due to Pydantic v2 upgrade

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#1815]
The online docs are missing Mula's environment settings:
![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/96fb5798-c191-486f-ad93-1f2200d51505)

See the CI output at the `Compile static HTML` step (e.g. https://github.com/minvws/nl-kat-coordination/actions/runs/6260541583/job/16998773587). 

`settings-doc==3.0.0` has support for Pydantic v2 which is great. It also includes an updated `markdown.jinja` file so we should be good for the future.

Unfortunately for us right now, this means that we are in a situation where some of our modules support Pydantic v2, and some do not. `settings-doc==2.0.0` must be used for Pydantic v1 installs (no backwards compatibility).

We essentially have three options here:

1. I checked, and we can create a workaround in mula's settings such that it tries to load the old pydantic BaseSettings module when DOCS=True. Unfortunately, the rest of the settings file uses some of the newer features in Pydantic which means we will have to create alternate routes for those snippets too. Will get messy very quickly.
2. Focus on upgrading all modules to Pydantic v2
3. Create two separate `settings-doc` compilation pipelines in GitHub Actions and the Makefile, one for Pydantic v1 and one for Pydantic v2. They will have to use two separate jinja templates, but that should be doable. The main challenge here is making sure that a part of the pipeline installs and uses the older Pydantic version, and one part of the pipeline installs and uses Pydantic v2. 

Thoughts and opinions are welcome.

**Comment by praseodym** [comment]
We'll want to (or have to) upgrade to Pydantic v2 eventually, so maybe it's best to focus on that?

Looking at the upgrade instructions, there's even a [upgrade code transformation tool](https://docs.pydantic.dev/latest/migration/#code-transformation-tool), so maybe it's not that big of an effort?

**Comment by underdarknl** [comment]
related to #1841
