### ISSUE TITLE
Design: Report type detail page

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#1829]

**Comment by HeleenSG** [comment]
Contains for example:
- Title
- Description
- Input object type
- Goal (what is the desired outcome of this report type)
- Created by
- Creation date
- Edit/delete option if it's your own (not for version 1)
- Duplicate option to create your own version (not for version 1)
- Available objects
- Saved reports (discuss with Jan) 
- Required/suggested plugins

**Comment by NoemiOverdijk** [comment]
This design is ready for review

https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=1160%3A42564&mode=design&t=fcFdjRzBVpMYBxjL-1

**Comment by underdarknl** [comment]
Looks good to me, I just left some implementation details for our developers on there.
