### ISSUE TITLE
Design flow for "Setup scan" plugin selection when not all object match the required idemnification for all required plugins

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#1838]
A design is needed for the following situation:

When setting up a report the user starts with selecting multiple objects. These objects have different levels of idemnification. 

What do we want to happen?
- Available reports are reports that are within the limitations of all selected objects? Only for required plugins? What do we do with suggested plugins? 
- Reports will be created on all objects that match the required idemnification? 
- Other suggestions welcome

**Comment by underdarknl** [comment]
When a user selects  a bunch of objects, those objects can be consumed by zero or more possible reports.
The reports that we'd show as options for the user to choose from should be the complete set of all reports the selected ooi's can be consumed by.
We should probably show the 'consumed' list of OOITypes for each report on the report selection page.
If a user selects one or more reports, the intersection of OOI's and their type with the selected reports might mean you get one report for OOI A, and two reports for OOI B.

For example, the user selects all his websites, and ip adresses.
A website can be the starting point for the following reports:
* Internet.nl report
* Software report
* DNS Report
An ip address can be the starting point for the following reports:
* Portscan
* Software report

so for each IP you'd get both the portscan and the software report, and for each website you'd also get a software report, but also the internet.nl and dns reports.

**Comment by NoemiOverdijk** [comment]
This design has been reviewed and approved.

The approved design can be found here:
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=1067%3A3513&mode=design&t=PxnKE21ZxHzhtPlS-1

If you want to leave comments on this design, you can do so here:
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=2565%3A8783&mode=design&t=VyesiU0aRhO3gYoK-1
