### ISSUE TITLE
[Bytes] Create an API to export all Mime-types currently known.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#185]
To help users pick Mime-types for their raw uploads, (or figure out which mime-types are currently not covered by a normalizer, but are present in the bytes-store, we should offer an API (and later a frontend) which gives us a list of the Mime-types in the bytes datastore.
This info can be used on the raw-upload form for users to pick from, but we could also list all raw files for a specific mime-type if the user is looking for either examples, or raw fles of a certain type.

**Comment by underdarknl** [comment]
Hm, but the boefjes might not know what mime-types they have created as those might be dynamic.

Eg, the download boefje might have created dozens of actual valid mime-types.
Could we not auto-filter these hashed and internal mime-types out of this api?
The goal is for a user to see which mime-types are already present in his forensic data-store, and then be able to use the katalogus to enable more normalizers based on those mime-types.

For example, the user navigates to the  page displaying the list of mime-types. The user notices 100's of 'application/pdf' and 'application/msword' raw-files. The user then decides to enable the fictional 'bsn-finder' and 'phone-number-finder' normalizers that act on these raw-files.

**Comment by Donnype** [comment]
@underdarknl That sounds more like a count-raw-files-per-mime-type API?

```SQL
SELECT count(*), unnest(r.mime_types) AS mime_type FROM raw_file r GROUP BY mime_type;
```

That would make more sense to me as well. Running this query locally already gives an insane amount of noise from the hashes though to be honest, and it doesn't look like a filter would be trivial per se.

Looking at those hashes though I am still also not sure what they are doing in the mime-type field. The arguments to the boefje meta job say nothing about the file format I'd say, and looking at the code the hash itself can simply be deduced from the `raw_file.boefje_meta.arguments` field?

If we would be able to remove those mime-types, this use cases become a lot more trivial to implement I think.

**Comment by Donnype** [comment]
@jpbruinsslot @ammar92 Perhaps you know where/if the argument hash feature in the mime-types is still used?

**Comment by jpbruinsslot** [comment]
> @jpbruinsslot @ammar92 Perhaps you know where/if the argument hash feature in the mime-types is still being used?

From the scheduler perspective, it seems the hash feature in the mime-types isn't used for anything.

**Comment by Donnype** [comment]
Here is a query that recreates the raw_file table without the hashed mime-types:

```SQL
select m.id,
       secure_hash,
       hash_retrieval_link,
       boefje_meta_id,
       array_agg(mime_type) as mime_types,
       signing_provider_id
from (

select raw.id, boefje_id, unnest(mime_types) as mime_type
    from raw_file raw join boefje_meta b on boefje_meta_id = b.id

) m join raw_file r on r.id = m.id where m.mime_type not like concat('boefje/', m.boefje_id, '-%')
                                   
group by m.id, secure_hash, hash_retrieval_link, boefje_meta_id, signing_provider_id;
```

So we just filter out the pattern "boefje/{boefje_id}-%" for the mime-types. Compared to a `select * from raw_file` and both ordered by id I get the following change (only hash-mime-types removed): 

![Image](https://github.com/minvws/nl-kat-coordination/assets/46660228/ae071851-6de4-46af-ae89-a684047a6a68)


So the migration script would be:

```SQL
with filtered_mime_types as (
    select m.id, array_agg(m.mime_type) as mime_types from (

        select raw.id, boefje_id, unnest(mime_types) as mime_type
        from raw_file raw join boefje_meta b on boefje_meta_id = b.id

    ) m where m.mime_type not like concat('boefje/', m.boefje_id, '-%') group by m.id
)
update raw_file r set mime_types = filtered_mime_types.mime_types from filtered_mime_types where r.id = filtered_mime_types.id;
```

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Onboarding flow works as expected, it's possible to launch new boefjes, which run as expected.

### What doesn't work:
Nothing found. 

### Bug or feature?:
Nothing found.
