### ISSUE TITLE
Add endpoint to octopoes to get related objects by type

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#1881]
Scenario (#1696): An object of type `finding` can have a related object of type `muted_finding`. When this related object exists, the finding counts as muted. To "unmute" the finding, it's needed to get hold of this related object of type `muted_finding`.

There currently is no endpoint we can use in Rocky to do get this related object by type, so that's where this ticket is for. When in Rocky we can retrieve the related object of type `muted_finding` we can use the `delete_ooi` methods that already exist to delete the `muted_finding` object and therefor unmute the `finding`.

**Comment by noamblitz** [comment]
Hmm do we really need that? The PK of the muted finding ooi is known. It's MutedFinding|<pk of finding>. If we create a reference with that knowledge, the muted finding ooi should be fetch able.

**Comment by noamblitz** [comment]
We can also use the new path query for this purpose.
