### ISSUE TITLE
Logging in with 2FA redirects to set-up 2FA

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#1883]
**Describe the bug**
After login with 2FA, KAT redirects to the page telling you to setup 2FA. (You can just continue using KAT however.)

**To Reproduce**
1. Use 1.12.0 with 2FA
2. Login with 2FA
3. Get notified to setup 2FA

**Expected behavior**
Not notifying to setup 2FA if 2FA is already used.

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/82cc57c9-0801-4122-8a5f-0d03f0b3ec76)

**OpenKAT version**
1.12.0

**Comment by underdarknl** [comment]
I was under the impression that this was one of the things we fixed? @dekkers

**Comment by dekkers** [comment]
We forgot to backport the fix to 1.12.
