### ISSUE TITLE
Scheduler not able to reach katalogus

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#1884]
`[WARNING] [Katalogus] Exception: Expecting value: line 1 column 1 (char 0)`

is the result of the scheduler getting a 404 response on the health endpoint of  the katalogus, and is not able to parse the contents of that response. The 404 is the result of  `urljoin` having unexpected results when joining urls that contain a path.

```
>>> urljoin("http://katalogus:8000/katalogus", "health")
'http://katalogus:8000/health'

>>> urljoin("http://katalogus:8000/katalogus/", "health")
'http://katalogus:8000/katalogus/health'

>>> urljoin("http://katalogus:8000/katalogus/", "/health")
'http://katalogus:8000/health'
```

**Comment by jpbruinsslot** [comment]
Additionally the `AnyHttpUrl` from pydantic adds a `/` when you enter a host name, e.g. `http://localhost:8000` it changes it to `http://localhost:8000/`, however if you enter a path is removes the trailing slash. `http://localhost:8000/path/` becomes `http://localhost:8000/path`

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [ ] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

I tried very hard to replicate the situation from the issue, but I couldn't get it to work even after changing some endpoint prefixes in the katalogus' router. Regardless, the PR doesn't seem to introduce any regressions either. I think we can merge this and await feedback from the original reporter.
