### ISSUE TITLE
Wrong label used for naming IPV4NetBlock 

### ISSUE THREAD

**Issue by jvgassel** [minvws/nl-kat-coordination#19]
When adding an object of type:  IPV4NetBlock the wrong label is used in the object list as a name.
Several inputs are needed when adding the IPV4NetBlock, for instance
- network  |  test_network
- name |  internal_lan
- description |  the internal office network
- start_ip |  192.168.1.1
- mask |  24

Then save the object, brings you back to http://localhost:8000/objects/ where all objects are listed.

Now the added IPV4NetBlock is displayed as 24

Expected behavior:
the IPV4NetBlock being displayed as with the input of 'name', in this example: internal_lan

**Comment by underdarknl** [comment]
Thank you, we will look into it. The models are present in the octopoes/models folders, the natural name (eg, the name being shown in the user-frontend) is defined in there too.

**Comment by underdarknl** [comment]
This is now resolved!
