### ISSUE TITLE
Check for availability of sudo command in debian installer script

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1910]
**Is your feature request related to a problem? Please describe.**
Currently our install.sh script does not  check if `sudo` is available, it just assumes as much. Since it cannot install it itself (due to sudo being unavailable) we should let the user know to do this themselves as root.

**Describe the solution you'd like**
Check for sudo, exit and inform the user if not present.

`if ! command -v sudo &> /dev/null
then
    echo "Sudo could not be found, please install sudo as root yourself"
    exit 
`

**Comment by ITNerdbox** [comment]
Or ensure it is run as root by using:

```
if [ "$EUID" -ne 0 ]
  then 
      echo "Please run as root"
  exit
fi
```
And add the `sudo` package as a required package that needs to be installed, like `curl` is.
