### ISSUE TITLE
Further Reports improvements

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#1916]
### What doesn't work:
* [ ] #2566
    * [x]  In the same vein: there is no clear proof-chain / reason why there is a green or red icon in the security measures table in general. 
* [x]  If I mute all findings, there is no change in the security measures table. I think some transparency/explanation about how the results are determined would be nice.
* If I change the query parameters, I can:
    * [x] Observe the future :rocket: 
    * [x] Get a 500 error if I observe a past date, and the input object(s) don't exist then
    * [x] Get a 500 error if I change the OOI's or report to something invalid

### Bug or feature?:
* ~~[ ] During the `Setup scan` step, the page suggests to enable certain plugins. However, disabling/enabling them doesn't have any immediate consequences for the report. It's not entirely clear that this just disables/enables the plugin in the katalogus.~~
* [x] The `Observed at: 17 oktober 2023 23:59 UTC` title is technically not correct. The report was generated/observed before midnight. Shouldn't this be the actual current time?
* ~~[ ] It is not immediately obvious that generating a report before the related plugins have finished running, plus normalizers and bits, results in an incomplete report. I think there should be a status indicator or something to indicate that the report may be incomplete. Of course, this is problematic due to the halting problem we have while scanning. Maybe indicate that a report is likely complete after no new objects/findings have been found after an X amount of time?~~
    * [x] When playing around with the reporting functionality, I actually found that the security measures checkboxes frequently flipped from yes to no depending on how long KAT has been scanning. Other users will notice this for sure.

_Originally posted by @Darwinkel in https://github.com/minvws/nl-kat-coordination/issues/1908#issuecomment-1766480797_

**Comment by noamblitz** [comment]
There are a few more improvements for next sprint:

Like table of content
"overall score mini template"
Clearance level checks
and more...

**Comment by underdarknl** [comment]
@media:print rules to hide non-printable stuff from the page. (eg, headers, footers, underscores on links) Also, open up all 'closed' html parts, since clicking wont be an option once its a printed file.
The optional (there's an ENV setting for this) permalink.
