### ISSUE TITLE
Inconsistent Versioning

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#194]
**Describe the bug**
KEIKO versioning is inconsistent.

**To Reproduce**
1. Generate a report
2. See that it mentions KEIKO 0.0.2
https://github.com/minvws/nl-kat-keiko/blob/5748b1316e8fb5f8478c68e2b03d9bbd46e4f362/templates/bevindingenrapport/template.tex#L38

1. Go to {katurl}/health/v1
2. See that it mentions KEIKO version 0.0.1-development

**Expected behavior**
All places showing KEIKO 1.3.0. If versioning of different components is expected to deviate from official KAT versioning, then at least _consistency_ and an _easily accessible overview_ of what versions KAT is running in the interface is expected.

**Comment by Donnype** [comment]
Closed with https://github.com/minvws/nl-kat-keiko/pull/26
