### ISSUE TITLE
Catch 500 errors in reports

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#1972]
## Describe the bug
Multiple 500 errors occur in the reports.

### 1. Date in the past
A 500 error occurs if I observe a past date, and the input object(s) don't exist then.

**Reproduce**
- Create a report with the Generate Report flow (so a normal report, not an aggregate or multi report)
- Change the date in the URL to something in the past (like the year 2000)
- An "ObjectNotFoundException" should be thrown

### 2. Invalid OOI/report
A 500 error occurs if I change the OOI's or report to something invalid

**Reproduce**
- Create a report with the Generate Report flow (so a normal report, not an aggregate or multi report)
- Change the ooi-value in the URL (eg. remove some characters
- An "Page not found (404) - OOI not found) should be thrown

### 3. Full report
When reviewing a full report with all objects (with minimal L1 clearance), all either generate 500 or seem to run into a timeout. Original issue #2186 

**More details**
The timeout happens we hitting the 'Generate report' button on the page showing which boefjes should be enabled. On hitting the button the browser indicates that it is loading a page, but a new page is never loaded. At some point the browser indication just stops without changing the page.

**Reproduce**
Try making an aggregate report while selecting all report types and all entries available for input.

### 4. Object detail page
Originial issue #2185 
Sometimes the page loads, sometimes it gives 500 Internal Server Error. Z-CERT found the following in the logs:

```
Internal Server Error: /en/**/objects/detail/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by underdarknl** [comment]
lets make sure to have both backend, and frontend validation before we rely on catching upstrream errors / 500s

**Comment by underdarknl** [comment]
This needs some more work, the unittests are failing on value unpacking.

**Comment by noamblitz** [comment]
I think @madelondohmen is busy with other important stuff so I'll pick this up now.
