### ISSUE TITLE
Improvements on setup scan step reports

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#1973]
Discuss with @HeleenSG what consequences it has of enabling or disabling plugins before creating a report.

**Comment by HeleenSG** [comment]
Within manual report setup during configuration, where plugins can be enabled/disabled we should add a warning to alert users to this behaviour. To make them aware. 

![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/5f670d68-f6be-4176-968f-17135441c311)

In the overview of (generated) reports the status will inform the user if plugins are currently running or if they have all finished.

![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/14e2ed28-5dbd-4458-8d9a-ca9452137ee3)

Design workfile: 
https://www.figma.com/file/6vS6Ehh64hyPJB3FKdHf7K/KAT-%7C-Design-%7C-Reports?type=design&node-id=301%3A2&mode=design&t=c6ETcSKf02ILCf42-1

**Comment by noamblitz** [comment]
> In the overview of (generated) reports the status will inform the user if plugins are currently running or if they have all finished.

We are encountering a halting problem here: when is the report completed? This is quite hard or even impossible to know.

**Comment by dekkers** [comment]
> > In the overview of (generated) reports the status will inform the user if plugins are currently running or if they have all finished.
> 
> We are encountering a halting problem here: when is the report completed? This is quite hard or even impossible to know.

As long as the report has a finite set of OOIs as input on which a finite set of boefjes/normalizers run, which is currently the case as far as I know, we should be able to conclude whether they have all been run in the last 24 hours or some other time period.

The halting problem is about whether you can figure out if an arbitrary computer program will finish or not and that is not something we have to do for the reports.

**Comment by noamblitz** [comment]
Haha thanks for explaining the halting problem, but trust me, I know what it is :). 

We could indeed choose to accept that there are currently no reports that have the problem but that they could exist. 

I can imagine a report that shows the amount of web pages of a website and checks the content of each page. I can image websites that have an infinite amount of web pages. KAT will, in that case, encounter the problem that it does not know the difference between "being almost done" or never finishing. 

Again, we could choose to accept this and lay the responsibility on the developer of the report.
