### ISSUE TITLE
[Mula] Implement additional filtering options for api

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#198]
* `models/filter.py`
* `repositories/sqlalchemy/task_store.py`

Implement filter options as `in_`, `notin_`, and free search

**Comment by TwistMeister** [comment]
Closed since this was duplicated by https://github.com/minvws/nl-kat-coordination/issues/182

**Comment by jpbruinsslot** [comment]
> @TwistMeister is there perhaps more info available for requirements on the frontend side?

@TwistMeister 

Reopened, since the duplicate was also closed

**Comment by jpbruinsslot** [comment]
@TwistMeister since this is in the sprint what are the requirements for this?

**Comment by underdarknl** [comment]
Some of these features have been merged by now, correct?
