### ISSUE TITLE
Update xhtml2pdf in requirements.txt

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#1989]
**Is your feature request related to a problem? Please describe.**
Currently we pin to an old version of xhtml2pdf due to a then current issue.
The reason why has been resolved:

https://github.com/xhtml2pdf/xhtml2pdf/issues/589

**Describe the solution you'd like**
See if we can update.

**Comment by ammar92** [comment]
The problem here is that even though this has been fixed, `xhml2pdf` hasn't bumped the `reportlab` (dependency) version to allow version 4 and above

**Comment by underdarknl** [comment]
Ah yes, I did not check for a new release.
