### ISSUE TITLE
Selecting all in the new reporting module result in HTTP 500

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2008]
**Describe the bug**
When selecting all objects available on the reporting page `Setup report` results in HTTP 500.

**To Reproduce**
1. Go to `Reports`
2. Select all
3. Click `Setup report`

**Expected behavior**
No server errors

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/495ccf0d-924b-4db3-b0c2-37314e925604)

**OpenKAT version**
1.13rc2

**Additional context**
The same behavior holds for selecting all and deselecting one. The same behavior also holds when deselecting multiple objects, but then it occurs one step later: on clicking `Continue with selecting`. It is as if the selection is too large to handle

**Comment by underdarknl** [comment]
How many object did you select in one go? And how many report-types?

**Comment by underdarknl** [comment]
@Rieven can you reproduce this?
@zcrt a 500 should also produce tracebacks, could you find them for us?

**Comment by underdarknl** [comment]
@zcrt please provide stack-traces or errors if you can. We are not seeing these issues in our current releases.

**Comment by zcrt** [comment]
Thanks for checking, I suspect it is a local proxy that does not like the complex URL KAT generates on selecting everything on a page, as I get the same error without logging in and I cannot find stack-traces in KAT. We will do some further investigation to find the culprit :)

**Comment by zcrt** [comment]
It turned out that the URL was indeed too large for an internal proxy eventually resulting in HTTP 500 for nginx. Apologies, although I can imagine a future scenario where other applications that are part of OpenKAT but not expecting URLs this large may break
