### ISSUE TITLE
[Mula] Please prefer to use available constants for this, e.g. `HTTP_404_NOT_FOUND` from `fastapi.status`

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#203]
Please prefer to use available constants for this, e.g. `HTTP_404_NOT_FOUND` from `fastapi.status`

**Comment by underdarknl** [comment]
Still relevant?

**Comment by jpbruinsslot** [comment]
No  indeed this has been integrated
