### ISSUE TITLE
[Feature] Flexible Scheduling of Boefjes

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#205]
### Flexible scheduling

Currently, there is one setting to control how often boefjes can run: https://github.com/minvws/nl-kat-mula/blob/657ccad261e0df8b0a6fa20082641b0b2b517014/.env-dist#L29 

It would be great if the setting can be controllable for each boefje and organisation. In that way, it would be possible to make a distinction between 'cheap' boefjes that can run every hour and boefjes that leverage an expensive API that can run once a week. In general, it may be good to put a maximum on the amount of times a boefje can run in a given timeframe, especially when API keys are involved.

### To Reproduce
Try setting different scheduling times for boefjes through the interface.

### Expected behavior
A general default setting for scheduling boefjes, which is overwriteable for each boefje in each organisation. Optionally a setting defining a maximum amount of times that a boefje can run in a given timeframe. This should not apply to boefjes that are started manually (but a warning may be welcome when the boefje is at its limit in a timeframe).

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jpbruinsslot** [comment]
Superseded by #204
