### ISSUE TITLE
Report flow feedback

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#2050]
Original comment from @stephanie0x00 : https://github.com/minvws/nl-kat-coordination/pull/2045#issuecomment-1822860488

- [x] ~Title of the report doesn't specify what type of report it is. It currently says "Report for organisation XYZ"~
- [x] ~The 'Observed at' time in the title of the report shows the UTC time, instead of the system time.~
- [ ] #2253
- [x] ~When selecting both the DNS + System report, the wizard becomes less clear on which plugins are required for what specific report. This is currently not (yet) an issue, but it could become confusing to the end user in the future. (screenshot below).~
- [x] ~There is no option to export the report to PDF for example. Only solution now would be to use the Print functionality of the browser to export to PDF. I think it will also be nice to 'store' these reports so you can view them over time to see the differences.~

![Image](https://github.com/minvws/nl-kat-coordination/assets/46660228/47b94dca-43ba-4bab-8bfc-662dfc6de39d)

**Comment by underdarknl** [comment]
* All times displayed in the frontend should be UTC for now, (and tell the user as much), There's a separate ticket to deal with user-defined timezones based on these settings. https://github.com/minvws/nl-kat-coordination/issues/967
* With multiple selected report types I think we need to label both the selected input ooi's and the plugins with the associated report-types when we show them to clear up why they are shown, and what they will be used for.
* The pdf export is handled in ticket https://github.com/minvws/nl-kat-coordination/issues/1975

**Comment by Donnype** [comment]
Closing because either follow up tickets have been created or these items have been resolved.
