### ISSUE TITLE
Possible data loss when scheduler connection with Bytes is interrupted

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2090]
**Describe the bug**
With KAT 1.12.1 we see multiple examples where after a (failed) job run an empty `.zip`-file is returned when downloading `meta and raw data`. At 1.13.0rc2 only old examples of this behavior can be found, indicating that the problem may be solved already. However, it may still be that when the scheduler is not able to reach Bytes the meta and raw data for a job is never stored although the job is executed.

**To Reproduce**
Unclear, but potential steps to reproduce the behavior:
1. The behavior was seen with the Nmap IP range boefje, so scanning that on an older KAT version may reproduce the issue
2. Experiments could be done with interrupting the connection between the scheduler and bytes.

**Expected behavior**
Some kind of notice of unexpected behavior (there should at least always be metadata for a job). 

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/626b186b-41df-4455-9109-0a27f8f118dc)

**OpenKAT version**
`1.12.1`, old examples on `1.13.0rc2`

**Additional context**
This issue is mostly for future reference. Problems with scheduler connections have been solved in 1.13.0rc2, however, the underlying issue may still exist when communication between the scheduler and Bytes is interrupted.

**Comment by jpbruinsslot** [comment]
Closed due to age
