### ISSUE TITLE
Finding severity 'Pending' not cleared

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2109]
After scheduling boefjes some of the findings receive the severity/status 'Pending' which never gets resolved to a real severity, while there are no more pending tasks. This happens both after completing the onboarding flow, as well as when enabling boefjes manually. My guess is that i

**To Reproduce**
Go through the onboarding flow and an URL. Wait until it's done. After half an hour waiting you still see 'Pending' findings. In the example here the domain mispo.es was used. 

**Expected behavior**
Once all tasks are completed (and waiting an additional period in case additional things are scheduled in the background) some findings remain on the severity 'Pending' instead of being cleared or receiving an actual severity.

**Screenshots**
In the screenshot below all findings are filtered for the status 'Pending'. Other findings and severities are shown when removing the filter. 
 
![finding-pending-only](https://github.com/minvws/nl-kat-coordination/assets/9821756/0b77891a-5601-47ac-aa08-1117adde25ce)

**OpenKAT version**
Currently at: commit 600dea76a1ad662265f3bd9aaa635f761853ed5d (HEAD -> main, origin/main, origin/HEAD), however have seen this occur for some time now.

**Comment by underdarknl** [comment]
This happens when the required Boefje isn't scheduled or enabled.
Are the various level 0 finding hydration boefjes enabled in your katalogus?

**Comment by stephanie0x00** [comment]
I've done a 'make reset' and only added https://mispo.es during the onboarding. The screenshots below show that: 
- Pending findings are still there
- Which boefjes are enabled, I've filtered on boefjes and only enabled boefjes in the screenshot. 
- Which tasks have run

![bug-pending-findings](https://github.com/minvws/nl-kat-coordination/assets/9821756/bfd9752d-d7e4-4013-8745-070c5d52d9f9)

![bug-boefjes-enabled](https://github.com/minvws/nl-kat-coordination/assets/9821756/4bf4a470-99a7-4b6c-9d68-730f9c7296f7)

![bug-finding-tasks](https://github.com/minvws/nl-kat-coordination/assets/9821756/9c62db50-c185-471c-8dc6-516f5961061e)


I've also attached the docker logs for: scheduler, katalogus, boefje, octopoes-api + worker, normalizer, rocky and bytes. 

[pending-bytes.txt](https://github.com/minvws/nl-kat-coordination/files/13634209/pending-bytes.txt)

[pending-rocky.txt](https://github.com/minvws/nl-kat-coordination/files/13634210/pending-rocky.txt)

[pending-normalizer.txt](https://github.com/minvws/nl-kat-coordination/files/13634211/pending-normalizer.txt)

[pending-octopoes-api-worker.txt](https://github.com/minvws/nl-kat-coordination/files/13634212/pending-octopoes-api-worker.txt)

[pending-octopoes-api.txt](https://github.com/minvws/nl-kat-coordination/files/13634213/pending-octopoes-api.txt)

[pending-boefje.txt](https://github.com/minvws/nl-kat-coordination/files/13634214/pending-boefje.txt)

[pending-katalogus.txt](https://github.com/minvws/nl-kat-coordination/files/13634215/pending-katalogus.txt)

[pending-scheduler.txt](https://github.com/minvws/nl-kat-coordination/files/13634217/pending-scheduler.txt)

**Comment by underdarknl** [comment]
The correct plugins are enabled, and tasks are being dispatched and ran. So that is working correctly.
Not sure why no 'new' tasks are being created for the new ooi+hydration-plugin combinations though.

**Comment by underdarknl** [comment]
The scheduler seems to finish its log with, maybe that service has gone down, or maybe it crashed the scheduler? Im guessing the scheduler could continue working with the old katalogus-dataset, but im not sure it does.

`nl-kat-coordination-scheduler-1  | [2023-12-11 10:22:00 +0000] [WARNING] [urllib3.connectionpool] Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='katalogus', port=8000): Read timed out. (read timeout=10)")': /v1/organisations/eee/plugins`

**Comment by jpbruinsslot** [comment]
Does the katalogus give any indication in their logging?

**Comment by underdarknl** [comment]
We should at least create a useful error message here, and also return that error in the form of a 404 to whatever service is requesting this organisation's data.

**Comment by underdarknl** [comment]
Fixed by https://github.com/minvws/nl-kat-coordination/pull/2142
