### ISSUE TITLE
Report generation workflow continues to next step while no objects are selected

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2134]
**Describe the bug**
When a user wants to generate a report they should first select the OOIs for which the report should be generated. However when a user forgot to select OOIs, and clicks the "Setup Report" button the interface goes to the second step and gives an error on this page ("Select at least one OOI to proceed."). The user needs to click the "Go back" button in order to select the correct OOIs. 

**Expected behavior**
When forgetting to select OOIs in the first step at: http://127.0.0.1:8000/en/ee/reports/select/oois/ the application should give a notification during this step, before continuing to the next step (http://127.0.0.1:8000/en/ee/reports/select/report-types/?). Meaning the error message should move to the first page and clicking the button should not be allowed before actual OOIs are selected. 

**Screenshots**
![report-workflow-selection](https://github.com/minvws/nl-kat-coordination/assets/9821756/6a491467-e40a-4c20-9b89-18f17446593b)

**OpenKAT version**
commit 1d7df6458a41e1770b62455c931a0c385cc4fef9 (HEAD -> main, origin/main, origin/HEAD)

**Comment by underdarknl** [comment]
Two options here. Do some Javascript magic to check if at least 1 OOI is selected (html5 has no way to do required on groups of checkboxes and require only one), or we choose too select all items (unpaginated) that where on the initial list and proceed with those.

**Comment by HeleenSG** [comment]
Design: 
![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/10ded711-6de5-4b54-992e-d093c3ce0049)

Figma: 
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=1105%3A13835&mode=design&t=rE59dQEL4BWKrQQ7-1
