### ISSUE TITLE
Incorrect Findings (with snyk.io), Because the Version Number Cannot Be Found (by Wappalyzer)

### ISSUE THREAD

**Issue by jordy-kennisnet** [minvws/nl-kat-coordination#2140]
**Incorrect Findings (with snyk.io), Because the Version Number Cannot Be Found (by Wappalyzer)**

When software is identified on a website without an associated version, all potential vulnerabilities are displayed. However, this is often unjustified because the software component used is, in fact, up-to-date.

**To Reproduce**
1.	Scan a website with Wappalyzer (boefje).
2.	Scan a software object without a version number with Snyk.io (boefje).
3.	You will receive all vulnerabilities because the version number is 'null.'

**Expected Behavior**
When Wappalyzer identifies software without a version number, I don't want to see all the potential vulnerabilities. I expect a finding that indicates the inability to retrieve the version of a software component. This finding can then be corrected by manually entering the version number or ignoring it. If there is a policy against displaying version numbers, and you don't want findings related to version numbers not being found, a solution could be implemented with a setting per organization.

**Screenshots**
None

**OpenKAT version**
1.12

**Additional context**
In the RAW file of Wappalyzer you can see that angular is found with 100% confidence, but with version null.
{"slug":"angular","name":"Angular","confidence":100,"version":null,"icon":"Angular.svg","website": "https://angular.io","cpe":"cpe:/a:angularjs:angular.js"

**Comment by underdarknl** [comment]
Maybe we need to ask the user for the version via a BIT, or maybe we make a config and BIT that allows the user to select the desired findings.
