### ISSUE TITLE
Wrong count of IPs in System Specific

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2184]
### Describe the bug
System specific sometimes gives 0/2 IPs, when there are 4 IPs (2x v4, 2x v6)

### Reproduce
If you set up a system with 1/2 IPv4 and 1/2 IPv6 addresses, the total of servers in the system specific section of the report doesn't correspond to the total amount of systems.

### Related
Might be related to #2187 (if IPv6 is not counted, then it may not be counted in system specific as well)

**Comment by Donnype** [comment]
@madelondohmen Do you have a way to reproduce this?

**Comment by underdarknl** [comment]
This issue was send to us By Matthijs / zcert. Ill ask him to provide details.

**Comment by zcrt** [comment]
Did you try setting up a system with 1/2 IPv4 and 1/2 IPv6 addresses? Then in the system specific section of the report the total does not correspond to the total amount of systems. However, I can imagine this is closely related to https://github.com/minvws/nl-kat-coordination/issues/2187; if IPv6 is not counted, then it may not be counted in system specific as well.

**Comment by noamblitz** [comment]
I have tried several ways to reproduce this bug. Everytime I have a system, which is an ipaddress with some hostnames pointing towards it that offers at least van ipservice, it always correctly shows up. My take:

There probably is at least one ipaddress that does not offer an ipservice. Since it does "nothing", it is not considered a system. 

Could that be the case?

**Comment by zcrt** [comment]
> There probably is at least one ipaddress that does not offer an ipservice. Since it does "nothing", it is not considered a system.

Looking at the report I have an IPv6 with open ports but no system type. Could be that e.g. Shodan only delivers open ports and no IPServices? I cannot check the object detail page atm due to https://github.com/minvws/nl-kat-coordination/issues/2213
