### ISSUE TITLE
Preselection for OOIs for Reports

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#2207]
When making a report for Generate or Aggregate report, we want a pre-selected OOIs based on:
- OOIs with clearance levela L1, L2, L3, L4. (excluding L0)
- OOIs which has a declared clearance type

**Comment by underdarknl** [comment]
We should check what the minimal required clearance level of required boefjes is. If that is level 2, then allowing the user to select level 1 ooi's doesn't make sense.
