### ISSUE TITLE
Not all findings are counted for the onboarding DNS report

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2236]
Not all findings are counted for the onboarding DNS report. It seems that DMARC, DNSSEC, DKIM and SPF records are not counted at all. Have verified with different domains, some show a completely empty table (if they have IPv6 support). 

**To Reproduce**
1. Click through the onboarding flow and use https://mispo.es as domain.
2. Get a coffee
3. Observe the mismatch between the DNS report table and the given findings on the Findings page. 

**Expected behavior**
In previous versions the DNS report also contained Medium findings for the domain mispo.es. 

**Screenshots**

![onboarding-dns-report-overview](https://github.com/minvws/nl-kat-coordination/assets/9821756/dbaf7e9c-99d4-4a9c-9f14-4b866130dae5)

![onboarding-dns-report](https://github.com/minvws/nl-kat-coordination/assets/9821756/59fc0f1e-112d-4c3e-91e0-52c8d7ac095b)

**OpenKAT version**
commit b359f1c06081e8f13ed077064a2e5a52115bf7c1 (HEAD -> main, tag: v1.14.0, origin/main, origin/HEAD)

**Comment by underdarknl** [comment]
Hm, it looks like the bits might not have created those findings yet when you where looking at that report, but they did exists when you (somewhat) later looked at the findings page? Is the timestamp listed on the dns-report before or after the first seen date for those missing findings?

**Comment by stephanie0x00** [comment]
After refreshing the dns-report page the numbers are still not shown. The Findings page shows them, thus it looks more like a miscalculation on the dns-report page instead of an issue with the bits.

**Comment by noamblitz** [comment]
The DNS report (old implementation which we should outphase) has a specific set of findings that it shows, thats why there is are mismatch :).
