### ISSUE TITLE
Filtering findings based on Hostname/IP

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2254]
As a user I'd like to get an overview with all identified findings for a specific host on the Findings page. 

This could either be through a search bar, but could also be done based on selecting the hosts in question. Both would be ideal as this depends on the workflow and information request of the user.

**Comment by underdarknl** [comment]
this would be handled via reports, as a simple 'dept search' from a given IP/hostname is probably too simple to cover the actual requirements of this. If however it does cover these requirements its already possibly by doing a regular findings report and limiting the search dept.

**Comment by stephanie0x00** [comment]
I would disagree. As a use case would be to just search through the data and get a quicker overview of what is going on within a network, instead of having to generate a report every time. For some use cases you don't want to actually generate a report, but just want to get an overview of findings for a specific host, or get an overview of a specific type of finding across all hosts, and easily check which items might be related. So I guess a proper search bar could fix this across all items.
