### ISSUE TITLE
Reports - make required and suggested plugins more clear  

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2262]
Splitting issues for: #2007 

> **Is your feature request related to a problem? Please describe.**
> In the new reporting module the user will always be shown a page describing which boefjes should be enabled and have run on the object of the report. This is split in `required` and `suggested` plugins. However, when all required boefjes are already enabled and have run on the object this page is confusing as it seems to suggest things that are already set. Especially the `Suggested plugins` is confusing when those plugins are already enabled.

> Optionally not showing the required plugins when all requirements are already enabled seems like a good idea. But, we might still want to show any not enabled optional plugins for the user to select from.
If all required and optional plugins are enabled I think we should skip this whole screen.

## Possible solutions

- Possibly skip the required/suggested plugins page when all requirements are met. 
- Improve visualisation that all requirements are met, or which ones are not yet met. 
- Others?

**Comment by madelondohmen** [comment]
All these solutions are already implemented:
- We skip the entire page if all plugins are enabled
- We show "All required/suggested plugins are enabled" when only one of the two sections is completed
- Users can show or hide enabled plugins 
- Users only see 4 suggested plugins and can click on a button to show more
