### ISSUE TITLE
Report summary design

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2264]
Report summary needs to give a clear overview on first glance. 

- Prioritise content visually 
- Shows the general results (how is the scanned object/organisation doing?) 
- Easy to interpret

**Comment by RomijnHumanoids** [comment]
Updated organisation report summary for review 10 januari.

https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=2726%3A27132&mode=design&t=kSVq69t4XGKksdxT-1
