### ISSUE TITLE
Investigate ux requirements & design: As a user I would to have a place where I can find my saved reports

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2268]
- Design a place for saved reports

Ability to: 
- Share (Mail? Other kat accounts?)
- Delete
- View
- Update/re-run report for current situation
- Creation date
- Filters used to generate report (e.g: date range, organisation)
- Name?
- Grouping?

Consider additional use cases and bulk

**Comment by NoemiOverdijk** [comment]
A design for this issue is ready for review:
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=2814%3A19928&mode=design&t=GUjHVKpWQLjXNySi-1
