### ISSUE TITLE
Design flow for creating sector reports through organization tags

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#2275]
See the description in https://github.com/minvws/nl-kat-coordination/issues/2244 and https://github.com/minvws/nl-kat-coordination/issues/2245:

### Context

Organizations can be annotated through _tags_, such as "hospital". In practice, these tags are used to categorize organizations into sectors, although an organization could be in several sectors and hence have multiple tags.

Currently in the flow to create a sector report, we select ReportData objects to aggregate the information:
![Image](https://github.com/minvws/nl-kat-coordination/assets/46660228/09f8a5ef-c4aa-4cab-bdbb-54530967d62f)

Ideally, we would also be able to create a sector report with the following flow:

- See the available tags
- Select the tag(s?) you want to create the report for
- See the organizations (ReportData objects) with this tag as a verification
- Continue the regular flow as if we selected these ReportData objects

**Comment by HeleenSG** [comment]
Design: 
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=2657%3A19552&mode=design&t=2RJmopLIeRfejMKt-1

**Comment by NoemiOverdijk** [comment]
We  ( @RomijnHumanoids , @HeleenSG and @NoemiOverdijk ) have decided to let users filter on tags for organisations, instead of creating a seperate flow. The design for this can be found in the figma link in the comment above this one. 

If that's an adequate solution for this issue, we can close this ticket.
@underdarknl

**Comment by NoemiOverdijk** [comment]
This ticket has become obsolete and can be closed. 
It has created some discussion points regarding the way we create sector reports, which will be discussed in a separate ticket.
