### ISSUE TITLE
make kat under Debian 11 (solved)

### ISSUE THREAD

**Issue by trideeindhoven** [minvws/nl-kat-coordination#23]
When running `make kat` under Debian 11 i see the following error:

"ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1."

### To Reproduce
1. make kat
2. See error

### Solution
Debian 11 repository has docker-compose 1.25.0. You need a newer one and this is easily solved by running:
`sudo mkdir /usr/local/bin`
`sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`
`sudo chmod +x /usr/local/bin/docker-compose`

This installs docker-compose v.1.27.4, build 40524192 and that version is compatible with the docker-compose.yml

**Desktop:**
 - OS: Debian 11.4
 - Version docker: 20.10.17, build 100c701
 - Version docker-compose: 1.25.0

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by iwanVgeelen** [comment]
@underdarknl

**Comment by reincode050** [comment]
https://github.com/minvws/nl-kat-coordination/wiki/Installatiehandleiding-KAT#31-docker-installeren

**Comment by trideeindhoven** [comment]
Should my solution be added to the link reincode050 posted above? Without my proposed solution, you cannot install openkat under debian 11.

**Comment by Darwinkel** [comment]
@trideeindhoven I setup OpenKAT with Docker in a Debian 11 VM using the linked instructions without issue a couple of weeks ago. The linked instructions specifically install docker-compose 1.29.2 here https://github.com/minvws/nl-kat-coordination/wiki/Installatiehandleiding-KAT#32-docker-compose-installeren
