### ISSUE TITLE
Jump to specific page on findings view

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2302]
Currently we only have the: first, previous, next and last options to choose to which page you want to jump. However when dealing with a lot of items (e.g. 170 pages) it would be nice to easily select which page you wish to jump to.

This feature mainly results from the current lack of a proper way of searching and/or filtering and/or aggregation on specific findings. 

![page numbers](https://github.com/minvws/nl-kat-coordination/assets/9821756/628ff492-fa0c-4dec-a4a8-38bf466edd44)

**Comment by underdarknl** [comment]
Why not implement the regular paginator class?

**Comment by NoemiOverdijk** [comment]
This design is ready for review

https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-For-review?type=design&node-id=3674%3A18338&mode=design&t=ZMP5Jfx40ra8jF1a-1

**Comment by NoemiOverdijk** [comment]
The following design has been approved for implementation:




![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/4f2e164c-a727-44e8-a0b1-1213a1a0f5b3)


You can find the approved design, including a mobile version and guidelines here:
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/%E2%9C%85-KAT-%7C-Approved-for-implementation?type=design&node-id=1330%3A8253&mode=design&t=qNZWcYmujeC5Twae-1
