### ISSUE TITLE
allow filtering of scan_level_declarion and current scan_level on objects endpoint

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#231]
Currently there is no way to filter the object list on the following criteria, the current octopoes objects api does not yet support this, but does support this on the scan-profiles endpoint.

* Filter on scan profile declaration type (declared, inherited, None)
* Filter on scan profile level (None, 0, 1, 2, 3, 4)

**Comment by Lisser** [comment]
Already implemented
