### ISSUE TITLE
Aggregate systems without vulnerabilities

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2321]
**Expected behavior**
Either do not show systems without vulnerabilities, or group them together on one line

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/115991818/f2a269c7-7a7e-4ac3-b89c-3a286edb2237)

**Comment by underdarknl** [comment]
So, you'd approve of the following Pr?
https://github.com/minvws/nl-kat-coordination/pull/2319
