### ISSUE TITLE
Design a space for generated reports ( Reports page)

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2345]
As a user, I would like to have a place where I can view: 

- the reports that I generated, 
- including their status

**Comment by RomijnHumanoids** [comment]
First draft based on current knowledge about user stories: https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=3217%3A14711&mode=design&t=TJbLkVIpIGQX5fMQ-1

**Comment by NoemiOverdijk** [comment]
The updated design is ready for review:

https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-For-review?type=design&node-id=3416%3A34814&mode=design&t=gIaY86SPIvlK9U2s-1

**Comment by NoemiOverdijk** [comment]
This ticket is ready for implementation.

The approved design can be found here:
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/%E2%9C%85-KAT-%7C-Approved-for-implementation?type=design&node-id=1211%3A1481&mode=design&t=GgJr2UcIuXk78s01-1

The implementation ticket for this ticket is #2626
