### ISSUE TITLE
Add stepper component to design system in figma

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2350]
![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/6815558b-2db2-4fa9-9930-a77660230b61)

**Comment by NoemiOverdijk** [comment]
The design for this component is finished and has been approved. You can find it in in our Design System:
https://www.figma.com/file/MDbpc9K0qjyaoRGAGiDX6t/KAT-%7C-Design-System-%7C-Components?type=design&node-id=1501%3A4402&mode=design&t=yytz8p7aYatRnVsy-1
