### ISSUE TITLE
Refinement DNS report sorting options

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#2352]
The choice of a report design with all DNS records in one table (per domain) offers the user a quick view of all found records per domain. See https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=2713%3A7931&mode=design&t=2sVOBjEr9JuG07Zw-1

If there is a use case where users would want to compare all A records of multiple domains for example, a possible solution would be to group tables per records type instead of per domain. Two questions:
- Is this a realistic use case for our users?
- Would it be technically possible to configure the report in two ways? (: per domain by default & per record type as optional)

**Comment by stephanie0x00** [comment]
> Is this a realistic use case for our users?

I can see use cases where it would be beneficial to easily compare similar type of DNS records. An example would be to verify if all domain names point to the right IPs or IP space (for example after a migration). This feature could also be used to catch potential security misconfigurations (e.g. if old IP space is still used). 

> Would it be technically possible to configure the report in two ways? (: per domain by default & per record type as optional)
Some solutions could be:
- to have a checkbox/selection option somewhere to enable this content, either in the configuration flow, or maybe in your user profile. 
- Add all the data to the appendix, so it's available if necessary, but doesn't clutter the general report.
- Give the user an option before hand to choose how the data in the report (this or maybe others too) should be grouped/organised. However this could easily become a very big question.

**Comment by RomijnHumanoids** [comment]
If there are no technical limitations to implement this I would suggest making it as a configuration step in the report flow. Switching multiple views within a report will create difficulties when exporting into PDF for example.

**Comment by stephanie0x00** [comment]
I think @noamblitz is more able to say how easy or difficult it is to implement this within OpenKAT itself.

**Comment by noamblitz** [comment]
Configurations are currently not possible in reports. If we add support for configurations (which is not that simple), then this will probably be quite trivial.

**Comment by RomijnHumanoids** [comment]
In the design example data is used from multiple record types found on multiple domains. I am not sure if this counts as an aggregate.

**Comment by noamblitz** [comment]
The multiple domains part makes it an aggregate :)
