### ISSUE TITLE
Design periodical report generation

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2354]
Design flow for setting up periodical report generation

- Setup
- Change settings
- See currently scheduled queries
- See generated reports

**Comment by NoemiOverdijk** [comment]
This design is ready for review:
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=3316%3A113692&mode=design&t=pPsCDaEYwQHwrR65-1

**Comment by NoemiOverdijk** [comment]
This design is ready to be implemented and currently only includes the set up for a periodical report.

Approved design:
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/%E2%9C%85-KAT-%7C-Approved-for-implementation?type=design&node-id=1212%3A9635&mode=design&t=JywBE03YqfCUmv6e-1
