### ISSUE TITLE
Generate Report - Downloading outdated report

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2356]
### What doesn't work
'Normal' report:
- The timestamp warning works when working in the browser. However one can still download an report with an outdated timestamp. E.g. when I change the date to: 2020-04-16 in the URL I see the warning  in the browser. However when I download this report it shows the date from the past. A malicious user could use this to tamper with timestamp on his reports and pretend to me compliant at a previous point in time. 

![report-adjusted-timestamp](https://github.com/minvws/nl-kat-coordination/assets/9821756/f64f6448-403c-4d58-8906-40db4b7e7e49)

- It appears the time in the timestamp is not updated. E.g. it shows 11:59 p.m. while I generated the report at 12:23. I expect this can be picked up in a separate ticket. 

_Originally posted by @stephanie0x00 in https://github.com/minvws/nl-kat-coordination/issues/2274#issuecomment-1898510231_

### How to reproduce
- Generate a report via the usual flow
- Change the date in the URL to a date (far) in the past
- Look at the "Observed at" timestamp (this is the old date which can be confusing/misused)
- Click on "Download report"
- The date on the PDF report should be the outdated date as well (which can be confusing/misused)

### Expected behaviour
It shouldn't be possible to download the report with the outdated time stamp on it. 

### Posible solutions
-  If a date is outdated, add "Outdated" instead of the old date in "Observed at", then this will be downloaded in the report as well.

**Comment by noamblitz** [comment]
Looking at the URL, only the date is given as a parameter and not the datetime. Maybe its best to just remove the time from the title?
