### ISSUE TITLE
Generate Report - Wrong timestamp

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2357]
### What doesn't work:
- It appears the time in the timestamp is not updated. E.g. it shows 11:59 p.m. while I generated the report at 12:23. I expect this can be picked up in a separate ticket. 

![report-adjusted-timestamp](https://github.com/minvws/nl-kat-coordination/assets/9821756/f64f6448-403c-4d58-8906-40db4b7e7e49)

_Originally posted by @stephanie0x00 in https://github.com/minvws/nl-kat-coordination/issues/2274#issuecomment-1898510231_

### How to reproduce
1. Generate a report via the usual flow
2. Look at the "Observed at" timestamp

### Expected behaviour
The time should be the time on which the report is generated.

**Comment by noamblitz** [comment]
Looking at the URL, only the date is given as a parameter and not the datetime. Maybe its best to just remove the time from the title?
