### ISSUE TITLE
As a user I want to give my report a name

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#2379]
We need to include the option give a report a name into the flow.
This includes:
- a place in the setup flow
- giving users the option to change the name

**Comment by RomijnHumanoids** [comment]
Design is ready with the option to give your report a name and style at the export settings in the report flow.

REVIEW link: https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-For-review?type=design&node-id=3399%3A15540&mode=design&t=tNmgL8C5JvTYXGYk-1

**Comment by RomijnHumanoids** [comment]
Update: After feedback March 13th the design is slightly updated. The option to add a reference date to the report name is added. https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-For-review?type=design&node-id=3494%3A56598&mode=design&t=kWBxR70mWyPjeJHV-1

**Comment by NoemiOverdijk** [comment]
feedback verwerken

**Comment by RomijnHumanoids** [comment]
Questions in reply to feedback comments sent (review file in Figma). Answers will determine if this ticket is done or the design needs a few adjustments.

**Comment by RomijnHumanoids** [comment]
In progress: kleine feedbackpunten verwerken en daarna done.

**Comment by RomijnHumanoids** [comment]
Design Done: feedback points processed and checked with feedback-givers. For details check the most recent design: https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Archive?type=design&node-id=3399%3A15541&mode=design&t=gHfykeCLoUyppTIS-1

**Comment by RomijnHumanoids** [comment]
Ticket closed. Implementation ticket: https://github.com/minvws/nl-kat-coordination/issues/2775
