### ISSUE TITLE
Save reports

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#2397]
## Report Generation:

Currently, users generate reports by initiating an action and then waiting for the report to be prepared. There is a lack of visibility into the report's progress, particularly whether the report is still scanning or processing.

### Proposal:

Reports are generated in three phases:

1. Generating (Scanning Phase): This phase involves scanners actively scanning data.
2. Processing (Query Phase): During this phase, queries run to create the final report.
3. Done: The report generation is complete.

Storage of reports:
- To address the current challenges, we propose saving the report as an OOI 
- Each objects will contain:

1. > Context JSON of the report
2. > Associated Reports
3. > Input OOIs of the report
4. > A UUID identifier
5. > Creation data

Retrieval:
- We will introduce a "Saved Reports" page
- Page will gather all Report OOI
- Clicking on a report will gather the Report OOI by the UUID, gather the templates of the associated reports, and fill them. This will greatly speed up viewing a report.

Normalization:
Creating a report will kick off the data retreival of the report by first making sure all boefjes have run (V2), then the Processing phase, which will gather the data and save the results as a raw file. After that, normalizers will start creating the OOI(s).

**Comment by underdarknl** [comment]
Can this be closed?

**Comment by noamblitz** [comment]
Yes!!
