### ISSUE TITLE
Update `dnspython`

### ISSUE THREAD

**Issue by ammar92** [minvws/nl-kat-coordination#2399]
**Is your feature request related to a problem? Please describe.**
`dnspython` should be updated to `2.5.0`. It's used in Boefjes (`kat_dns` and `kat_dns_zone`), Rocky and Octopoes.

**Describe the solution you'd like**
- Upgrade the package and fix normalizers

**Describe alternatives you've considered**
Ultimately we'd like to get rid of `dnspython` by normalizing raw (DIG) data. But this is one step easier.

**Comment by dekkers** [comment]
> **Describe alternatives you've considered** Ultimately we'd like to get rid of `dnspython` by normalizing raw (DIG) data. But this is one step easier.

I've just looked into this briefly but I am not really convinced that we need to get rid of dnspython.

The answer.response we get from dnspython and save as raw file is already low-level and similar to output from the dig command line. E.g.

```
>>> import dns.resolver
>>> resolver = dns.resolver.Resolver()
>>> answer = resolver.resolve("openkat.nl", "A")
>>> print(str(answer.response))
id 37529
opcode QUERY
rcode NOERROR
flags QR RD RA
edns 0
payload 65494
;QUESTION
openkat.nl. IN A
;ANSWER
openkat.nl. 7044 IN A 62.204.64.191
;AUTHORITY
;ADDITIONAL
>>> 
```

vs

```
% dig openkat.nl A

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> openkat.nl A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8876
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;openkat.nl.                    IN      A

;; ANSWER SECTION:
openkat.nl.             7026    IN      A       62.204.64.191

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Jan 30 14:26:32 CET 2024
;; MSG SIZE  rcvd: 55
```

**Comment by originalsouth** [comment]
Perhaps `nslookup` would be another candidate?
```
% nslookup -query=A openkat.nl 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   openkat.nl
Address: 62.204.64.191
```

**Comment by originalsouth** [comment]
[dog](https://github.com/ogham/dog):
```
% dog openkat.nl A @1.1.1.1
A openkat.nl. 4h00m00s   62.204.64.191
```
also supports json output:
```
% dog -J openkat.nl A @1.1.1.1
{"responses":[{"additionals":[],"answers":[{"address":"62.204.64.191","class":"IN","name":"openkat.nl.","ttl":14400,"type":"A"}],"authorities":[],"queries":[{"class":"IN","name":"openkat.nl.","type":1}]}]}
```
