### ISSUE TITLE
Human readable primary key in report sections

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2421]
When reading reports we currently use "DNS Report for Hostname|internet|mispo.es" as section headers. However this make the report less readable and more clumpy. It would be great if the section headers could just say "DNS Report for mispo.es". 

This is currently the case for all reports, not just for the DNS report. 

Once this is done it would be nice to make sure all tables in all reports have an introduction text above the table which contains this human readable primary key. For the DNS report an example could be: "The table below gives an overview of the DNS records found for the DNSzone mispo.es.". 

![report-header-name](https://github.com/minvws/nl-kat-coordination/assets/9821756/ed0d6953-3ed6-44f1-8cac-e18f4ac5fd6d)

**Comment by noamblitz** [comment]
This is already fixed in: https://github.com/minvws/nl-kat-coordination/pull/2722
