### ISSUE TITLE
Typo in graph view of the Object Detail page

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#245]
There is a typo in the graph view of the object detail page. 
![Screenshot 2023-01-25 at 10 10 53](https://user-images.githubusercontent.com/118826623/214537395-7fb4c5e8-5500-46a7-b205-cbf34fa643ed.png)

"top" instead of "to"

**Comment by underdarknl** [comment]
make sure to update the translated files too.
