### ISSUE TITLE
Unit tests for Safe Connections Report

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2479]
**Is your feature request related to a problem? Please describe.**
Currently no unit tests have been written for the Safe Connections Report.

**Describe the solution you'd like**
Unit tests should be written.

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Safe connections report seems to work as expected. 

### What doesn't work:
n/a

### Bug or feature?:
n/a
