### ISSUE TITLE
OOIs keep reapearing after deletion

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#2497]
**Describe the bug**
Objects keep reappearing when deleting multiple OOIs. 

**To Reproduce**
1. Make sure the install has multiple pages of OOIs
2. Delete all OOIs as quickly as possible
3. See OOIs reappearing

**Expected behavior**
Objects stay deleted

**OpenKAT version**
Main

**Desktop (please complete the following information if relevant):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by noamblitz** [comment]
Found out that it was because boefjes were already scheduled... Not sure how to handle that.

**Comment by noamblitz** [comment]
Interesting, could very well be the reason

**Comment by underdarknl** [comment]
Maybe we should also delete any jobs related to OOI's that are deleted? If we dont already do so?

**Comment by noamblitz** [comment]
I checked the scheduler and it seems to do that already

**Comment by underdarknl** [comment]
Has this in fact been resolved by the aforementioned fix?

**Comment by originalsouth** [comment]
I think this issues has long been resolved? @noamblitz?

**Comment by noamblitz** [comment]
Yea
