### ISSUE TITLE
Wrong count of objects in report flow

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2503]
When going through the report flow with one Hostname, the object list will show the hostname twice. This will result in an incorrect count on the reports page as shown below. 

![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/16c0f6f6-1aa9-4996-b749-abcb9078b7b8)

**Comment by noamblitz** [comment]
Ive seen a similar issue in the KATalogus, where some objects were listed twice. I will pick this up now.

**Comment by stephanie0x00** [comment]
The bug seems to be related to the checkbox selection in the report flow. First selecting the row and afterwards the 'select all' checkbox gives the multiple objects under certain conditions..

**Comment by stephanie0x00** [comment]
To reproduce:
- Make sure your Hostname has L2 clearance.
- Click Reports.
- Select the checkbox on the **row** of the hostname and click on the button. 
- Click the back button (change selection) to return to the object list. 
- Click the 'select all' button to select all the domains and continue to the next page. 
- The object list should now show the Hostname twice. For every time you repeat these steps another object is added to the list.
