### ISSUE TITLE
Discuss creating a sector report through organisations/reports

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#2574]
Issue #2275 created some discussion regarding the flow for creating a sector report, which we can discuss here.

**Comment by NoemiOverdijk** [comment]
For those not up to date, you can find the comment and the design here:
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=3214%3A876&mode=design&t=pPsCDaEYwQHwrR65-1

<img width="569" alt="Screenshot 2024-02-28 at 16 54 10" src="https://github.com/minvws/nl-kat-coordination/assets/118826623/8e46cb7d-efa8-4a65-b010-77a0115b9cf1">
<img width="569" alt="Screenshot 2024-02-28 at 16 54 19" src="https://github.com/minvws/nl-kat-coordination/assets/118826623/29afa06c-8cd3-4a67-af05-f5a88a619bdd">

**Comment by NoemiOverdijk** [comment]
As a result of this discussion, we (@RomijnHumanoids @HeleenSG @NoemiOverdijk ) have decided to take another look at the entire reports flow. We have looked into ways we can include report generating through query building into the flow. We want to discuss our initial proposal with @noamblitz @underdarknl .
