### ISSUE TITLE
Decouple updating/inserting boefjes/plugins from the OpenKAT installation

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#2629]
**Is your feature request related to a problem? Please describe.**
To quickly respond to new cyber threads it is essential to be able to quickly and smootly introduce a new -or update an existing- boefje/plugin in an existing OpenKAT-installation, without having to update the installation as a whole.

**Describe the solution you'd like**
- For existing boefjes using a docker container adding a setting in the boefje defining the version of the Docker container would be a good first step.
- For new boefjes/normalizers/bits allowing other boefjessources/repos/URLs to be a source of code for boefjes would be beneficial
- Specifically for a boefje such as Nuclei, one would like to be able to update or introduce new templates without leaving the user interface.

**Comment by underdarknl** [comment]
Can this be closed.

**Comment by zcrt** [comment]
I don't think this has been fixed for all boefjes yet?

**Comment by underdarknl** [comment]
Correct. Ill create a new ticket for moving the local boefjes to a new container.
