### ISSUE TITLE
Missing tabler icons in Rocky

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#2639]
- We are missing some icons to use in Rocky
- Update tabler icons

**Comment by stephanie0x00** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make reset`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
Looks good, haven't identified anything weird going on CSS wise. 

### What doesn't work:
n/a

### Bug or feature?:
n/a
