### ISSUE TITLE
Implement periodical report generation

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#2658]
_This ticket is part of epic #2626_

### Detailed description
We want the user to be able to generate reports periodically.

### Feature benefit/User story
As a user, I want to be able to generate reports periodical so that it saves me time by not generating them manually.

### Specifications
The implementation should include…
- Page title and stepper
- Report schedule
- Report format
- Report name

### Screenshots
![Image](https://github.com/minvws/nl-kat-coordination/assets/99282220/3056afa7-8d25-48f2-94e7-36e89ef2a4cd)

### Figma link
https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2325%3A13868&t=yzPYrYFsQAygovBO-1

## Implementation
This ticket is split into multiple smaller tickets:
- [x] #2779 
- [ ] #2774 
- [x] #2775

**Comment by RomijnHumanoids** [comment]
Updated implementation Figma file link: https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2325%3A13868&t=yzPYrYFsQAygovBO-1
