### ISSUE TITLE
Create report history page frontend

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2669]
_This ticket is part of epic #2626_

## Description
The report flow is going to change a bit. The first step is to save the generated reports and show them in a history page. 
This ticket will only create the frontend of the history page. Saving the generated reports is part of issue #2720

On this page, the following sections are included:
* Generate report button
* Tabs
* Filtering and searching
* Table with all the reports (which is foldable an can show more details)
* Pagination
* Options to rerun, share, save and delete selected reports from the table

### Design
https://www.figma.com/design/GJCDuJYinANHYQ6Ystfzgn/%E2%9C%8D%F0%9F%8F%BC-KAT-|-For-Review-|-Reports-Page?node-id=1325-874

## To do
- [x] Save and show "Selected plugins" @dekkers 
- [x] Generate a report -> Refer to new URL with report ID @dekkers 
- [x] Fix schaling/styling of table 
- [x] Bug: "Selected objects()" is empty when opening a saved report @madelondohmen 
- [x] Change "Objects" column name to "Input Objects" @madelondohmen 
- [x] "Input Objects" column: One object = show object, multiple objects = show a number @Rieven 
- [x] "Report types" column: More than 2 rapport types -> add "+..." @Rieven 
- [x] Show maximum of 20 reports @Rieven 
- [x] Get maximum of 6 children for each report when loading the history page @Rieven 
- [x] Expanded row: report types tabel @Rieven 
- [x] Expanded row: subreports (< 6 reports = show, >5 reports = "View all subreports" button) @Rieven 
- [x] New subreports page template with all subreports @madelondohmen 
- [x] Get one report by parent_id to show on subreport page @madelondohmen 
- [x] Rename report_history_list.html to report_history.html @madelondohmen 
- [x] Write unit tests

**Comment by NoemiOverdijk** [comment]
#3020  The design for the grey tags with '+ 2' is done and can be found here:
https://www.figma.com/design/ENe9lxMBTOA3Nd745U7OKP/%E2%9C%85-KAT-%7C-Approved-%7C-Components?node-id=2325-344&t=08oevwd5omh4hrtG-1



![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/498963c7-3fbb-4470-b984-f49d1d2cfcc0)
