### ISSUE TITLE
Nmap normalizer doesn't parse IPv6 addresses into yielded objects

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#2702]
No open ports are currently shown for IPv6 addresses in both the normal as well as the aggregate report, even though these ports were manually verified to be open.

**Comment by underdarknl** [comment]
Does the scanning machine have access to ipv6? Could you verify that the raw files generated by the nmap boefje on these ip's contain the ports?

**Comment by stephanie0x00** [comment]
I think the issue might be the following line in the nmap raw file: 

> `<target specification="2a01:7c8:REDACTED" status="skipped" reason="invalid"/>`

It appears the IP is skipped from scanning completely.

**Comment by noamblitz** [comment]
Is docker specifically configured to allow ipv6 connections? It does not do that by default

**Comment by stephanie0x00** [comment]
Yes, the first code snippet above shows that I can perform ping from inside the docker container to google over IPv6. 

> Ping from the boefje container works
```
root@0aa906c114bf:/app/boefjes# ping6 google.com
PING google.com(ams17s12-in-x0e.1e100.net (2a00:1450:400e:810::200e)) 56 data bytes
64 bytes from ams17s12-in-x0e.1e100.net (2a00:1450:400e:810::200e): icmp_seq=1 ttl=116 time=253 ms
64 bytes from ams17s12-in-x0e.1e100.net (2a00:1450:400e:810::200e): icmp_seq=2 ttl=116 time=9.23 ms```

**Comment by noamblitz** [comment]
Sorry that I didn't read your ticket thoroughly, definitely should have! Should investigate!!

**Comment by stephanie0x00** [comment]
The problem appears to be in the normalizer of IPv6 data. There are no yielded objects for IPv6 addresses.
