### ISSUE TITLE
Aggeragate report doesnt show CVE description, or loses pdf markup when it does show

### ISSUE THREAD

**Issue by tobiasBDO** [minvws/nl-kat-coordination#2725]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
pdf aggregate reports with only vulnerabilities selected generate a mangled report without any CVE descriptions even though they are present on the webpage or they create markupless documents with said descriptions.

**To Reproduce**
1. Go to aggregate reports
2. Select a OOI with CVE's
3. Select vulnerabilities
4. Generate report
5. Export to pdf (won't see descriptions)
6. Open 1 of the CVE details and retry (will see descriptions but no markup)
![image](https://github.com/minvws/nl-kat-coordination/assets/123560075/327a29d8-f70e-4b6c-87f8-920f7321464d)

**Expected behavior**

**Screenshots**

**When downloading as pdf without opening the description:**
![image](https://github.com/minvws/nl-kat-coordination/assets/123560075/ca5a7c7c-7bbf-4b49-b1f6-6c66817b1e9f)

**When downloading as pdf with the description:**
![image](https://github.com/minvws/nl-kat-coordination/assets/123560075/8c67f211-29df-467b-b6bc-557ea661581f)

**OpenKAT version**
`v1.15.0rc1`

**Additional context**

**Comment by madelondohmen** [comment]
This issue should be fixed by now (see PR #2674). I can't reproduce the bug anymore.
