### ISSUE TITLE
Reports flow plugin warning requires content

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2772]
This warning message has mock up content at the moment. The section it's in is ready for implementation therefor this warning message should be filled with actual content. 

Current: 
![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/8aca9dfd-960e-4503-9989-65340cae1043)

Context within the design: 
![Image](https://github.com/minvws/nl-kat-coordination/assets/11405133/b23747dc-30dd-47df-9fa9-c263cc2f127f)

Should contain: 
- Warn users that enabled plugins will keep running automatically
- What to expect when a plugin is enabled (that they will scan objects within their clearance level and that they will stay on and scan automatically)  
-  Plugins can take time. If the user enables them right before generating a report plugins may need time to collect the data.

Design: 
https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/%E2%9C%85-KAT-%7C-Approved-for-implementation?type=design&node-id=1310%3A8530&mode=design&t=IK9lthj7ZYnPuU0D-1

**Comment by stephanie0x00** [comment]
Text suggestion:

```
Warning! Before you proceed read the following points: 

- OpenKAT is designed to scan all known objects on a regular (daily) basis using the enabled plugins and set clearance levels. This means that scans will run automatically.

- Be patient; Plugins can take some time before they have collected all their data.  

- Enabling them just before report generation will likely result in inaccurate reports, as plugins have not finished collecting data.
```

**Comment by dekkers** [comment]
I think it is better to remove `(daily)`. At the moment it is correct because the interval is hardcoded to 24 hours at the moment, but we want to move away from that and be able to support different intervals.

In the text that's already in the design I would also say `If you choose not to enable a plugin` instead of `If you choose not give a plugin permission to run`.

**Comment by madelondohmen** [comment]
> I think it is better to remove `(daily)`. At the moment it is correct because the interval is hardcoded to 24 hours at the moment, but we want to move away from that and be able to support different intervals.
> 
> In the text that's already in the design I would also say `If you choose not to enable a plugin` instead of `If you choose not give a plugin permission to run`.

I've applied your suggestions in this PR #2897 (that implements the warning section).
