### ISSUE TITLE
Export setup - give my report a name

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#2775]
_This feature is part of epic #2626 _

### Detailed description
In the export setup page of the report flow after choosing report format options there will be table showing the results of the choice above: multiple reports per report type, object etc.
As far as it is possible KAT will give a general name to the reports in the list (see the image for examples). 

### Feature benefit/User story
As a user, I want to give my report a name so that I can distinguish them from each other.

### Specifications
The implementation should include…
- The table must have an edit button in every line to let the user give the report its custom name via a modal (see the image with this ticket). 
- The modal starts with the text "Give your report a custom name and optionally add the reports’ reference date to the name. To do so you can select a standard option or use a Python strftime code in the report name.", in which the 'Python strftime' links to https://strftime.org. 
- Then, it has a text input field for the user to give it a name (in which the Python strftime codes are recognised) and a form select to add the reference date of the report to its name. 
- The dropdown gives different options for how specific the reference date must be included (no reference date, timestamp, day, week, month, year). 
- Lastly, the modal has a primary 'Confirm' button and secondary 'Cancel' button.

### Screenshots
![Image](https://github.com/minvws/nl-kat-coordination/assets/148460647/7b3845f1-23b1-4a64-88fd-04c622c17dd4)
![Image](https://github.com/minvws/nl-kat-coordination/assets/148460647/95ecf8af-8034-40ae-8277-a30445699364)

### Figma link
https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2325%3A13868&t=yzPYrYFsQAygovBO-1

## Implementation
_This part should only be filled in by the developers._
### Possible solution
_Outline your proposed solution for implementing the feature. You can include any specific ideas, designs, or functionalities here._

### Alternatives considered
_Describe any alternative approaches or solutions you've considered, and why you believe the proposed solution is superior._

### To do
- [ ] .
- [ ] .

**Comment by RomijnHumanoids** [comment]
Edited the design and implementation notes in this ticket based on new feedback.

**Comment by RomijnHumanoids** [comment]
Updated implementation Figma file link: https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2325%3A13868&t=yzPYrYFsQAygovBO-1

**Comment by RomijnHumanoids** [comment]
Approved for implementation link: https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2693-5918&t=j2KMFqnW709iqwCx-1

**Comment by paulvandenbraken** [comment]
As Kennisnet serviceprovider I want an automated, easily-operated, scheduled and save means of distributing of reports to our stakeholders (schools/edu-serviceproviders) so that we can provider our stakeholders with required information to have them keep their online environments save.

 = = = = = =

We want to distribute reports in a save manner to our stakeholders. (Save encrypted mail, authorized pull from a platform etc. without granting access to OpenKAT for these stakeholders (which introduces extra OpenKAT admin work and monitoring).
