### ISSUE TITLE
kat_answer_normalizer uses mimetypes as input

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#2808]
The kat_answer_normalizer uses the mime type as input: https://github.com/minvws/nl-kat-coordination/blob/5273eaa897206e18775f939d2f426189fc383e21/boefjes/boefjes/plugins/kat_answer_parser/normalize.py#L12

This won't work if the normalizer only gets the input OOI dict as proposed in #2564. This is the only normalizer that uses the mimetype as input for what to do.  I see the following possible solutions:

1. Add the mimetypes to the normalizer function signature
2. Change the answer raw files so that they include the bit instead of using the metadata of the raw file for this information.

My preference would be to do second. I think it would be better if we use the mimetype only to decide which normalizer to run and that raw files include all necessary information for the normalizer instead of using the raw file metadata for this.

Original ticket that implemented this also mentioned this but doesn't clearly state why it was implemented this way: https://github.com/minvws/nl-kat-coordination/issues/288

**Comment by underdarknl** [comment]
Would option 3 be possible, where we set the mime-type from the answer"-boefje" to be whatever question/answer this was?
That way we can target those mime-types with specific normalizers/parsers if we want, or target the generic boefje/answer mime-type (which will still be present) if we want to parse generic answers from raw-files.

**Comment by dekkers** [comment]
> Would option 3 be possible, where we set the mime-type from the answer"-boefje" to be whatever question/answer this was? That way we can target those mime-types with specific normalizers/parsers if we want, or target the generic boefje/answer mime-type (which will still be present) if we want to parse generic answers from raw-files.

That sounds a lot more complex, because the generic normalizer wil always run on the generic type but if there is also a specific normalizer on the specific type we have two normalizers that will create OOIs, so we would also have to introduce some sort of blacklisting to make this work?

I also don't see what we would gain with this, the only thing the normalizer does is copy the config from the raw file into the object. This can just be a generic normalizer for all answers if we add the bit id in the raw file, so there is currently also no need for this complexity.

Implementing option 2 now would also not prevent us from implementing option 3 in the future if there would be a need for it.

**Comment by underdarknl** [comment]
ok, lets do no 2
