### ISSUE TITLE
Design: I want to duplicate boefjes with custom arguments

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#2870]
If you want update the design you can find it in the [Workfile | Boefjes](https://www.figma.com/design/wXSEivzTwUHJkMEPlfG1Ug/%F0%9F%90%88-KAT-%7C-Workfile-%7C-Boefjes?node-id=509-54667&t=gtU6TkFN0qJqOtVa-1)

The inital purpose of this ticket was to create a flow to duplicate/create boefjes with custom arguments. 
After starting on this ticket, two issues came to light that affect this ticket but are not in scope:

1. We need to design a way to upload documents (like images for the Boefjes)
2. We need to revise and redesign the Boefje/plugin detail page.

I have made two separate tickets for this;

- #3309 
- #3308 

There is also a separate ticket for _creating_ boefjes with custom arguments.
- #3318 
-----------

As a user I want to be able to duplicate boefjes and save them as a variant with different settings so I can have multiple pre-sets per boefje. 

Sub ticket of: https://github.com/minvws/nl-kat-coordination/issues/2828
 
Todo: 
- Design flow (wireframe)
- Add entry points
- Space on boefje detail page for variants
- How do we want to show this within the KATalogus
- Option to edit
- Option to duplicate
- Option to setup variables
- Option to delete this variant
- Unhappy flows
- Clearance level (Should this be adjusted based on settings, who should be allowed to do so? What are the implications for KAT)

**Comment by NoemiOverdijk** [comment]
I made a first version of this so it can be reviewed. I have left some comments with questions (some design-related, some more technical)

https://www.figma.com/design/wTD4hfTbZMp0o2G6VmUepU/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Boefjes?node-id=2301-4437&t=MTjbTxGoO2tQ8tV7-1

**Comment by NoemiOverdijk** [comment]
I updated the design based on the initial feedback.
You can review it here:
https://www.figma.com/design/wTD4hfTbZMp0o2G6VmUepU/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Boefjes?node-id=2301-15215&t=LdufrawppYqjj3gj-1

**Comment by NoemiOverdijk** [comment]
I made another version of this. It's just about the flow, so without a redesign of the Boefje detail page. It does not include uploading a photo yet, since we don't have a component for that yet.

You can find the updated design in [For Review | Boefjes](https://www.figma.com/design/wTD4hfTbZMp0o2G6VmUepU/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Boefjes?node-id=2418-16101&t=exrRhKwNDrXmRX4x-1)

**Comment by NoemiOverdijk** [comment]
This ticket is blocked because the flow requires a way to upload a cat picture and a readme file. 
That will be possible with this issue:

- #3309

**Comment by NoemiOverdijk** [comment]
This design is has been approved and is ready for implementation.
You can find the approved design in the [Approved | Boefjes](https://www.figma.com/design/D48Pf9lLpxET1jp0Wsjzw5/%E2%9C%85-KAT-%7C-Approved-%7C-Boefjes?node-id=2301-14554&t=OkC1Ba5bbLcxjHzG-1) file.
