### ISSUE TITLE
Octopoes export / import tool needs Documentation on how to use, what its requirements are, and what is does, and does not do.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#2877]
This new tool does need Documentation on how to use, what its requirements are, and what is does, and does not do.

_Originally posted by @underdarknl in https://github.com/minvws/nl-kat-coordination/issues/2855#issuecomment-2071921858_

**Comment by stephanie0x00** [comment]
The documentation consists of two parts:

- [X] Documentation for xtdb-cli tool help functionality (`$ ./xtdb-cli.py --help`), solved with #3019
- [ ] Documentation for docs.openkat.nl
