### ISSUE TITLE
bug - Rocky - CSRF token not found (Debian Install)

### ISSUE THREAD

**Issue by yowkah** [minvws/nl-kat-coordination#2879]
**Describe the bug**
After a vanilla installation using the Debian installation guide for Rocky linux, after starting all the services and attempting to log in, we get a CSRF token error: 

Reason given for failure:

    CSRF cookie not set.

**To Reproduce**

In the rocky.conf we have set:

DJANGO_ALLOWED_HOSTS="*"
DJANGO_CSRF_TRUSTED_ORIGINS="https://samkat.xxx.xx"

Granian is set to use HTTPS on port 8443 and host 0.0.0.0 with selfsigned certs.

For testing purposes i set up a reverse tunnel and local hostname overwrite using SSH so that i can access this (instead of using a reverse proxy)

ssh \<ipadress of jumpserver\>  -L 443:samkat.xxx.xx:8443

/etc/hosts on my machine contains:
samkat.xxx.xx 127.0.0.1

In a private window (to prevent cache issues)  i go to:
https://samkat.xxx.xx/en/login

The page loads, i type in the credentials and hit login.
I get redirected to the 403 page.

**Expected behavior**
I expected to log in and be redirected to a dashboard or something similar.

**Screenshots**
Screenshots showing the request and response + the request body
![Screenshot_20240423_131508](https://github.com/minvws/nl-kat-coordination/assets/6965826/ea145686-e9c3-4edc-998b-77897b838b33)
![Screenshot_20240423_131611](https://github.com/minvws/nl-kat-coordination/assets/6965826/b3339cea-f3ce-4da2-93af-165833e571bb)

**OpenKAT version**
 1.15.0  installed through Debian packages.
Ubuntu 22.04.04 LTS 

**Desktop (please complete the following information if relevant):**
 - OS: Fedora 39
 - Browser: Firefox 
 - Version: 124.0.2

**Additional context**
Im sorry for the blurring in the screenshots and the aliassing of the TLD and domain. We use publicly signed certificates internally and i don't want to expose their names.

**Comment by underdarknl** [comment]
It looks like your config is correct, and using the ssh tunnel should not matter in this regard.
I do notice that the form data's csrf token and the token in de request send along with it are already out of sync.
I also notice the django application not sending out a new csrf cookie. We have seen more of these issues in the past, and its usually some specific detail that breaks the chains. Finding them, hardening our documentation or code against them is useful though and We'd love to get in touch to sit down and solve this issue with you.

**Comment by yowkah** [comment]
That sounds great. We have some holidays coming up here, so next week I will personally have time to pick this up. If next week doesn't suit you I will have to refer you to a colleague. Do you have a preferred way of setting this up?

**Comment by underdarknl** [comment]
Great, A jitsi call is fine.
Are you a member of our signal group, or you can mail me the your availability / contact details on meedoen@openkat.nl
