### ISSUE TITLE
Discussion: revise the reports history page

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#2885]
As a user I want to see whether and in what way my report is aggregated

**Comment by RomijnHumanoids** [comment]
Also we have to consider whether a table with the objects in the report is relevant what users want to see in an expanded table row on the report in the history page.

**Comment by RomijnHumanoids** [comment]
Also, around discussing what users want to see on the report history page, I would like to discuss whether an 'aggregated' report of multiple DNS reports with different objects is perceived by the user as an aggregate report or a normal report with multiple options. In other words: does 'aggregate' mean to them: multiple objects in the same report, or multiple report types (+multiple objects) in one report.

**Comment by RomijnHumanoids** [comment]
Discussion April 30: For now, with aggregated reports & multiple merged reports (no definite name yet) we show a table with underlying reports inside the expanded row on the reports history page. Every underlying report will have a report type and input object. There is a new ticket for scalable solution of this table, in case there are multiple report types & many objects the mentioned view will not work.

Design scalable solution for expanded row of aggregated/multi reports in report history page [#2894](https://github.com/minvws/nl-kat-coordination/issues/2894) .
