### ISSUE TITLE
Update feature request template

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#2887]
This ticket is part of #2886.

**Is your feature request related to a problem? Please describe.**
When a design ticket is finished, a new implementation ticket is created. To create a good implementation ticket, a template must be created to determine what should and should not be included in the ticket. This template should also be used for new features, which do not yet contain a design. These fields can then be left blank.

**Describe the solution you'd like**
A template that can be copy-pasted into the implementation ticket description, which can then be filled in by the design team.
Also, this template should be visible when a new feature request issue is created.

**Comment by madelondohmen** [comment]
Maybe something like this will be a suiting template. Idea is to fill in as much as possible. For the UX designers, this means to fill in the "About this feature" part. The "Implementation" section will be for the developers to fill in.

________

_Please add one or more of the following labels to your issue:_
`frontend` `backend`

## About this feature
### Detailed description
_Add detailed description of the new feature you'd like to propose. If this feature is related to a problem, what problem does it solve?_

### Feature benefit/User story
_Please also explain why this feature is important or necessary. What benefit does it bring to users? If possible, provide a user story format:_ 

As a [_type of user_], I want to [_action_] so that [_benefit_].

### Specifications
_Please add some specifications for the implementation. What needs to be implemented to match the design?_

The implementation should include…
- Specification 1
- Specification 2

### Screenshots
Include screenshots of the proposed design changes here.

### Figma link
Link to the Figma design for further visualization (if applicable)

### Additional information
Any additional information, considerations, or context that might be helpful for understanding or evaluating the feature request.

## Implementation
### Possible solution
Outline your proposed solution for implementing the feature. You can include any specific ideas, designs, or functionalities here.

### Alternatives considered
Describe any alternative approaches or solutions you've considered, and why you believe the proposed solution is superior.

**Comment by NoemiOverdijk** [comment]
Looks good! I have one suggestion; maybe it's a good idea to make it more explicit which parts are exlusively for the design team or the developers? To ensure people outside of the OpenKAT team know which parts to fill in when submitting a feature request.

**Comment by madelondohmen** [comment]
Maybe something like this would be better then?

________

## About this feature
### Detailed description
_Add detailed description of the new feature you'd like to propose. If this feature is related to a problem, what problem does it solve?_

### Feature benefit/User story
_Please also explain why this feature is important or necessary. What benefit does it bring to users? If possible, provide a user story format:_ 

As a [_type of user_], I want to [_action_] so that [_benefit_].

### Specifications
_Please add some specifications for the implementation. What needs to be implemented to match the design?_

The implementation should include…
- [ ] Specification 1
- [ ] Specification 2

### Additional information
_Any additional information, considerations, or context that might be helpful for understanding or evaluating the feature request._

## Design
_This part should only be filled in by the OpenKAT design team._
### Screenshots
_Include screenshots of the proposed design changes here._

### Figma link
_Link to the Figma design for further visualization (if applicable)_

## Implementation
_This part should only be filled in by the developers._
### Possible solution
_Outline your proposed solution for implementing the feature. You can include any specific ideas, designs, or functionalities here._

### Alternatives considered
_Describe any alternative approaches or solutions you've considered, and why you believe the proposed solution is superior._

**Comment by madelondohmen** [comment]
Templated approved by the team.
