### ISSUE TITLE
Rocky not reachable on port 8000

### ISSUE THREAD

**Issue by trideeindhoven** [minvws/nl-kat-coordination#29]
When installing OpenKAT using the dockerguide at https://github.com/minvws/nl-kat-coordination/wiki/Installatiehandleiding-KAT#41-standaard-installatie i see no errors and port 8000 is open (i see this using `ss -tulpn`).
When i try to reach localhost:8000 the connection is immediately closed (also when i try this using netcat or even `telnet localhost 8000`). I tried both 127.0.0.1 and localhost.

I then do a `docker-compose down` and a `docker-compose up` (not in background) and then i see loads of periodical errors:
```
^[[36;1mkatalogus-db_1         |^[[0m 2022-08-17 11:25:58.906 UTC [35] FATAL:  password authentication failed for user "katalogus_app"
^[[36;1mkatalogus-db_1         |^[[0m 2022-08-17 11:25:58.906 UTC [35] DETAIL:  Password does not match for user "katalogus_app".
^[[36;1mkatalogus-db_1         |^[[0m   Connection matched pg_hba.conf line 99: "host all all all md5"
^[[36;1mkatalogus-db_1         |^[[0m 2022-08-17 11:25:59.835 UTC [36] FATAL:  password authentication failed for user "katalogus_app"
^[[36;1mkatalogus-db_1         |^[[0m 2022-08-17 11:25:59.835 UTC [36] DETAIL:  Password does not match for user "katalogus_app".
^[[36;1mkatalogus-db_1         |^[[0m   Connection matched pg_hba.conf line 99: "host all all all md5"
```
and
```
^[[33;1mkatalogus_1            |^[[0m INFO:     Started server process [1]
^[[33;1mkatalogus_1            |^[[0m INFO:     Waiting for application startup.
^[[33;1mkatalogus_1            |^[[0m INFO:     Application startup complete.
^[[33;1mkatalogus_1            |^[[0m INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
^[[33;1mkatalogus_1            |^[[0m INFO:     172.24.0.7:55194 - "GET /health HTTP/1.1" 200 OK
^[[33;1mkatalogus_1            |^[[0m INFO:     172.24.0.7:55196 - "GET /v1/organisations HTTP/1.1" 500 Internal Server Error
^[[33;1mkatalogus_1            |^[[0m An error occured: (psycopg2.OperationalError) connection to server at "katalogus-db" (172.24.0.3), port 5432 failed: FATAL:  password authenticati>
^[[33;1mkatalogus_1            |^[[0m 
^[[33;1mkatalogus_1            |^[[0m (Background on this error at: https://sqlalche.me/e/14/e3q8). Rolling back session
^[[33;1mkatalogus_1            |^[[0m Traceback (most recent call last):
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3256, in _wrap_pool_connect
^[[33;1mkatalogus_1            |^[[0m     return fn()
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
^[[33;1mkatalogus_1            |^[[0m     return _ConnectionFairy._checkout(self)
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
^[[33;1mkatalogus_1            |^[[0m     fairy = _ConnectionRecord.checkout(pool)
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
^[[33;1mkatalogus_1            |^[[0m     rec = pool._do_get()
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
^[[33;1mkatalogus_1            |^[[0m     self._dec_overflow()
^[[33;1mkatalogus_1            |^[[0m   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
^[[33;1mkatalogus_1            |^[[0m     compat.raise_(
```

I am running using user-id 1000 (important according to the wiki)

### To Reproduce
- Install using docker guide
- last command: `make kat`
- now port 8000 is up, but not reachable using browser. `telnet localhost 8000` immediately closes port

### Expected behavior
Port 8000 reachable on localhost

 - OS: Debian 11.4
 - Browser Firefox 91.11.0

I have saved the full docker-compose up log to:
[docker.log](https://github.com/minvws/nl-kat-coordination/files/9359176/docker.log)

**Comment by underdarknl** [comment]
Dear @trideeindhoven, 
Thank you for your interest in OpenKAT.  This is a new one, but we will have a look to make we can help you. We did release a new version just today, so maybe you found a fresh new bug which needs fixing.

**Comment by ammar92** [comment]
Many thanks for the submission @trideeindhoven. Looking briefly at the logs I can see the following:
- KATalogus DB fails to start because of authentication errors
- KATalogus API fails because it can't establish a connection with the KATalogus DB
- Rocky fails because it can't reach KATalogus API

The latter is obviously not desirable so we're looking into this.

**Comment by noamblitz** [comment]
See solution of https://github.com/minvws/nl-kat-coordination/issues/30

**Comment by noamblitz** [comment]
Katalogus db connection fails because of renaming of env vars

**Comment by noamblitz** [comment]
Another (better) is solution is renaming the env variable names to match those in the env-dist

**Comment by trideeindhoven** [comment]
I can confirm the problem was the .env. I tried pruning the images, but a manual edit of the .env would probably have worked too. Case closed! Thank you noamblitz
