### ISSUE TITLE
Option to restart a task on task page

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#291]
_Please add one or more of the following labels to your issue:_
`frontend`

**Is your feature request related to a problem? Please describe.**
Sometimes you want a recent task to run again (the normalizer or the boefje (or bit)). Currently, you have to find the page for the specific object or navigate to the respective boefje (even if it is only the normalizer that needs re-run).

**Describe the solution you'd like**
A button next to every task on the task page (or a selector combined with a button) to restart that task (both for boefjes, normalizers and bits).

**Describe alternatives you've considered**
Navigating painfully through KAT.

**Comment by underdarknl** [comment]
related: #1159  and #1160 for specific work on both these two job types
