### ISSUE TITLE
Implement modal in setup config flow to show boefje details and "required for"

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#2969]
[Design and specs](https://www.figma.com/design/5lYYfE1SqJ9qofjyvwdvtw/%E2%9C%85-KAT-%7C-Approved-%7C-Reports-Flow?node-id=2450-11365&t=a57AOpwG4aj2PzRt-1)

When implementing the modal for the boefje details, one also has all the data at their disposal to make the "required for x reports" modal, since this part exists in both modals. Because it should be fairly straightforward to create that second modal as well, please consider it part of this task.

**Comment by NoemiOverdijk** [comment]
For more information and detailed specs about the modal component, you can view the documentation on the modal in the [Components Library](https://www.figma.com/design/MDbpc9K0qjyaoRGAGiDX6t/%F0%9F%8E%A8-KAT-%7C-Design-System-%7C-Components?m=auto&node-id=811-9833&t=2OvTVfCl0lamoIYs-1) of the Design System.
