### ISSUE TITLE
OpenMetrics API for Bytes

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#298]
It would be good to have an OpenMetrics API endpoint for Bytes which exposes (at least) the following data:

* Total disk size used.
* Total amount of raw files
* Total amount of organizations

Per organization it could also show the following
* Total disk size used.
* Total amount of raw files

This would help Ops to graph growth of the datastore and provide insights into the trajectory and future storage needs for Bytes.

**Comment by Donnype** [comment]
I guess we assume non-application metrics to be handled by other parts of the stack? E.g. the standard exporter for nginx if you use that in front of your openKAT install for metrics such as `http_requests_total`?

**Comment by Donnype** [comment]
And: do we want the `truth` with respect to the bytes-data volume and its contents or do we want to collect most of the information from the database (for e.g. #rawfiles)?

**Comment by praseodym** [comment]
> And: do we want the "truth" with respect to the bytes-data volume and its contents or do we want to collect most of the information from the database (for e.g. #rawfiles)?

I'd mostly rely on the database because it's a lot faster to query than iterating over the filesystem.

**Comment by praseodym** [comment]
> I guess we assume non-application metrics to be handled by other parts of the stack? E.g. the standard Prometheus exporter for nginx if you use that in front of your openKAT install for metrics such as `http_requests_total`?

Yes, but if we think service-level metrics such as `http_requests_total` are useful we should still consider adding them. It looks like [prometheus_fastapi_instrumentator](https://pypi.org/project/prometheus-fastapi-instrumentator/) (disclaimer: not tested by me) would make this pretty easy to do.

**Comment by Donnype** [comment]
@praseodym Keep in mind that this query has to do a join to group by the organization. It takes roughly 1.3 seconds to perform this query for 2 million files:

```
select bm.organization, count(rf.id) from raw_file rf join boefje_meta bm on bm.id = rf.boefje_meta_id group by bm.organization
```

The directory scan however takes roughly 1.0 seconds in this setup.

**Comment by praseodym** [comment]
@Donnype that's an unexpectedly slow query. But keep in mind that a directory scan might be orders of magnitude slower depending on the characteristics of the underlying storage, e.g. a NFS share will likely be way slower.

**Comment by Donnype** [comment]
Consensus reached in discussion with @praseodym @underdarknl @dekkers: we should recommend [node exporter](https://prometheus.io/docs/guides/node-exporter/) to monitor disk usage of Bytes and can use the database query to fetch the number of raw files per organization, and only configure a cache for this query.
