### ISSUE TITLE
Third party Django lib for template Components

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#2998]
Is it viable and desirable to use [this library ](https://github.com/EmilStenstrom/django-components?tab=readme-ov-file#using-slots-in-templates) or [this](https://github.com/Xzya/django-web-components). What are the drawbacks if we would? The benefit is that it makes reusable Django components easier to implement and use.

**Comment by TwistMeister** [comment]
As discussed on 28-5-2024: @underdarknl @ammar92 and @dekkers will decide on what lib to use, before the end of this week (at may 31st at the latests)

**Comment by ammar92** [comment]
I would opt for `django-components`. It's a more up-to-date package, rich in features, and feels natural to use. We can check the tests in the repository for inspiration on how to write our own tests for our own components.

**Comment by dekkers** [comment]
Django-web-components is pretty similar and someone proposed to [merge the projects](https://togithub.com/Xzya/django-web-components/issues/17), but the author of django-web-components doesn't seem interested in that. The author also says he is currently not working on django-web-components, considers it mostly done and doesn't seem very open to new features.

Django-components is also working on [adding some of the features of django-web-components](https://togithub.com/EmilStenstrom/django-components/discussions/486). So I also think that we should use django-components.

**Comment by underdarknl** [comment]
Lets go with django-components.
