### ISSUE TITLE
bij het starten geven een aantal containers aan dat er niet geauthentiseerd kan worden

### ISSUE THREAD

**Issue by iwanVgeelen** [minvws/nl-kat-coordination#30]
Ik ben vandaag ook aan de slag gegaan om een versie van OpenKat te installeren (en onze eigen boefjes te testen!). Helaas loop ik tegen een probleem aan. Gezien de vorige mail hoop ik dat je me hiermee kan helpen, of doorverwijzen naar de juiste persoon.

Technische Details
Installatie is gestart middels: make kat. De containers worden probleemloos gebouwd, echter bij het starten geven een aantal containers aan dat er niet geauthentiseerd kan worden met de database. De .env file in /nl-kat-coordination/ is gevuld met wachtwoorden, ook lijken de referenties naar dit bestand in de docker-compose goed te staan. Aanvullend heb ik ook geprobeerd om een nieuwe .env te maken via: make env. Helaas heeft dat het probleem nog niet kunnen verhelpen.

Rocky:
…
psycopg2.OperationalError: FATAL: password authentication failed for user "rocky_app"
…
django.db.utils.OperationalError: FATAL: password authentication failed for user "rocky_app"

Katalogus:
…
psycopg2.OperationalError: connection to server at "katalogus-db" (172.25.0.4), port 5432 failed: FATAL: password authentication failed for user "katalogus_app"
…
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "katalogus-db" (172.25.0.4), port 5432 failed: FATAL: password authentication failed for user "katalogus_app"

Bytes:
…
psycopg2.OperationalError: connection to server at "bytes-db" (172.25.0.5), port 5432 failed: FATAL: password authentication failed for user "bytes_app"
…
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "bytes-db" (172.25.0.5), port 5432 failed: FATAL: password authentication failed for user "bytes_app"

**Comment by noamblitz** [comment]
Hi! 

Probleem is dat de volumes (databases) nog bestaan met de credentials die in de oude .env stonden. De makkelijkste oplossing is om docker te prunen. Als er belangrijke informatie van andere projecten in docker aanwezig zijn zullen we voor een andere oplossing moeten gaan. 

Stap 1. docker-compose down --volumes
Stap 2. Verwijder de .env file in nl-kat-coordination
Stap 3. docker system prune -a --volumes
Stap 4. make pull
Stap 5. make kat                   

Als het goed is is alles dan opgelost. Ik ben benieuwd naar het boefje.

**Comment by trideeindhoven** [comment]
Iwan: ik heb de "prune" methode geprobeerd (die werkt!). kun jij de betere methode (wijzigen van .env) proberen, dan weten we zeker of beide fixes werken.
