### ISSUE TITLE
Design system update: Destructive button - size small

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3008]
In the design system there is one button option missing at the moment. There is no small size destructive button, so we can add this.

**Comment by NoemiOverdijk** [comment]
I added small destructive buttons and also took the time to make more options for the destructive button that I found were missing.

![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/de75db23-1305-42d8-bc37-05d50faa0c55)
![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/c6a1c9ef-b4e1-48a1-8cf9-1f2b565abd28)
![Image](https://github.com/minvws/nl-kat-coordination/assets/118826623/af42f409-5098-42cc-aee8-b40d23818123)

**Comment by NoemiOverdijk** [comment]
You can find the complete button component set including documentation in the Design System:
https://www.figma.com/design/MDbpc9K0qjyaoRGAGiDX6t/%F0%9F%8E%A8-KAT-%7C-Design-System-%7C-Components?node-id=233-94&t=dDJvCWKSEZvhSR2z-1
