### ISSUE TITLE
Design: add 'clear all' possibility to multiselect filter dropdown component

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3040]
### This design is approved and ready to be implemented

You can find the approved design in the Figma file: [KAT | Approved | Components
](https://www.figma.com/design/ENe9lxMBTOA3Nd745U7OKP/%E2%9C%85-KAT-%7C-Approved-%7C-Components?node-id=2332-2355&t=NK10jP6nMNOpGh1w-1)

More details about the dropdown component can be found in the [KAT | Design System | Components](https://www.figma.com/design/MDbpc9K0qjyaoRGAGiDX6t/%F0%9F%8E%A8-KAT-%7C-Design-System-%7C-Components?m=auto&t=F7VlB14TsGZGkmkZ-1)

![Image](https://github.com/user-attachments/assets/32cfa8b6-ce2b-4900-b359-997aa1326433)

-------------------------------
### Formerly: Design: add 'clear all' possibility to multiselect filter dropdown component
As discussed, this is the ticket to design a 'clear all' possibility to multiselect filter dropdown component.

See image and Figma file as reference where to use it.

![Image](https://github.com/minvws/nl-kat-coordination/assets/148460647/4cccdfc8-4971-47c1-8d02-9b93ede66940)

https://www.figma.com/design/EmUOOLqoFVB50syfDjSX9u/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Filters-%26-Query?node-id=2394-106687&t=4FjQs14ZToaScORV-1

**Comment by NoemiOverdijk** [comment]
This ticket is ready for review:
https://www.figma.com/design/vblfDVl9C5sg16xtHkwXDR/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Components?node-id=2364-17639&t=76H2hpNQ3QWVvu9Y-1

**Comment by HeleenSG** [comment]
Implementation of styling can be found here: https://github.com/minvws/nl-kat-coordination/pull/3446 And can be reviewed. 

We can add the necessary in a separate pr.

**Comment by HeleenSG** [comment]
Todo: (Feedback from @RomijnHumanoids)

- [ ]  Hover state border 1px instead of 2px.
- [ ]  Grey border instead of colored borders
- [ ]  Check if border color is correct

Edit: As it's already merged I will add these fixes in a separate pr.

**Comment by HeleenSG** [comment]
Last issues fixed in: https://github.com/minvws/nl-kat-coordination/pull/3565
