### ISSUE TITLE
6. Test all exposed web interfaces and machines for vulnerabilities, such as SQLi and XSS

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3070]
### Detailed description
_Add detailed description of the new feature you'd like to propose. If this feature is related to a problem, what problem does it solve?_

### Scope
* _Item1_
* _Item2_

### Out of scope 
* _Item1_
* _Item2_

## Related tickets
- [ ] ...

**Comment by underdarknl** [comment]
Not part of MVP, can be added after Deadline. 
Z-cert will provide plugings, or suggestion for tools.

**Comment by zcrt** [comment]
Move out of MVP board, reopen
