### ISSUE TITLE
21. Support audit trail level logging, preferable with configurable logging levels

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3075]
### Milestone items
 * 4 Logging
 * 9 Algemeen: logging, metrics, dingen die omvallen
 * 26 Een inzichtelijke log van acties die uitgevoerd zijn in de applicatie

### Detailed description

Details are written down in ticket #3038.

## Related tickets
- #3038
- #3043
- #3044
- #3114
- #3178
- #3216

**Comment by underdarknl** [comment]
@zcrt can you validate the currently merged structured logging  output and Audit events?
