### ISSUE TITLE
22. Provide a record of communication history via logging and/or audit trail

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3076]
### Detailed description
Details are written down in ticket https://github.com/minvws/nl-kat-coordination/issues/3038.

### Scope
* _Item1_
* _Item2_

### Out of scope 
* _Item1_
* _Item2_

## Related tickets
- [ ] #3038  
- [ ] #3043 
- [ ] #3044

**Comment by underdarknl** [comment]
Outside MVP as discussed. This is mainly the communication between Z-cert and its mail-provider.
