### ISSUE TITLE
Create JSON for making reports

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#3088]
_This ticket is part of epic #2626_

### Detailed description
This is step 1 in creating scheduled reports. While generating a report, we need to create a JSON.
With every step in the report flow, this JSON needs to be expanded (with a post-request). 
At the end of the flow, the report will be generated based on this JSON. 

This JSON will help us to go back and forth through the generate-report pages.
This will also make it possible to implement other features, like scheduling reports and creating "recipes".

This ticket is pre-work that has to be done before we can implement the scheduled reports.

### Possible solution

The JSON as here described will be "all things needed to make a report". 
This consists of a JSON object that will be passed from view to view with user selections.

What is needed for this JSON?
**- OOIs:** Remember which objects are selected. We don't want to make multiple octopoes requests each time we need the show attributes. 
**- OOIs filters.** We want to remember the filters used for filtering OOIs
- observed_at: When are these OOIs observed when creating the report.
**- Report types:** Which report types are selected?
**- Plugins:** We want to remember the state of the plugins during report creation.

With this information we can generate data for the report types selected: the data together with the JSON we will save in bytes.
The data consists of:
- Calculations to find/fetch vulnerabilities.
- Aggregation of data for aggregate report (the sum of parts) (de-duplication)
- Subreports 

This is an example of how the JSON should look like. If also configs are needed, this can be added to the JSON.
```
report = {
   "observed_at" : "2014-06-13 23:59:59 00:00",
   "ooi_filters": 
      {
           "ooi_types": ["Hostname","URL"]
           "clearance_levels": [2, 3, 4],
           "clearance_types": "["declared", "inherited"]
      },
   "oois" : 
       {
           "pk": "Hostname|internet|mispo.es",
           "clearance_level": 2,
           "clearance_type": "declared"
        },
        {
           "pk": "Hostname|internet|mispo.es",
           "clearance_level": 2,
           "clearance_type": "declared"
        },
    "report_types": ["aggregate_report", dns_report", "findings_report"],
    "plugins": {
        "plugin_id": "dns-records",
        "name": "DnsRecords",
        "description": "Fetch the DNS record(s) of a hostname",
        "type": "boefje",
        "options": "required",
        "scan_level": 2,
      },
       "plugin_id": "dns-records",
        "name": "DnsRecords",
        "description": "Fetch the DNS record(s) of a hostname",
        "type": "boefje",
        "options": "required",
        "scan_level": 2,
        
}
```
### Where do we save report recipes? 
There are some options:
- [x] Create a new Report Recipe OOI and/or add a new OOi Type
- [ ] Report OOI. Save the recipe in a variable so it can be used to generate another report in time. When the OOI is rescheduled we can use the recipe info send to Scheduler to unpack it there. If a report task means, do a rerun for each ooi in the recipe. I am doubting about the plugin information needs to be stored in the recipe. 
<img width="683" alt="image" src="https://github.com/user-attachments/assets/53b8bca0-8609-4dd3-a1ad-ea99937a18d8">

- [ ] Scheduler. We can also feed the Scheduler the Report OOI with the recipe in it and then extract the data in Scheduler.

- [ ] Report Data. Report Data is stored in bytes. 
<img width="698" alt="image" src="https://github.com/user-attachments/assets/603b54e0-37c9-4520-aa90-ef485c6945ce">

use also in:
<img width="573" alt="image" src="https://github.com/user-attachments/assets/ae9b3b9a-6820-40e3-9231-7b578bbdebab">

To unpack the data for the view.

**Comment by madelondohmen** [comment]
Looking good. In the future, config and export settings should also be part of this recipe, right? Maybe we could already add this. Things like the report name, the scheduler settings and saving subreports (or not) could then be set there.

**Comment by Rieven** [comment]
We concluded during the discussion meet of 27th of August 2024:

- The report recipe will be a new OOI 
- Each Report OOI has a reference to a report recipe OOI
- What are we going to do with the scan level of the OOI? 
- We save user and organization from which the report is created
