### ISSUE TITLE
[bug-rocky] error 403 forbidden (CSRF error) using containers

### ISSUE THREAD

**Issue by AnonymousWP** [minvws/nl-kat-coordination#309]
**Describe the bug**

After following https://docs.openkat.nl/technical_design/containers.html#setup, OpenKAT is reachable by using HTTP (for example, `<IP-address>:8000`, but as soon as I submit POST requests (such as logging in), I get the following error:

![image](https://user-images.githubusercontent.com/50231698/221157318-958ada91-e55a-49d3-9681-c80954a00d0f.png)

As mentioned, you have to edit the trusted origins, but nowhere in the documentation (as per above) it's mentioned how you should edit it. Steps are lacking. Via localhost it works fine.

**To Reproduce**
1. Go to your web interface (Rocky)
2. Click on 'login'
3. Login with your credentials
4. Notice the error how it complains about CSRF and how it does not match any trusted origins

**Expected behavior**

The documentation should mention any further steps required (e.g. modifying a config file) and explain how to solve this issue. 

**Screenshots**

See above.

**OpenKAT version**

1.4.0 (installation date: 24-02-2023), used https://docs.openkat.nl/technical_design/containers.html#setup.

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10 and PopOS 22.04
 - Browser: Chrome 110 and Firefox 110

**Comment by AnonymousWP** [comment]
> OpenKAT version
> 1.4.0 (installation date: 24-02-2023), used https://docs.openkat.nl/technical_design/containers.html#setup

Also, the version is probably incorrect, as for some reason [you hardcode 1.4.0 in the env file](https://github.com/minvws/nl-kat-coordination/blob/main/.env-dist#L7), which means you don't run the latest image. When I changed this to 1.5.2, it pulled the images for 1.5.2.

**Comment by underdarknl** [comment]
I'm guessing you are connecting to the container over an IP-address which is not in fact localhost / 127.0.0.1.
Rocky (or frontend) sets a secure flag on the session cookies (as we want to be sure by default), even though we are serving over http. 
Your browser sees this 'secure' cookie, and notices its being served to a non-secure endpoint after you submit the login form, and discards it.
For localhost / 127.0.0.1 a special case exists where this cookies is allowed to be send.
An option would be to setup a proxy in front of the container which handles the https offloading.
Another option is to change the rocky/rocky.conf django config file and set both cookies secure flags to false.

**Comment by AnonymousWP** [comment]
But we followed the production manual, so then I'd expect it to not only available from localhost. After all, how would people be able to access it from outside if it's only pointing to localhost? Also, why is this not documented? As far as I can see, nothing of a proxy is mentioned in the steps for deploying a container (https://docs.openkat.nl/technical_design/containers.html#setup).

We tried using Nginx as a proxy in front of the container, but no luck. We got it now working with SSH-tunneling, but none of this is mentioned when you follow the steps of the documentation either.

**Comment by underdarknl** [comment]
We have updated the docs to include this information:
* https://docs.openkat.nl/technical_design/debianinstall.html#configure-hostname-in-rocky
* https://docs.openkat.nl/technical_design/nginx.html
I hope with these details you can get the 'production' environment ready to go.
