### ISSUE TITLE
Fix report overview table in manual

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3105]
**Describe the bug**
The report overview table in de manual is missing IPAddresses as input objects. 

**To Reproduce**
Go here: https://docs.openkat.nl/manual/reports.html#reports

**Expected behavior**
Should be like this: 
https://github.com/minvws/nl-kat-coordination/issues/2806#issuecomment-2122360975

**Screenshots**
![Image](https://github.com/minvws/nl-kat-coordination/assets/99282220/ced04c6d-0f41-40bd-ad7e-20311316cbe9)

**Comment by underdarknl** [comment]
The RPKI report would also be logical to request for an IP address or IpRange I'd say. Possibly in the future also for a AS as those own ranges.
