### ISSUE TITLE
Add bytes API endpoint to upload mutiple raw files

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#3113]
### Detailed description

Add bytes API endpoint that can be used to upload multiple raw files in a single API call.

### Feature benefit/User story

When generating reports we create a lot of raw files for each subreport.  We currently need to do an API call for each raw file which is slow. Having an endpoint to upload all the raw files in one go will speed this up.

### Specifications

The API needs to accept multiple files using multipart upload. It should return all the raw file ids of the raw files that are created.

---

## To Be Discussed

Ideally we can use the [`multipart/form-data`](https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean) mime type for this:

![Image](https://github.com/user-attachments/assets/69e8c5e7-9dc5-4238-a11d-371f22801f2d)

The limitation here is that each file part has at most one content-type header, while our files can have multiple mime-types.

**Comment by underdarknl** [comment]
This functionality can then also be used in the Boefjes-runner, as some boefjes also return multiple raw-files, or at least they can. 
https://github.com/minvws/nl-kat-coordination/blob/2195d81006dc912a989151ef7e407466d03e3f97/boefjes/boefjes/job_handler.py#L167
