### ISSUE TITLE
40. Support for interfacing via API with the client's asset database (DADB) and optionally with tenants' asset databases (by Z-CERT)

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3130]
### Detailed description
_Add detailed description of the new feature you'd like to propose. If this feature is related to a problem, what problem does it solve?_

### Scope
* _Item1_
* _Item2_

### Out of scope 
* _Item1_
* _Item2_

## Related tickets
- [ ] ...

**Comment by underdarknl** [comment]
@zcrt the DADB boefje is now working as expected, yes?
