### ISSUE TITLE
46. Introduce an automated way of responding to high visibility, key 0 day issues (by Z-CERT)

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3131]
### Detailed description
_Add detailed description of the new feature you'd like to propose. If this feature is related to a problem, what problem does it solve?_

_**Notes from discussion**_: this could relate to being able to quickly add custom (containerized) boefjes and normalizers.

### Scope
* _Item1_
* _Item2_

### Out of scope 
* _Item1_
* _Item2_

## Related tickets
- [ ] ...

**Comment by underdarknl** [comment]
The normalizer part for this is covered by #3383 
combined with the ability to create / add new boefjes based on containers handled in #3318 this allows Anyone to quickly create new CVE discovering boefjes.

**Comment by underdarknl** [comment]
related: https://github.com/minvws/nl-kat-coordination/pull/3400
