### ISSUE TITLE
Saving reports - Onboarding flow 

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3133]
While going through the onboarding flow the following items are not present in the DNS report. The output from the DNS report can be seen below in the screenshot. 
	- Selected objects section is empty 
	- Selected report types is empty
	- Selected plugins is empty
	- DNS report doesn't get shown

![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/af15a434-a005-47c5-a14f-3d6752dd374b)

**Comment by ammar92** [comment]
There's no PR/ implementation linked to this issue yet, right?
