### ISSUE TITLE
Saving reports - Download normal report not working

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3140]
**Describe the bug**
In the normal report ("generate report") the "Download report" isn't working correctly.
It opens a new tab with the same URL.

**To Reproduce**

1. Generate a normal report
2. Click on 'Export'
3. Select 'Download report'
4. New tab opens with same URL

**Expected behavior**
I would expect to download a PDF.

**Comment by dekkers** [comment]
I fixed this in the saving reports branch in e45b3dd9389d7aa9334b0d7e883a25a5aed30645
