### ISSUE TITLE
Add Pattern to Nmap boefje to match a range of numbers, eg 0 to 65000 are not overly easy to do, but here's a try:

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#3143]
> To revisit this. Patterns that match a range of numbers, eg 0 to 65000 are not overly easy to do, but here's a try:
> 
> `(([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-4]),)*?(([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-4])-)?([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])`
>
> This will match the following:
> 
> - 1
> - 1,2
> - 1-65000
> - 1,2,100-200
> - 65534-65535
> 
> Rules:
> 
> - The number of single ports is unlimited, the number of range groups is unlimited, but expected to come after the single ports.
> - Range groups are intended to be separated by a dash
> - No spaces / other chars are allowed.
> - Port numbers (single or in range) are limited from 1 to 65535
> - A small number is allowed as the second argument in a range, this is not easily fixed in the regex, but we might be able to flip them round in the boefje code.

_Originally posted by @underdarknl in https://github.com/minvws/nl-kat-coordination/issues/2999#issuecomment-2177941702_

**Comment by Donnype** [comment]
A different, perhaps more modular approach, including passing unit tests:
```python3

max_65535 = "(6553[0-5]|655[0-2]\d|65[0-4]\d{2}|6[0-4]\d{3}|[1-5]\d{0,4}|\d)"  # matches 1 to 65535
max_65535_or_range = f"({max_65535}|{max_65535}-{max_65535})"  # matches 1 to 65535 or a range of two
pattern = re.compile(f"{max_65535_or_range}|{max_65535_or_range}(,{max_65535_or_range})+")  # comma separated list of the latter

def test_single_port_pattern():
    for single_port in ["1", "2", "20", "200", "2000", "20000", "65535"]:
        assert pattern.fullmatch(single_port) is not None


def test_bad_single_port_pattern():
    for bad_single_port in ["-1", "-2000", "65536", "222222"]:
        assert pattern.fullmatch(bad_single_port) is None


def test_multi_ports_pattern():
    for multi_port in ["1,2", "2,3,4", "2,3,4,5,6,7", "2,20,200,2000,65535"]:
        assert pattern.fullmatch(multi_port) is not None


def test_port_range_pattern():
    for port_range in ["1-2", "2-20000", "65533-65535"]:
        assert pattern.fullmatch(port_range) is not None


def test_combined():
    for port_range in ["1,1-65000", "1,2,234,4300-5999,1"]:
        assert pattern.fullmatch(port_range) is not None


def test_badly_combined():
    for port_range in ["1,1-", "1-234-323"]:
        assert pattern.fullmatch(port_range) is None

```
