### ISSUE TITLE
Indemnification not set warning appears randomly with no indication of which organization

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#316]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/30832687/221599925-0d8b80d1-d15a-42b1-8784-5616a279c932.png">

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/30832687/221620249-aa5f8165-0468-408b-ae89-a7861d83ed0d.png">

**OpenKAT version**
Note the release tag (and if possible: the installation method) here.
If it concerns an in-development version, note the branch(es) and commit hash(es) here as well.

**Desktop (please complete the following information if relevant):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information if relevant):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by TwistMeister** [comment]
What steps do I have to take to reproduce?

**Comment by Rieven** [comment]
> What steps do I have to take to reproduce?

Unknown to me as well, soemtimes it randomly pops up

**Comment by TwistMeister** [comment]
When looking at the code that throws this error, it doesn't really explain why this is happening. On `setup` of the `OrganizationDetailView` the indemnification gets checked by using the `OrganizationView` mixin attribute called `indemnification_present`. When that's false it adds a messages of type error... Maybe @ammar92 or @dekkers can help figure this out?

**Comment by praseodym** [comment]
As discussed, the proposed solution is to render the unset indemnification warning in the template instead of through a message.
