### ISSUE TITLE
Feature toggle to enable or disable JSON format logging

### ISSUE THREAD

**Issue by ammar92** [minvws/nl-kat-coordination#3177]
### Detailed description

In order to specify what kind of logging format we would like to see, we need a setting. During development, you'd like to see a human readable (and colored) output, whereas in production or other environments, you might want to format the output to JSON, to enable easier log aggregation.

This feature would be a continuation of #3114 

### Specifications

The implementation should include:

- [ ] An environment key `JSON_LOGGING` per module to enable JSON (dict) logging (see Mula)

### Additional information

The processors used by `structlog` should be reconsidered. For example, use color and key-value rendering for non JSON logging, and disable colors for the JSON output. This could otherwise result in color symbols in the JSON strings.

## Implementation

- Introduce `JSON_LOGGING` environment key (boolean, default `False`)
- Adapt processors in `structlog.configure` calls

### Alternatives considered

An alternative would be to always output JSON format logging and use a log aggregator and monitor (even during development). However, this approach adds complexity, since you'd be dependent on such tools, and it otherwise it might be harder to read the logs during development without these tools.

**Comment by underdarknl** [comment]
As suggested in the discussion, lets go for a env-var that toggles between off (for not existent / empty), or 'json' when the value is 'json'. That way we could introduce 'xml' or 'txt' output by using the same env-var.
