### ISSUE TITLE
SYNK boefje returns *all* CVE's for software without Version Number

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#3187]
**Describe the bug**
Currently, when a software package is found, but is found without a software version number, snyk returns all CVE's for this software. 

This is over cautious and produces a lot of noise and false positives.

https://github.com/minvws/nl-kat-coordination/blob/b9bbc3b070790fac41bdf266f44cdf9000728dee/boefjes/boefjes/plugins/kat_snyk/normalize.py#L18C5-L18C21

**To Reproduce**

1. Add a softwaerIntance for a package as noted on snyk.io, dont give a version number
2. Run the snyk boefje
3. Notice all CVE's created

**Expected behavior**
Instead of adding all CVE's we should problably look at the most recent version f the software available, and if that still have CVE's list those.
Since we don't have a source for 'newest version' we should probably just stick to an informational warning stating we cannot judge that software, but we know some version of that package are known to be vulnerable.

**OpenKAT version**
Main

**Additional context**
Noted by KennisNet.

**Comment by paulvandenbraken** [comment]
We do not encounter this issue since 1.17 anymore and have closed this issue in our internal JIRA.
