### ISSUE TITLE
Migration to Wappalyzer as normalizer doesn't clean old data.

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3204]
**Describe the bug**
Old findings are not cleaned with the move from the Wappalyzer boefje to the Webpage Analysis normalizer. This means that an old finding from January 1st 2024 would still show up as a Finding even though it hasn't been validated since March 23rd 2024 (dates are fictive). There is currently no garbage collection for invalidated findings, nor is there a warning on the page of the finding itself to make this clear. The latter is partly picked up in #3186 by changing the observation date as shown on the objects detail page.  This bug was mentioned by Kennisnet. 

This issue will also occur when disabling boefjes and for future migrations of boefjes, that may be removed. 

**To Reproduce**

1.Scan some hosts with the old Wappalyzer boefje.
2. Wait a day to make sure that there is also data for another day.
3. Upgrade to the Wappalyzer normalizer version.
4. Scan some hosts with the wappalyzer normalizer. 
5. Observe that old findings on the object detail page are now not attached to a boefje/normalizer. 

**Expected behavior**
With the migration old findings should be cleaned up, also when boefjes are disabled and/or when boefjes are removed from the repository. 

**Screenshots**
Coming soon. 

**OpenKAT version**
main

**Possible solution(s)**
- A 'zero' boefje, in case boefjes are removed, disabled, or otherwise available.

**Comment by underdarknl** [comment]
Another option could be to ask the user what they want to do when disabling a boefje, or when a boefje is removed.
The same goes for disabling/removing normalizers, and also for Bits (when we get there).

Removing all OOI's that have the affected plugin in their origin cleans up the pollution of the database, but might remove data that you can no longer re-create. thats a choice only the user can make.

**Comment by originalsouth** [comment]
Problem seems to be that normalizer-id was changed when the wappalyzer code was changed/updated. Quickest way to address is to change the origin method accordingly. Will proceed making a migration script.

**Comment by originalsouth** [comment]
As #3234 will be merged, the backend part of this bug shall be implemented shortly. Handing over to documentation/frontend.

**Comment by underdarknl** [comment]
We need to provide a migration script that allows the user to remove the defunct objects.
