### ISSUE TITLE
No-certificate finding when a valid certificate is present

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3205]
**Describe the bug**
In certain cases a "No certificate" finding is shown for hosts, when there is actually a valid certificate for the host. This is likely due to parsing of the data with SNI proxies and/or redirects of hosts. This bug was mentioned by Kennisnet. 

Edit: It looks like this issue is somehow related to the backend. As the boefje runs and the normalizer run and x509 objects are created with the expected data in it. 

I did find this in the logs, but that is a different issue and should not be the cause of the 'No-certificate' finding. 

```
normalizer-1  | [2024-08-13 13:22:19 +0000] [1] [INFO] [_client] HTTP Request: GET http://scheduler:8000/queues "HTTP/1.1 200 OK"
normalizer-1  | [2024-08-13 13:22:19 +0000] [1] [INFO] [_client] HTTP Request: POST http://scheduler:8000/queues/normalizer-aa/pop "HTTP/1.1 200 OK"
normalizer-1  | [2024-08-13 13:22:19 +0000] [16] [INFO] [job_handler] {"event": "Obtained results observations=[] declarations=[] affirmations=[] scan_profiles=[]", "level": "info", "timestamp": "2024-08-13T13:
22:19.670966"}
normalizer-1  | /app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py:120: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_before_utc.
normalizer-1  |   valid_from = cert.not_valid_before.isoformat()
normalizer-1  | /app/boefjes/boefjes/plugins/kat_ssl_certificates/normalize.py:121: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
normalizer-1  |   valid_until = cert.not_valid_after.isoformat()
normalizer-1  | [2024-08-13 13:22:19 +0000] [15] [INFO] [normalize] Parsing certificate of type <class 'cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey'>
normalizer-1  | [2024-08-13 13:22:19 +0000] [15] [INFO] [normalize] Parsing certificate of type <class 'cryptography.hazmat.bindings._rust.openssl.rsa.RSAPublicKey'>
normalizer-1  | [2024-08-13 13:22:19 +0000] [16] [INFO] [_client] HTTP Request: POST http://bytes:8000/bytes/normalizer_meta "HTTP/1.1 201 Created"
normalizer-1  | [2024-08-13 13:22:19 +0000] [15] [INFO] [job_handler] {"event": "Obtained results observations=[NormalizerObservation(type='observation', input_ooi='Website|internet|145.97.33.18|tcp|443|https|internet|meta
```

**To Reproduce**

1. Perform a TLS check against a host with a proxy, SSO portal, redirect. 
2. Manually verify that there is a valid TLS certificate.
3. Verify that there is a No-certificate finding for this host. 

Note: pm me for the hostname on which this occurs. 

**Expected behavior**
When a (valid) certificate is present there should not be a finding saying 'No-certificate'. 

**Screenshots**
n/a

**OpenKAT version**
main

**Comment by underdarknl** [comment]
We think this is going wrong in the Bits somewhere. @originalsouth could you take a look at this?

**Comment by underdarknl** [comment]
also @stephanie0x00 has confirmed the issue.
