### ISSUE TITLE
On the crisis room and organizations list: allow users to filter organizations by selecting one or more Tags.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#321]
Currently, the crisis room shows all organizations that the user can see, It would be helpful to allow the user to filter this list by selecting from the Tags present in his organization set.
Resetting the tag selection should also be allowed. (this could just be a link back to the crisis room, instead of a form action)

**Comment by underdarknl** [comment]
@Rieven is this something you can start working on?

**Comment by TwistMeister** [comment]
I unassigned @Rieven from this particular ticket, so we can use this as the design ticket and when the design is ready @Rieven can start working on implementation in a separate ticket.

**Comment by TwistMeister** [comment]
To be clear: We would like to filter the lists on the crisis room using tags, but currently the "entire list of organisations a user has access to" is a separate page where we would also like to be able to filter on tags. But this list isn't in fact part of the crisis room itself. Just related in terms of tags-filter.

**Comment by NoemiOverdijk** [comment]
This design has been reviewed, the final design can be found here:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=329%3A13299&t=wnYRVitpF1aF7yZx-1](url)

If you still wish to leave comments on the design, you can do so here:
[https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=527%3A60960&t=KdIzHtXxD9DPzN6n-1](url)
