### ISSUE TITLE
[Katalogus] Create an API to export all Mime-types currently handles by enabled normalizers.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#322]
An API is needed on the Katalogus which exposes the list of current mime-types consumed by the enabled normalizers for a given organization.
This depends on the fact that we can in fact enable/disable normalizers.

**Comment by underdarknl** [comment]
depends on: https://github.com/minvws/nl-kat-coordination/issues/323

**Comment by underdarknl** [comment]
This data is already present on the current plugins endpoint. Maybe we can offer a helper method on the Katalogus client.

**Comment by ammar92** [comment]
> This data is already present on the current plugins endpoint. Maybe we can offer a helper method on the Katalogus client.

This would imho be a better option. I'm currently writing a feature request for more filtering and pagination on the backend side which should make this option even easier to implement.

**Comment by Donnype** [comment]
Shall we close this or move to the backlog then?

**Comment by Donnype** [comment]
Moving to backlog for now

**Comment by Donnype** [comment]
Closing this one
