### ISSUE TITLE
Human readable time on Object table page

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3221]
**Describe the feature**
PR #3186 introduces the 'When' column in the Last observed by table to show when an object was last identified. The current timestamp is not human readable, but is already an improvement. A better human readable time stamp would be nicer to the user.  For example `2024-10-31 13:37:37` or another time format. I suppose it would also be nice if the user can choose his/her preference for the timestamp formatting. 

**To Reproduce**

1. Make sure you have some data in the interface. 
2. Click on Objects > Open any object.
3. Scroll down to the 'Last observed by' section and view the timestamp

**Expected behavior**
A human readable timestamp for the user. 

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/9821756/204edfa3-699b-43b3-b4b7-c99f79aa55b3)

**OpenKAT version**
main

**Comment by ammar92** [comment]
This is not a bug (since it’s clearly human-readable) but a feature request (for a better format). If the timestamp were missing or incorrect, then it would be a bug.

**Comment by underdarknl** [comment]
Ideally I'd also add a warning-state to this table row if the last run was too old. Eg, "warning: this specific Boefje has produces this proof 2 weeks ago, this might be stale data. check the Boefje's task list for errors."
