### ISSUE TITLE
DNS boefje crashed on SERVFAIL when using correctly functioning dnssec

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#3269]
**Describe the bug**
The DNS boefje crashed on DNS-responses from zones that correctly implement DNSSEC and include 
This happens due to python's dns resolver exhausting its list of recursors due tot each of them returning a 
The crash happens for example when requesting the data for _domainkey.dnssec-failed.org which as designed returns a SERVFAIL.

**To Reproduce**

1. add dnssec-failed.org
2. Run dns boefje
3. See error as listed below:

```
boefje-1  |   File "/usr/local/lib/python3.11/site-packages/dns/resolver.py", line 763, in next_nameserver
boefje-1  |     raise NoNameservers(request=self.request, errors=self.errors)
boefje-1  | dns.resolver.NoNameservers: All nameservers failed to answer the query _domainkey.dnssec-failed.org. IN TXT: Server Do53:1.1.1.1@53 answered SERVFAIL
boefje-1  | 
boefje-1  | The above exception was the direct cause of the following exception:
```

**Expected behavior**
Not crash on correctly answering severs when we ask for non exitant records.

**OpenKAT version**
Main, including 1.16 / 1.17

**Additional context**
Reported by Arjen from our community.

**Comment by halma1** [comment]
Getest, en scan loopt nu door.
