### ISSUE TITLE
Discover and define user needs for the dashboard.

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#3273]
`design` 

### Detailed description
We should discover what the specific user needs are in regards to the dashboard, and define the requirements accordingly.

### Feature benefit/User story

As a _user_, I want to _have a clear overview of the status of the organisation(s) that I'm responsible for_ so that _I know what I have to act on_.

### Additional information
We also need to design a way for users to handle question OOIs in a more user friendly way. The dashboard could very well be the right place for this.

**Comment by HeleenSG** [comment]
I have discussed the miro board with @underdarknl. Conclusions were: 

- We can start with the step making customisation possible for users by adding parts of reports to the dashboard. Designs are needed as to how and when users will be able to do so.There are some design challenges here like: 
   - how do users find the different options (as they are in separate reports)
   - how do we guide users when they haven't selected any custom elements to add to the dashboard just yet
   - If we add a couple of default reports and sections to the Dashboard from those reports. How do we communicate clearly those are related to the reports. (And will stop working when those reports are deleted). 
   - If a user deletes one of the default elements. How do we make sure they have the ability to add it back and find it again.
