### ISSUE TITLE
Quick styling fixes for the current filters

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#3274]
This design has been approved and is ready to be implemented. 
You can find more details about the design in the [Approved | Patterns](https://www.figma.com/design/DELH5exdYs61olBbZFpk34/%E2%9C%85-KAT-%7C-Approved-%7C-Patterns?node-id=2302-2291&t=qw018QamOKL7bFiP-1) file.

![Image](https://github.com/user-attachments/assets/20d799f5-69ce-4b65-bb72-4e1a7f99b954)

---------

Since the new filter design is out of scope for the MVP, we want to make the current filtering a bit more user friendly with some (hopefully) quick styling fixes. 

### Current styling

![Image](https://github.com/user-attachments/assets/0e2109a5-5030-42d7-9a20-990c8ba8a745)
![Image](https://github.com/user-attachments/assets/20bb6cb4-bb89-4b3d-9f97-a3c2ed4d0d21)

**Comment by NoemiOverdijk** [comment]
This design is ready to be reviewed. You can find the design in the [For Review | Patterns](https://www.figma.com/design/EmUOOLqoFVB50syfDjSX9u/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Patterns?node-id=2603-4774&t=b0DHQSaSnrlhxNdW-1) file.

**Comment by HeleenSG** [comment]
@NoemiOverdijk I've updated the PR based on your feedback. Which adds:
- Border bottom when the filters are opened
- Moves the chevron to the left

@Rieven I've updated the pr description with the todo's. Which mainly include adding the counter to other filters.

**Comment by NoemiOverdijk** [comment]
@HeleenSG Looks good to me!
