### ISSUE TITLE
Scan profile declaration from External Database not working

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#3310]
**Describe the bug**
https://github.com/minvws/nl-kat-coordination/blob/eefc519c9b40e7b5ce826d91e24242a8c8c5e608/boefjes/boefjes/plugins/kat_external_db/normalize.py#L53 and https://github.com/minvws/nl-kat-coordination/blob/eefc519c9b40e7b5ce826d91e24242a8c8c5e608/boefjes/boefjes/plugins/kat_external_db/normalize.py#L71 do not seem to be working

**To Reproduce**

1. Connect an external DB
2. Notice clearance level stays 0.

**Expected behavior**
Using the hardcoded clearance `level=3`.

**Screenshots**
![image](https://github.com/user-attachments/assets/00296257-c23c-4f81-a6fe-49abcc9ad5ce)

**OpenKAT version**
main (31 july 2024)

**Comment by originalsouth** [comment]
Can replicate bug with https://gist.github.com/originalsouth/b922ecef262ef4dac6802c0410f2a058

**Comment by originalsouth** [comment]
Desired result can be achieved by adding: `BOEFJES_SCAN_PROFILE_WHITELIST='{"kat_external_db_normalize": 3}'` to the `.env` file.

**Comment by zcrt** [comment]
Would this solution still work with https://github.com/minvws/nl-kat-coordination/pull/3311? Because this looks like a hardcoded solution for a specific declaration.

**Comment by originalsouth** [comment]
> Would this solution still work with #3311? Because this looks like a hardcoded solution for a specific declaration.

@dekkers
