### ISSUE TITLE
As a KAT user, I want to be able to create and add my own boefjes

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#3318]
### Design a flow to create and add boefjes

We should also create the flow to create boefjes. This design can be largely the same as the flow for duplicating boefjes, except:
- The entry point for the flow should be the KAT-alogus.
- Users should be able to add a container image.
- The form fields should probably not be prefilled.

If you want to work on this design, you can find it in the[ Workfile | Boefjes](https://www.figma.com/design/wXSEivzTwUHJkMEPlfG1Ug/%F0%9F%90%88-KAT-%7C-Workfile-%7C-Boefjes?node-id=514-63919&t=gtU6TkFN0qJqOtVa-1)

-----------

Relates to:
https://github.com/minvws/nl-kat-coordination/issues/2828

### To be discussed

With respect to permissions, because the decision was to have a flow where admins approve a copied/created boefje, we suggest for a first version to only allow admin users to create (and copy) boefjes.

### Conclusion

Agreed (@underdarknl @dekkers), although we probably need the admin flow soon after, so design can work on that already.

**Comment by NoemiOverdijk** [comment]
A first version of this flow is ready to be reviewed. You can find it in the [For Review | Boefjes](https://www.figma.com/design/wTD4hfTbZMp0o2G6VmUepU/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Boefjes?node-id=2472-25863&t=CApMFcgwxwOXg6sw-1) file.

**Comment by NoemiOverdijk** [comment]
This ticket is blocked because the flow requires a way to upload a cat picture and a readme file. 
That will be possible with this issue:

- #3309

**Comment by NoemiOverdijk** [comment]
This design has been approved for implementation.
You can find the design in the[ Approved | Boefjes file](https://www.figma.com/design/D48Pf9lLpxET1jp0Wsjzw5/%E2%9C%85-KAT-%7C-Approved-%7C-Boefjes?node-id=2301-6042&t=OkC1Ba5bbLcxjHzG-1).
