### ISSUE TITLE
Design: Can users delete reports?

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3330]
This question came up during design ticket #3026 about (bulk) actions on the reports page in the history tab.
- Do we want users to be able to delete reports? Deleting report doesn't mean to delete data in it, so you could generate it again at a later moment.
   - If yes, is this only possible from the folders tab (not designed yet) or also from the report history tab?
   - If yes, what to do with subreports as they're only toggled to view (not generated as separate reports), and they are still part of parent reports. I we want to prevent a toggled 'show sub reports' view that is a customised incomplete sub reports view.

This question is more broad than only design, so feel free to join the discussion on possibly deleting reports.

**Comment by underdarknl** [comment]
I would say yes, For those users who can also delete Regular OOI's. As reports are just stored as OOI's in the database.
Deleting Sub-reports would be a separate action, but it might make sense to ask the user if they want to. Bear in mind that a sub-report might be used in more than one grouping or aggregating report. But as you said, deleting a sub-report does not delete the report that relied on it, or the data that was needed to generate it in the first place. (unless the report was added from an outside source, and not generated in the current organisation)

**Comment by RomijnHumanoids** [comment]
Discussion outcome is in short: Yes. Depending on their rights in the KAT install users can either delete reports they made themselves, or delete reports across organisation.

Reports are saved as OOI with their timestamp in the graph. A new report (scheduled/rerun/reschedule) is a new version of this same OOI. Older versions are still saved in the graph, also when users delete a report. Deleting means putting an expired valid time on an object in the graph. The report is not in the overview on the report page UI but it is still possible to go back in the graph to the moment where the report was still valid.
For deleting sub reports this means that data can still be visualised in the parent report after deleting sub reports, and for proof behind report content it is still possible to go back in the graph to when the subreport was valid.

This outcome means that the flow for deleting reports will be designed in the bulk flow ticket #3026
