### ISSUE TITLE
Come up for the right term for reports-report (report that consumes imported reports)

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3335]
Previously known as a sector report. But this name does not always cover the meaning of this report. This is a report type that gives general overview of underlaying reports' totals and means. It only consumes other reports, not other object types.

It's possible that:
- A large organisation X (overlooking cybersecurity for many organisations) wants to report the status of this sector (sector report)
- A organisation Y (large hospital for example) has outsourced some of its hosting to another party that makes reports. Organisation Y wants a combined report of their own reports with the imported reports from the external party, because it's both their assets.
- Or organisation Z, not even outsourcing their assets, wants to generate a report with totals and mean of a few different DNS repots in their reports page, so they generate a 'reports-report'.

If you have thoughts/opinions on the name of this report that consumes reports, please be welcome to share.

**Comment by RomijnHumanoids** [comment]
Some suggestions: top-level report, overview report

**Comment by stephanie0x00** [comment]
Maybe report collections?

**Comment by Rieven** [comment]
**Meta-report**: A report that provides a higher-level overview or analysis of other reports.

**Comment by RomijnHumanoids** [comment]
Discussion outcome is: 
- Thinking point: Maybe this report doesn't need a separate name to have a separate flow starting point.

This could be the separate flow starting points:

![Image](https://github.com/user-attachments/assets/4f917059-0f6b-4953-b345-5b9e0004ea73)
