### ISSUE TITLE
Add the ability to use date placeholders in report names in the config flow

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#3339]

**Comment by underdarknl** [comment]
Basically:
import datetime
now = datetime.datetime.utcnow()
datetime.datetime.strftime(now, '%Y-%m-%d %H:%M:%S')

now wordt gevuld op het moment dat we de report maken (nu, of in de toekomst als deze scheduled is)
De string '%Y-%m-%d %H:%M:%S' is een voorbeeld, maar daar kun je dus de naam zoals door de gebruiker aangegeven in stoppen, inc placeholders.
