### ISSUE TITLE
Design: a pattern for submitting multiple form input textfield answers on the same subject

### ISSUE THREAD

**Issue by RomijnHumanoids** [minvws/nl-kat-coordination#3408]
As we are now implementing a multi select form input select similar to the new filter design, the need for a pattern to submit multiple text input answers to the same questions in a form came up. There is already a use case within settings in KAT (for a specific boefje if I remember correctly) where multiple text input answers are required or desired from users.

Look for existing patterns in a single input field with a button to add fields and from the second field on a way to remove added fields.

**Comment by NoemiOverdijk** [comment]
We do have a button specifically for adding things. You can find it in the [KAT | Design System | Components](https://www.figma.com/design/MDbpc9K0qjyaoRGAGiDX6t/%F0%9F%8E%A8-KAT-%7C-Design-System-%7C-Components?m=auto&node-id=233-94&t=yDUctKOWAnPj5DkV-1).



![Image](https://github.com/user-attachments/assets/afd32701-8c97-4843-ab8a-e601d63f0e33)

**Comment by HeleenSG** [comment]
Review file: 
https://www.figma.com/design/vblfDVl9C5sg16xtHkwXDR/%E2%9C%8D%F0%9F%8F%BC-KAT-%7C-For-Review-%7C-Components?node-id=2540-2&t=KXNKHN7PZk3aJSBl-1
