### ISSUE TITLE
Update explanation

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3424]
The explanation currently looks like this:

![Image](https://github.com/user-attachments/assets/0b28ce66-c8c7-40c5-872a-2415a81b9b66)

But shoud look like this:

![Image](https://github.com/user-attachments/assets/cd7f0138-65ee-4d59-b74b-5a9174c7606c)

**Comment by HeleenSG** [comment]
https://github.com/minvws/nl-kat-coordination/pull/3450 

Fixes the width issue. 

Other issues that need to be fixed are: 
- Icons are missing (information etc) 
- The option to close/remove the notification.

**Comment by stephanie0x00** [comment]
QA of https://github.com/minvws/nl-kat-coordination/pull/3450 looks good. This fixes the problem.
