### ISSUE TITLE
Add search on key on OOI list

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#345]
As a user I want to be able to type a search query in a text input to search for that (sub)string in all OOI's keys that are listed in the OOI overview table

**Comment by originalsouth** [comment]
> This is blocked by the implementation of Octopoes 3.0, since it now is impossible to search by wildcard/string

Am I missing something, why is this blocked? Can't we do a fuzzy find on the complete list retrieved from Octopoes inside Rocky?
