### ISSUE TITLE
Remove unnecessary repetition within katalogus

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#3474]
**Describe the issue**
We could remove the 'plugin type' column when we are looking at the boefjes or normalizers lists, as it will list the same type over and over.

**To Reproduce**

1. Go to KAT-alogus
2. Click on: Toggle view to see list view (instead of default card view)
3. See table: header "plugin type". When looking at either the boefjes or the normalizers view. This column will be filled with the same content for all. And can be removed. 

**Expected behavior**
Expect the table to have useful information for our users. Repeating the same information over and over while in a specific view isn't. Remove unnecessary information making it easier to see the useful information.

**Screenshots**
<img width="1276" alt="364079720-c9238c3e-5884-4dc9-8e19-7fb08b45eb73" src="https://github.com/user-attachments/assets/0cfea156-4e69-467d-a318-1136e62005be">

**Comment by stephanie0x00** [comment]
Works now! Including the 'All' page now shows the labels .
