### ISSUE TITLE
As an admin, I want to delete a Boefje

### ISSUE THREAD

**Issue by NoemiOverdijk** [minvws/nl-kat-coordination#3480]
As an admin/user, I want to be able to remove Boefjes from my organisation.
This flow can be based partially on the flow for approving/rejecting a Boefje.
You can find that design in the [Approved | Boefje](https://www.figma.com/design/D48Pf9lLpxET1jp0Wsjzw5/%E2%9C%85-KAT-%7C-Approved-%7C-Boefjes?node-id=2346-13945&t=luQdWPjakZpG5alR-1) file.

**Comment by RomijnHumanoids** [comment]
Closing this ticket because it's part of #3486
