### ISSUE TITLE
Object importing

### ISSUE THREAD

**Issue by paulvandenbraken** [minvws/nl-kat-coordination#3491]
## About this feature
Should have for Kennisnet phase: Epic-3

### Detailed description
(Besides exporting objects) Kennisnet requests importing objects in an identical way.

### Feature benefit / User story
As an administrator I want to be able to import objects so that I will be able to efficiently on-board organisations that provide me with their assets-list.

This is important because: When performing new organizations, it is very important that this is done correctly. If this has to be done manually, then that can also take on errors in addition to extra work.

**Comment by underdarknl** [comment]
```
OOI_TYPES: dict[str, dict] = {
    "Hostname": {"type": Hostname},
    "URL": {"type": URL},
    "Network": {"type": Network, "default": "internet", "argument": "name"},
    "IPAddressV4": {"type": IPAddressV4},
    "IPAddressV6": {"type": IPAddressV6},
}
```
