### ISSUE TITLE
Federative website is scanned, instead of Webapp-site

### ISSUE THREAD

**Issue by paulvandenbraken** [minvws/nl-kat-coordination#3497]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
Due to the re-direct, the federative website is scanned, instead of Webapp-site.

**To Reproduce**

**Expected behavior**

**Screenshots**

**OpenKAT version**
Note the release tag (and if possible: the installation method) here.
If it concerns an in-development version, note the branch(es) and commit hash(es) here as well.

**Desktop (please complete the following information if relevant):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Additional context**

**Comment by underdarknl** [comment]
We need some more info on this one. What boefje is following the redirect?
