### ISSUE TITLE
Duplicate OOI references in result in origin

### ISSUE THREAD

**Issue by originalsouth** [minvws/nl-kat-coordination#3508]
**Describe the bug**
Duplicate references in result in origin.

Example (generated by main b098d8d2ee2f7bdbb4c7d98e7125ae3c16f43bd7):
```
{
  "method": "dns-alias-resolving",
  "origin_type": "inference",
  "result": [
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|145.97.35.101",
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|145.97.35.101",
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|2001:610:2d8:300::35:101",
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|2001:610:2d8:300::35:101"
  ],
  "source": "Hostname|internet|ocauthenticatie.entree.kennisnet.nl",
  "source_method": null,
  "task_id": null,
  "type": "Origin",
  "xt/id": "Origin|inference|dns-alias-resolving|Hostname|internet|ocauthenticatie.entree.kennisnet.nl"
}
```
Note the duplication's in the results.

As we are not expecting this, we might get undefined behavior. Probably `result` should be a `set` instead of a `list`.
https://github.com/minvws/nl-kat-coordination/blob/ba809d0ce61c3a0f28940c97bd048582c657481a/octopoes/octopoes/models/origin.py#L16-L22

**To Reproduce**

1. Enable [DNSRecords(A, AAAA), NMap TCP, SSLCertificates, WebpageAnalysis] boefjes
2. Scan URL("http://metaplus.kennisnet.nl/") on L2
3. Wait
4. Observe Origin exampled above with `octopoes/tools/xtdb-cli.py --node 2 query '{:query {:find [(pull ?var [*])] :where [[?var :type "Origin"]]}}' | jq -C  | less -R`

**Expected behavior**
```
{
  "method": "dns-alias-resolving",
  "origin_type": "inference",
  "result": [
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|145.97.35.101",
    "ResolvedHostname|internet|engine.entree.kennisnet.nl|internet|2001:610:2d8:300::35:101"
  ],
  "source": "Hostname|internet|ocauthenticatie.entree.kennisnet.nl",
  "source_method": null,
  "task_id": null,
  "type": "Origin",
  "xt/id": "Origin|inference|dns-alias-resolving|Hostname|internet|ocauthenticatie.entree.kennisnet.nl"
}
```

**OpenKAT version**
main b098d8d2ee2f7bdbb4c7d98e7125ae3c16f43bd7

**Comment by underdarknl** [comment]
I agree we should not allow for multiple references t the same ooi in the results. We could cast the results to a set inside Octopoes before adding the origin, but I'd be hesitant in changing the typing of the resultset of the normalizers as I'd love to move that to Json at some point (which does not support sets), Moving it to a json based interface makes the interface platform / language agnostic.
