### ISSUE TITLE
Add cron interval field to boefje meta

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#3527]
Note that according to:
https://github.com/minvws/nl-kat-coordination/pull/3529/files#diff-ba4d44750141fd99171bebe06a2bfc32f73cf562e041bab734df40bfa999eaa0

these new fields should be `schedule` for the cron expression and `interval` for the grace period.

**Comment by underdarknl** [comment]
Two fields are required actual (after discussing with @jpbruinsslot ) 

One for the cron expression, which tells the scheduler to run the boefje *once* on the matching times for all OOI's (this needs future work on the boefjes side to implement multi-ooi inputs)

One for a backoff timer (in minutes), which the scheduler can use to push back the creation of new OOI+boefje jobs combinations from the current default of 1 day to the selected amount of minutes.

**Comment by underdarknl** [comment]
N.B. @jpbruinsslot  is going to implement the backoff timer first.

**Comment by jpbruinsslot** [comment]
> N.B. @jpbruinsslot is going to implement the backoff timer first.

Work is done on this pr: https://github.com/minvws/nl-kat-coordination/pull/3529

**Comment by Donnype** [comment]
If we only use an interval, we will never be able to handle the use-case "I want to send out my reports every Monday morning at 10:00 and have the freshest data."
