### ISSUE TITLE
Update Katalogus descriptions boefjes and normalizers

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3539]
**Describe the bug**
Not all boefjes and normalizers have a proper text now, this still needs to be updated as a continuation of  #3444

**Expected behavior**
Explanatory descriptions for all boefjes and normalizers. 

**OpenKAT version**
main

**Comment by zcrt** [comment]
It would be nice if the `description.md` files are actually shown in the front-end of OpenKAT

**Comment by stephanie0x00** [comment]
> It would be nice if the `description.md` files are actually shown in the front-end of OpenKAT

That sounds like a good feature request, but is outside of the scope of this PR. This only updates/adds the description texts in boefje.json and normalizer.json files.
