### ISSUE TITLE
Suggested plugins disappeared from Reports

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3604]
**Describe the bug**
The suggested plugins section is always empty for generated reports. 

**To Reproduce**

1. Go through the report flow and select DNS. 
2. Make sure you have some plugins enabled.
3. Generate report
4. See empty suggested plugins section. 

**Expected behavior**
The suggested plugins shows which plugins are enabled and disabled for the generated report.

**Screenshots**
![image](https://github.com/user-attachments/assets/cbe735c1-56c1-4ae1-afb8-2f03c6ffc891)

**OpenKAT version**
main

**Comment by underdarknl** [comment]
The whole section 1.3 is empty.
