### ISSUE TITLE
Nmap Ports Boefje - Add setting gives error message

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3639]
**Describe the bug**
When adding a setting to the Nmap Ports boefje like shown in the explanation, an error message is thrown.

**To Reproduce**

1. Go to 'Nmap Ports' boefje
2. Click on 'Configure Settings'
3. Open the helper text
4. Copy-paste the example in the input field
5. Click 'Add setting'
6. See error

**Expected behavior**
Setting should be saved and you should return to the boefje detail page.

**Screenshots**
![Image](https://github.com/user-attachments/assets/0e96e4fb-3fa1-4242-b213-078a7f198883)

Even with only one port:
![Image](https://github.com/user-attachments/assets/85fecc8d-67fd-442f-b5ae-cd800509e156)

**OpenKAT version**
main

**Comment by underdarknl** [comment]
The regex does indeed not match any of the expected inputs.
