### ISSUE TITLE
Reports - Vulnerability report is empty when hostnames are selected without an A or AAAA record

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3679]
**Describe the bug**
When using multiple hostnames for the vulnerability report the report is empty when one of these hostnames doesn't have an A or AAAA record.

**To Reproduce**

1. PM me for the hostname without A/AAAA records.
2. Add another hostname and generate some data for the vulnerability report.
3. Generate report and see its empty

**Expected behavior**
When a hostname without A/AAAA is also selected the vulnerability report should still be visible. 

**OpenKAT version**
main

**Comment by originalsouth** [comment]
This is not a bug in Octopoes but in the generic report generator not being to cope with empty data.

**Comment by underdarknl** [comment]
So, currently we are doing something akin to an 'outer join' where the report engine expects a regular inner join?

**Comment by originalsouth** [comment]
> So, currently we are doing something akin to an 'outer join' where the report engine expects a regular inner join?

Yeah, you could call it that -- the question is more specifically whether we want to report that we have not found anything on for this OOI rather just omitting it

**Comment by underdarknl** [comment]
I think having a choice between outer and inner joins at the API level would be useful. 
For this specific usecase, I'd expect the report to show No IP's where found, and as such no findings could be found. Its an unexpected situation, but because of that we should not silently ignore this by dropping the resulting rows from the result.

**Comment by originalsouth** [comment]
> I think having a choice between outer and inner joins at the API level would be useful.

This only makes sense on a high-level. The way we are parsing and building the data right now (at least in vulnerability reports) a filter makes more sense IMHO; which can be optionally done at a later point in the pipeline.

**Comment by originalsouth** [comment]
https://github.com/minvws/nl-kat-coordination/blob/3c4b5c09fdd7debef5666c3e83b0eae5546dfc3c/rocky/reports/report_types/vulnerability_report/report.py#L133

```
diff --git a/rocky/reports/report_types/vulnerability_report/report.py b/rocky/reports/report_types/vulnerability_report/report.py
index a04c4ca25..f226111f5 100644
--- a/rocky/reports/report_types/vulnerability_report/report.py
+++ b/rocky/reports/report_types/vulnerability_report/report.py
@@ -130,7 +130,7 @@ class VulnerabilityReport(Report):

             result[input_ooi] = data

-        return result
+        return {key: val for key, val in result.items() if val}

     def get_findings(self, input_oois: Iterable[str], valid_time: datetime) -> dict:
         ips_by_input_ooi = self.to_ips(input_oois, valid_time)
 ```

**Comment by originalsouth** [comment]
After more digging, we (thanks @madelondohmen @noamblitz) that this a race condition (you were right @noamblitz) -- the problem is the reports are not yet saved but we are already querying them -- waiting some time resolves the problem.
