### ISSUE TITLE
Change "Consumes" to "input" and "produces" to "output"

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#380]
For boefjes we always talked about consumes and produces, but input/output seems more fitting.

**Comment by underdarknl** [comment]
Output OOI Types is not a given, as it depends on the normalizers present in the installation. Output raw-file mime-types is also not a given, as some boefjes might include random mime-types as they are found when scanning. For example the download boefje might introduce hundreds of different mime-types into the Bytes data-store. Listing them would be useless.
