### ISSUE TITLE
Run boefje once at creation or update of ooi

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#3879]
> Dit boefje maar 1 keer draaien bij de create van een ooi, of eventueel als tweede spoor, dit boefje alleen draaien als het OOI veranderd. @underdarknl 

From the scheduler we need to differentiate what types of boefje requires a different approach for calculating the next time a task needs to run or to run once. Likely we need to update the boefje definition in order to give the scheduler the necessary information on how to schedule the task.

**Comment by jpbruinsslot** [comment]
@underdarknl could you work out the requirements for this feature request and the likely scenarios?

**Comment by underdarknl** [comment]
@jpbruinsslot I agree we should add this as a flag to the boefjes definition if needed.
I propose the following options for a boefje:
* Interval (as already implemented, and the default scheduling strategy)
* Creation (indicated by a new flag in the boefjes definition runon: creation)
* Update (indicated by a new flag in the boefjes definition runon: update)

Deletion is never cause for a boefje to run, and neither are reads. 
If the runon flag is present, the interval could be implemented as a delay, but I'd rather not overload that field, and instead just ignore it. We could present a warning to the user if both fields are set to explain the behavior for a given Boefje.

**Comment by underdarknl** [comment]
The likely usecase would be to run a boefje Once on every create/update to make sure we gather static data from a remote source, or send the OOI to a remote sink when we create/Update it in KAT.  An alerting boefje that sends out the OOI 'as it happens' would be our first user of this feature.

**Comment by jpbruinsslot** [comment]
| mutation operation type | boefje runon | create schedule? | run task? |
| ----------------------- | ------------ | ---------------- | --------- |
| `CREATE`                | `create`     | `false`          | `true`    |
| `CREATE`                | `update`     | `false`          | `false`   |
| `CREATE`                | `None`       | `true`           | `true`    |
| `UPDATE`                | `create`     | `false`          | `false`   |
| `UPDATE`                | `update`     | `false`          | `true`    |
| `UPDATE`                | `None`       | `true`           | `true`    |

**Comment by jpbruinsslot** [comment]
PR https://github.com/minvws/nl-kat-coordination/pull/3906 is updated and can be tested with https://github.com/minvws/nl-kat-coordination/pull/3901

Note that tests haven't been written yet.

**Comment by jpbruinsslot** [comment]
Tests have been added to the PR
