### ISSUE TITLE
allow filtering on object list page based on scan_profile_type and scan_profile_type

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#391]
### Describe the bug, issue or concern
Currently there is no way to filter the object list on the following criteria, the current octopoes objects api does not yet support this, but does support this on the scan-profiles endpoint.

* Filter on scan profile declaration type (declared, inherited, None)
* Filter on scan profile level (None, 0, 1, 2, 3, 4)

Adding this would allow users to quickly see what objects are (for example) new and have no scan profile.
The same mechanism can be used to filter objects eligible for scanning by a given boefje on the boefje detail page, where this is now being filtered in python time. https://github.com/minvws/nl-kat-rocky/blob/c4a17846bde7114b1964c1cc69854e27e4de621e/katalogus/views/plugin_detail_scan_oois.py#L67

**Comment by Lisser** [comment]
Already implemented
