### ISSUE TITLE
Rocky's health page can crash on pydantic validationerror in some situations

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#392]
### Describe the bug, issue or concern

Somehow the health page on Rocky can crash on a combination of error-data. This should not happen, and instead it should be showing the page with information on what crashed instead of crashing itself.

### To Reproduce
1. Go to '/health/v1'
2. observe 500 error

### Expected behavior
A working health page showing what works, and what doesn't.

### Logs
```
nov 16 11:53:38 nsec-lnx-03 python[55451]: [2022-11-16 11:53:38 +0100] [55451] [ERROR] [h11_impl] [uvicorn.error] Exception in ASGI application
nov 16 11:53:38 nsec-lnx-03 python[55451]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
nov 16 11:53:38 nsec-lnx-03 python[55451]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
nov 16 11:53:38 nsec-lnx-03 python[55451]: pydantic.error_wrappers.ValidationError: 1 validation error for ServiceHealth
nov 16 11:53:38 nsec-lnx-03 python[55451]:   str type expected (type=type_error.str)
```

**Comment by Donnype** [comment]
@underdarknl I cannot reproduce this by turning off Keiko now. Has this one been fixed?
