### ISSUE TITLE
Who do we want to assign to a ticket?

### ISSUE THREAD

**Issue by madelondohmen** [minvws/nl-kat-coordination#3935]
We've started this discussion during the retrospective on 05-12-2024. 

What do we want to do?
- Assign the owner of the ticket
- Assign the person who is working on the ticket?

**Comment by underdarknl** [comment]
>     * Assign the person who is working on the ticket?

 * Assign the person who is expected to be / should be working on the ticket?

**Comment by madelondohmen** [comment]
Outcome of discussion meet 10-12-2024:

We are going to try for a while to assign the person who is expected to be/should be working on the ticket. 
That way you can also see during the stand-up what work there is for everyone to do that day.
