### ISSUE TITLE
Enabled boefjes sync between organisations

### ISSUE THREAD

**Issue by stephanie0x00** [minvws/nl-kat-coordination#3941]
**Describe the bug**
When you have 2 organisations, the enabled and disabled boefjes are the 'synced' with multiple organisations. This means that if you have nmap tcp, and log4shell enabled for Organisation A, these will also be enabled for Organisation B. 

**To Reproduce**

1. Go through the onboarding for organisation A. Enable an extra boefje, eg. nmap tcp.
2. Create a second organisation.
3. check the katalogus page for organisation B and observe that the enabled boefjes are similar to those of organisation A. 

**Expected behavior**
Organisations should be able to have their own selection of boefjes enabled. 

**Screenshots**
-

**OpenKAT version**
main

**Comment by underdarknl** [comment]
Nope, does not look that way: 
https://github.com/minvws/nl-kat-coordination/blob/2320a417a0faf2a04407c22c520946753ba41eab/rocky/account/mixins.py#L90

But, we should probably cache or move the lookups to the member.organization.code to an property of the KATalogus in:
https://github.com/minvws/nl-kat-coordination/blob/2320a417a0faf2a04407c22c520946753ba41eab/rocky/katalogus/client.py#L309
