### ISSUE TITLE
Show yielded objects of normalize

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#398]
_Please add one or more of the following labels to your issue:_
`frontend`

**Is your feature request related to a problem? Please describe.**
The link `Download meta and raw data` on the Task page for a normalizer does not return the yielded normalizer output, nor its logs. Instead the input (boefje output) is shown.

**Describe the solution you'd like**
I would expect both the input, (current) output and the logs of the normalizer to be available.

**Describe alternatives you've considered**
Read the logs in the containers, not very user friendly, not possible on every system for all users.

**Additional context**
Also when yielding an object returns an Octopoes API error, this should also be visible in the frontend (and possibly not result in a green 'completed').

**Comment by underdarknl** [comment]
On the task page, I'd like to see the following 3 columns instead of the current 'download raw data'
* Consumed Raw File
* Produced by Boefje on date (link to job on boefje task list)
* MimeType (link to page with raw files, which we need to design)
* Output OOI's (as linked objects)
