### ISSUE TITLE
Bring "organization filtering" to "database time" instead of "python time" for org member with status "blocked"

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#411]
`get_user_organizations()` now uses a list comprehension to filter organisations where the org member is blocked, but this should be done in database time instead.

**Comment by Lisser** [comment]
Logic regarding filtering organizations for a user seems to be implemented in too many places. On top of that, it's implemented slightly differently in each place:

https://github.com/minvws/nl-kat-coordination/blob/3c0b40c0a92c0eaf9b8d98cf91fb57332bbd310f/rocky/tools/user_helpers.py#L13-L17

https://github.com/minvws/nl-kat-coordination/blob/bf30408fb631b71b287176a2ab660e3702d0c7dc/rocky/crisis_room/views.py#L43-L45

https://github.com/minvws/nl-kat-coordination/blob/bf30408fb631b71b287176a2ab660e3702d0c7dc/rocky/crisis_room/views.py#L67-L70

https://github.com/minvws/nl-kat-coordination/blob/bf30408fb631b71b287176a2ab660e3702d0c7dc/rocky/crisis_room/views.py#L83

https://github.com/minvws/nl-kat-coordination/blob/bf30408fb631b71b287176a2ab660e3702d0c7dc/rocky/account/templatetags/organization_management.py#L8-L19

https://github.com/minvws/nl-kat-coordination/blob/bf30408fb631b71b287176a2ab660e3702d0c7dc/rocky/rocky/views/organization_list.py#L22-L33

Let's try to:
- figure out the common logic
- document this 
- implement this cleanly, with tests

**Comment by Rieven** [comment]
Another django way of doing the querying:

`from myapp.models import Entry
from django.db.models import Q

members = OrganizationMember.objects.filter(user=self.request.user, status=~Q(OrganizationMember.STATUSES.BLOCKED))
`
Which return all non-blocked users

**Comment by Rieven** [comment]
Blocked users should not be able to do anything. We can move the logic of blocked users or in a middleware or we create a class based view for it. Blocking a user for me means no access to the app itself, but this must be mapped out of what exactly is expected.

All members can view data, but only redteamers can scan and create evidence.
Admins can edit organizations and members

I have made some tests for this at:
https://github.com/minvws/nl-kat-coordination/blob/d173812861450079e9eac3456593dbfcadcc2433/rocky/tests/test_member_edit.py

**Comment by TwistMeister** [comment]
@Rieven `Blocked users should not be able to do anything. ... Blocking a user for me means no access to the app itself...` - this is untrue and I would like you to be cautious with such statements.

"blocked" is a status that belongs to the **organization member**. Therefor it shouldn't affect the user as a whole. It's only meaning is "this user can no longer access assets or information about this organization". Meaning the general pages, like crisis room should still be available, and therefor the user should still be able to login.

It's perfectly possible a user is linked to more than one organization, and then they should not be locked out of either KAT or the crisis room. They should be able to view the organization that they are suspended (status=="blocked") for, but they should still be able to access all other organizations they are linked to.

One UX thing that still has to be decided is "should the organization still exist in the organization drop down". Because there are pros and cons to this. One of the things why we don't want to exclude it from the list is that a user might wonder what is wrong and why it's not there. If it still exists in the drop down, the user can still navigate to that organization and then we can show a messages on the organization dashboard that informs the user about its suspension for that oragnization and to contact an admin.

**Comment by TwistMeister** [comment]
@Lisser to clear things up a bit more:
When a user is suspended from an organization the organization may still exist in the users drop down. At least for now. When the user navigates to such an organization a 403 - Unauthorized page should be shown. Jan and I discussed this and we decided a 403 is fine (in terms of giving away information), because the user has to be linked to the organization and therefor probably already knows it exists. For users that are not at all linked to an organization a 404 should be shown instead of a 403, but that might be out of scope for this issue.

To sum things up:
**should 'blocked' organisations appear in the org menu dropdown?**
Yes, so a user doesn't have to wonder where the organization went and to enable us to give a more detailed error message on the follow up page (which will be the organization dashboard, probably)

**should 'blocked' organisations appear on the crisis room?**
I didn't check this yet, but I would say no, because this is a slippery slope. Having it show there leads to the desire to access it to learn more about the info shown on the crisis room, which they can't. Also it seems unexpected to the organization admin that suspended the user, that the user still is able to view information about said organization.

**how should the logic regarding access to organisations be, regarding permissions, red-teamers, and superadmins?**
I'm not sure what you mean with the logic regarding access to organizations per role. But I'll try to shine some light from what I do know:

AFAIK every organization member should be able to access the organization where they are linked to as organization member. UNLESS they are suspended (status=="blocked").

In terms of organization administration/management: Superusers and organization admins are the only ones that should be able to access the organization members list. They are the ones that can suspend other organization members. 

Superusers should not be able to get suspended.

I'm not sure about organization admins. Maybe they should be able to suspend eachother, maybe not. Maybe only the superuser should be able to suspend organization admins. This has yet to be determined.

Clients and red-teamers have nothing to do with the organization members list, they can access KAT to do security scanning and reporting stuff, not user management.

**Comment by Lisser** [comment]
Thanks @TwistMeister and @Rieven for your inputs. This is a lot more clear.

Do superadmins get automatic access to each Organization? (And thus also automatically get all Organizations in the dropdown / on the crisis room?)

**Comment by Lisser** [comment]
For clarity, here are the places in the Rocky UI that deal with Organization lists.

### Clone settings in Katalogus
![Screenshot 2023-03-10 at 10 25 13](https://user-images.githubusercontent.com/9639395/224277417-de3025e3-7535-4989-98b5-9a29584204f5.png)

### Navbar
![Screenshot 2023-03-10 at 11 05 33](https://user-images.githubusercontent.com/9639395/224287583-a2e41313-04ab-494a-bbce-5627308498a1.png)

### Crisis room
![Screenshot 2023-03-10 at 11 08 07](https://user-images.githubusercontent.com/9639395/224288164-8875b7dc-fdf0-4f94-8626-6f5ba0bc27b2.png)

### Organization List
![Screenshot 2023-03-10 at 11 19 56](https://user-images.githubusercontent.com/9639395/224290844-867c6da6-c069-4db9-b2a1-e5fff3f9e783.png)

TODO:
Describe for each, which situations can arise and how it should be dealth with
