### ISSUE TITLE
Failing to create organization for external services in post_create creates inconsistency in Rocky

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#428]
When starting up services and some failing to get up, creating an organization in Rocky at several times has caused inconsistency in my setup since a failed post_create does not delete the organization. This means we also cannot retry creating an organization. I would suggest to make this (and perhaps other?) more atomic, meaning we only finish the creation of an organization when all services succeed to create one and else delete organizations everywhere. Another option would be to support some interface to retry this, but since the existence of organizations is crucial to functionality I would not opt for this now perhaps. Retrying the creation calls in `post_create` is already a good first step by the way.

**Comment by dekkers** [comment]
I doubt that retrying again will help, because most of the time this fails because there is some misconfiguration that needs to be fixed. What probably would help a lot is if we have good health checks everywhere and don't allow creation of an organization when not all services are healthy.

**Comment by Donnype** [comment]
Agreed that basic retries would not capture most current cases. Only checking health of services would not capture bugs/programming errors in those services though, still leaving Rocky open to inconsistencies. The trade-off would be consistency vs. availability I guess, although it is arguable how `available` Rocky really is when you can create organizations without having the organization in the Katalogus or an XTDB node for that organization.
