### ISSUE TITLE
superuser admin can see all organisations on crisis room (and sees findings) but cannot navigate into organisations

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#442]
A super user on his crisis room page can see all organisations, however we cannot navigate into organisations for which no organisatonMember record is present.
Further more, the lookup for the total number of findings seems to work regardless of this record, where it shoudn't.
A superuser should just be presented with a confirm box to create the missing record if needed, or a 404 like any other user if he tries to visit an organisation for which we has no rights.

**Comment by underdarknl** [comment]
this should be covered in: https://github.com/minvws/nl-kat-coordination/pull/528

**Comment by dekkers** [comment]
#528 has been merged
