### ISSUE TITLE
You are not verified as an organization member by your system administrator.

### ISSUE THREAD

**Issue by rvanlieshout** [minvws/nl-kat-coordination#446]
**Describe the bug**
I've just added new users but am unable to sign in to any of these because of the message:

> # Enable Two-Factor Authentication
> 
> You are not verified as an organization member by your system administrator. Contact your system administrator about your verification to proceed to Two Factor Authentication setup.

I've got no clue where I should take actions now. Any hints would be appreciated

**To Reproduce**

1. Add a new member on https://openkat.lico.nl/en/org/members/add/
2. Sign in as that user
3. Click 'Setup two factor authentication'

**Expected behavior**
I would expect to be able to enable Two-Factor Authentication 

**Screenshots**

<img width="1478" alt="Scherm­afbeelding 2023-03-07 om 10 17 39" src="https://user-images.githubusercontent.com/430979/223377798-da6902d5-1716-4176-9ff3-3a021c1fded1.png">

**OpenKAT version**
Note the release tag (and if possible: the installation method) here.
If it concerns an in-development version, note the branch(es) and commit hash(es) here as well.

I've followed https://docs.openkat.nl/technical_design/containers.html and am on:

`commit 4461e59acbffe6f655e3a44332329c229ea7f759 (HEAD -> main, origin/main, origin/HEAD)`

**Comment by zcrt** [comment]
There may be an option to set the specific user to 'verified' on https://openkat.lico.nl/admin (`Organization members`)

**Comment by rvanlieshout** [comment]
I've managed to resolve this by checking verified on https://openkat.lico.nl/en/admin/tools/organizationmember/3/change/. Thanks

Would I have expected the need to use /admin for this? (although I'm perfectly ok with that)
