### ISSUE TITLE
Remove `Job` model from Rocky?

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#453]
This is legacy^2

**Comment by underdarknl** [comment]
Wouldn't we want to introduce an object again which handles the data that a Job now has, but also implements methods to restart the job?
I'd say this is more useful than just a Dict, and is something that could be handed a Scheduler-client-instance to communicate trough. They could also be created by the Scheduler-client.

**Comment by Donnype** [comment]
It's mostly the Job table in Rocky I'm referring to. This seems to have 0 uses in Rocky.

**Comment by ammar92** [comment]
This is a duplicate of https://github.com/minvws/nl-kat-coordination/issues/352
