### ISSUE TITLE
Location headers should allow relative paths

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#454]
**Describe the bug**
Relative paths are possible in Location headers and should be correctly classified as such.

**To Reproduce**
1. Add scirpt.php in a location header

**Expected behavior**
domain.com/script.php should be added as httpurl, script.php is added currently.

**OpenKAT version**
1.6

**Comment by underdarknl** [comment]
The path in a location header should be absolute: https://www.rfc-editor.org/rfc/rfc2616#section-14.30

However, no browser (and therefor now website) knows this, or implements it this way.
There are relatively straightforward rules to go from a relative uri to an absolute uri which we can apply however, (if the originating uri is known):
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Resolution
