### ISSUE TITLE
Rocky uses outdated CWE database

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#470]
Rocky uses the `cwe` python library for CWE information. This includes the CWE database, but the package hasn't been updated since June 2020. It was created in two weeks and seems to be abandoned after that. Because of this we are using an outdated version of the CWE database.

We should switch to use the XML that is available at https://cwe.mitre.org/data/downloads.html.

**Comment by zcrt** [comment]
Related: https://github.com/minvws/nl-kat-coordination/issues/152
