### ISSUE TITLE
Octopoes installation fails during 'make install'

### ISSUE THREAD

**Issue by Tedixx** [minvws/nl-kat-coordination#48]
### Describe the bug, issue or concern
Following the installation instructions displayed at https://github.com/minvws/nl-kat-coordination/wiki/Installatiehandleiding-KAT, the installation of OpenKAT, in specific octopoes, is not successful. The following error message appears: " => ERROR [stage-0 3/7] RUN groupadd --gid 0 octopoes" 

![error](https://user-images.githubusercontent.com/82908532/194044788-36dd8b88-6e2c-4f1e-86fb-e8d07522402a.png)

The installation was conducted from a clean DigitalOcean droplet running Ubuntu 20.04, with the latest update. A regular user account (ID 1000, sudo rights) was used during installations. The error message appears at 'make kat.' Manual adding octopoes as --gid 0 octopoes does not solve this issue.

**Comment by underdarknl** [comment]
@Donnype could you take a look at this?

**Comment by Donnype** [comment]
@Tedixx It seems like the user running `make kat` is in group 0. This does not seem have any special privileges under Linux, and can simply be supported perhaps. We would then need to change the Dockerfile(s) to read something like
```shell
getent group {service} || groupadd --gid $USER_GID {service}
```
(source: https://unix.stackexchange.com/questions/145348/short-simple-command-to-create-a-group-if-it-doesnt-already-exist)

This does require testing to see if this does not introduce the bug it was trying to solve again: permission issues for the containers accessing the mounted volumes. @underdarknl Thoughts?

**Comment by Donnype** [comment]
Or was `sudo make kat` run instead of `make kat`?

**Comment by underdarknl** [comment]
> @Tedixx It seems like the user running `make kat` is in group 0. This does not seem have any special privileges under Linux, and can simply be supported perhaps. We would then need to change the Dockerfile(s) to read something like
> 
> ```shell
> getent group {service} || groupadd --gid $USER_GID {service}
> ```
> 
> (source: https://unix.stackexchange.com/questions/145348/short-simple-command-to-create-a-group-if-it-doesnt-already-exist)
> 
> This does require testing to see if this does not introduce the bug it was trying to solve again: permission issues for the containers accessing the mounted volumes. @underdarknl Thoughts?

I think using a user with group 0 would pose some security issues with the current various permissions, we should either clamp down more, but im guessing we should not support users or groups with id 0 as that would normally mean root on many systems
