### ISSUE TITLE
Mula, keep track of the changeset of OOI_types when new plugins are enabled and query for those objects

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#486]
When Mula refreshes its KAT-alogus info, it should keep track of the changeset of OOI_Types, (and possibly related minimal scan levels). This elta can be used to directly ask Octopoes for objects that would from then on be eligible for scheduling.
This would give our users a better instant satisfaction when enabling new boefjes

**Comment by jpbruinsslot** [comment]
Related: https://github.com/minvws/nl-kat-coordination/issues/204

**Comment by jpbruinsslot** [comment]
To get ooi's and boefjes scheduled, when a new boefje gets enabled I would recommend leveraging the work on this pr into a feature branch https://github.com/minvws/nl-kat-coordination/blob/a1d041d072839a478fc5c0cc948c67481f4b8df7/mula/scheduler/schedulers/boefje.py#L193

This requires a change in octopoes https://github.com/minvws/nl-kat-coordination/issues/227 to relay a list of ooi's from an organization that an enabled boefje can run on. `get_objects_by_object_type()` @Lisser  thoughts?

I'm a bit hesitant to add another accounting/cache to keep track of in the scheduler. And I think this would solve the problem of "directly ask Octopoes for objects that would from then on be eligible for scheduling."
