### ISSUE TITLE
Mula metrics endpoint for current katalogus info

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#487]
Currently, its hard to see if Mula has any up to date katalogus details for a given organization, and what those details are. I would propose a few metrics:
* The raw known katalogus set for a given organization.
* The time since the last refresh
* The refresh interval
* Possible the set of handled OOI_Types and their related scan levels s per the enabled boefjes
Some of this data could be shown on the health endpoint too, as it helps with peeking inside the scheduler

**Comment by jpbruinsslot** [comment]
Relevant: https://github.com/minvws/nl-kat-coordination/issues/298
