### ISSUE TITLE
Gitpod can't launch a new instance of openKAT

### ISSUE THREAD

**Issue by Robinzor** [minvws/nl-kat-coordination#493]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._

**Describe the bug**
Gitpod can't launch a new instance.

http 503 on package https://ghcr.io/v2/dekkers/xtdb-http-multinode/manifests/main

**Screenshots**
![image](https://user-images.githubusercontent.com/70282027/225349553-ee57628a-68ad-4068-8208-b28212519d66.png)

![image](https://user-images.githubusercontent.com/70282027/225349888-717a2b2e-2e04-4c7e-8c9d-abc710d1d7b1.png)

**Comment by underdarknl** [comment]
Judging by the error, it might be a temporary issue at ghcr.io ?

**Comment by Robinzor** [comment]
Seems to be working again.

**Comment by Robinzor** [comment]
problem is solve but outside of gitpod the authentication error is still there so I guess there is some authentication within gitpod.
