### ISSUE TITLE
Show boefjes, normalizers and bits in Katalogus

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#498]
**Is your feature request related to a problem? Please describe.**
The KATalogus currently only shows boefjes.

**Describe the solution you'd like**
Make boefjes, normalizers and bits visible (and controllable).

**Describe alternatives you've considered**
None

**Additional context**
Related: https://github.com/minvws/nl-kat-coordination/issues/230
Priority: ++

**Comment by TwistMeister** [comment]
Is currently being designed in https://github.com/minvws/nl-kat-coordination/issues/524.

**Comment by NoemiOverdijk** [comment]
The redesign for the KAT-alogus is ready and shows normalizers and bits alongside the boefjes.

[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?node-id=225%3A9532&t=7pcrwLmTfpKAPQjn-1](url)

**Comment by NoemiOverdijk** [comment]
![KAT-alogus](https://user-images.githubusercontent.com/118826623/228850790-f45ba88c-6def-4686-8f2f-6145f660e59a.png)
This is what the overview of all plugins wil look like

**Comment by underdarknl** [comment]
@zcrt agreed. filtering should be implemented.

For now, we will implement the normalizer flow, and maybe the BIt frontend, but we wont show the BIT frontend, as wedo not yet have them in our kataogus api's.
