### ISSUE TITLE
[UI/UX] Show origin of OOI

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#501]
**Is your feature request related to a problem? Please describe.**
Origin of object of interest is hard to find. As an end-user I would like to quickly filter on object that were added by hand, objects that were found by normalizer N/bit B/KAT as a whole, and object ingested from an external database (e.g. DADB).

**Describe the solution you'd like**
Storing this information with objects and making it searchable in the front-end.

**Additional context**
Priority: ++
Related: https://github.com/minvws/nl-kat-coordination/issues/364

**Comment by TwistMeister** [comment]
At present, there are OOIs that are present in KAT, but their origins are unclear. These OOIs can be associated with hostnames that have corresponding DNS records from different levels of nameservers. It would be useful to have a feature that can determine the shortest path of inheritance/observation to an OOI with a specified scan level. This feature can be implemented as a manual query and need not be displayed on every detail page.

**Comment by noamblitz** [comment]
Just keep in mind that calculating this might be quite expensive, so consider showing this only after a specific request from a user.

**Comment by Lisser** [comment]
Implement an algorithm that finds a path from a given OOI with a clearance level to an OOI with a declared clearance level by traversing the graph..

So, a clearance level inheritance path. This does not have to be the shortest path specifically 

Then:
- Implement a visualization in Rocky on the OOI detail page (on demand, to not slow down the OOI detail page)
- [Implement visualization in the PDF report]
