### ISSUE TITLE
[UI/UX] Add scope to reports

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#503]
**Is your feature request related to a problem? Please describe.**
The scope of reports is unclear. One would like to know, how findings are found and the actions KAT took to get to its findings.

**Describe the solution you'd like**
Make it clear in a report which actions where taken by KAT to reach its conclusions. 

**Additional context**
Priority: +

**Comment by TwistMeister** [comment]
This is already work in progress, as I thought you were aware. Please check if issues exist before requesting a feature.
Both https://github.com/minvws/nl-kat-coordination/issues/344 and https://github.com/minvws/nl-kat-coordination/issues/333 are about the feature requested, see them for more details and if applicable join the discussion in the comments.
