### ISSUE TITLE
`admin` organization code causes route priority issues

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#510]
**Describe the bug**
If the organization code name is "admin", users are redirected to the Django admin interface. 

**To Reproduce**
1. Do a clean `make kat`
2. Create an organization with the code `admin`
3. Notice that you are redirected to the Django admin interface.

**Expected behavior**
We should probably not allow reserved organization codes, such as admin and static, to prevent route priority bugs.

Include these comments:
https://github.com/minvws/nl-kat-coordination/issues/790

**Comment by underdarknl** [comment]
I think the only way around this is to have a deny-list of url's that we cannot use because they are already taken.

**Comment by underdarknl** [comment]
I think the only way around this is to have a deny-list of url's that we cannot use because they are already taken.

**Comment by Darwinkel** [comment]
Verification without Django-admin has been implemented recently :tada:
