### ISSUE TITLE
error 'access_token' when I try to create a network

### ISSUE THREAD

**Issue by ErikNoort** [minvws/nl-kat-coordination#514]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._
bug rocky

**Describe the bug**
I cannot create a network, instead 'access_token' is replied 

**To Reproduce**
1. Go to Object
2. Click add, add object
3. select network and click add object
4. enter a name and click add network
5. the notification 'access_token' is added in the 

**Expected behavior**
I would expect a network object to be created

**Screenshots**
See attachment
![kat error network creation](https://user-images.githubusercontent.com/109131344/225864852-a631989a-a50c-4607-a231-e85c34a354ce.png)

**OpenKAT version**
version 1.7.0rc1 on Debian 11.6

**Desktop (please complete the following information if relevant):**
 - OS: Windows 11
 - Browser: Chrome 111 and Firefox

**Comment by underdarknl** [comment]
Im thinking somewhere your setup has not fully installed as it should.
What info does the health link at the bottom of the page give you?

**Comment by ErikNoort** [comment]
Hi Jan,

health page:

Service	Healthy	Version	Additional
rocky	True	0.0.1.dev1	-
octopoes	True	0.0.1.dev1	-
xtdb	True	1.23.0	{'version': '1.23.0', 'revision': 'c9ae268855e156f07ac471537445823f011bc320', 'indexVersion': 22, 'consumerState': None, 'kvStore': 'xtdb.rocksdb.RocksKv', 'estimateNumKeys': 1, 'size': 10941289}
katalogus	True	0.0.1-development	-
scheduler	True	0.0.1.dev1	-
bytes	True	0.0.1.dev1	-
keiko	True	0.1.0	-

It was a fresh installation on 1.6.2 (same issue) and after that an upgrade to 1.7.0rc1

Thanks, Erik

**Comment by ErikNoort** [comment]
Hi

Did a clean reinstall of 1.7.1 and now everything is working again.

Regards, Erik
