### ISSUE TITLE
cannot complete onboarding step with setup scan url with server error 500

### ISSUE THREAD

**Issue by ErikNoort** [minvws/nl-kat-coordination#515]
_Please add `bug`, the name of any relevant modules (e.g. `rocky`), and any other relevant labels to your issue._
bug rocky

**Describe the bug**
cannot complete onboarding step with setup scan url with server error 500, it fails to add an url

**To Reproduce**
1. Go to /en/onboarding/customer/step/setup-scan/ooi/info/
2. Click on  DNS report (other types are greyed out)
3. Click add url
4. Server Error (500)

**Expected behavior**
I would expect the 

**Screenshots**

**OpenKAT version**
Openkat 1.7rc1 on Debian 11.6

**Desktop (please complete the following information if relevant):**
 - OS: Windows 11
 - Browser: Chrome 111

**Additional context**
Syslog produces the following:

Mar 17 10:33:37 dcwkat kat-rocky[251814]: ERROR:django.request:Internal Server Error: /en/onboarding/customer/step/setup-scan/URL/
Mar 17 10:33:37 dcwkat kat-rocky[251814]: Traceback (most recent call last):
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/octopoes/connector/octopoes.py", line 36, in _verify_response
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     response.raise_for_status()
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     raise HTTPError(http_error_msg, response=self)
Mar 17 10:33:37 dcwkat kat-rocky[251814]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8001/computerwacht/object?reference=Network%7Cinternet&valid_time=2023-03-17+09%3A33%3A36.969074%2B00%3A00
Mar 17 10:33:37 dcwkat kat-rocky[251814]: During handling of the above exception, another exception occurred:
Mar 17 10:33:37 dcwkat kat-rocky[251814]: Traceback (most recent call last):
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/tools/ooi_helpers.py", line 368, in get_or_create_ooi
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return api_connector.get(ooi.reference, observed_at), False
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/octopoes/connector/octopoes.py", line 99, in get
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     res = self.session.get(
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return self.request("GET", url, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/octopoes/connector/octopoes.py", line 56, in request
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     self._verify_response(response)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/octopoes/connector/octopoes.py", line 40, in _verify_response
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     raise ObjectNotFoundException(data["value"])
Mar 17 10:33:37 dcwkat kat-rocky[251814]: octopoes.models.exception.ObjectNotFoundException: Network|internet
Mar 17 10:33:37 dcwkat kat-rocky[251814]: During handling of the above exception, another exception occurred:
Mar 17 10:33:37 dcwkat kat-rocky[251814]: Traceback (most recent call last):
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     response = get_response(request)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return self.dispatch(request, *args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return bound_method(*args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return view_func(request, *args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return super().dispatch(request, *args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return super().dispatch(request, *args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper

Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return handler(request, *args, **kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/views/generic/edit.py", line 133, in get
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return self.render_to_response(self.get_context_data())
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/onboarding/views.py", line 239, in get_context_data
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     context = super().get_context_data(**kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/tools/view_helpers.py", line 111, in get_context_data
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     context = super().get_context_data(**kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/account/mixins.py", line 58, in get_context_data
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     context = super().get_context_data(**kwargs)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/views/generic/edit.py", line 66, in get_context_data
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     kwargs['form'] = self.get_form()
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/ooi_view.py", line 104, in get_form
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     kwargs = self.get_form_kwargs()
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/onboarding/views.py", line 215, in get_form_kwargs
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     hidden_fields = self.get_hidden_form_fields()
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/onboarding/views.py", line 201, in get_hidden_form_fields
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     ooi, created = get_or_create_ooi(self.octopoes_api_connector, bytes_client, params["ooi"])
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/tools/ooi_helpers.py", line 374, in get_or_create_ooi
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     create_ooi(api_connector, bytes_client, ooi, observed_at)
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/tools/ooi_helpers.py", line 386, in create_ooi
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     bytes_client.add_manual_proof(task_id, BytesClient.raw_from_declarations([declaration]))
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/bytes_client.py", line 45, in add_manual_proof
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     self.login()
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/bytes_client.py", line 150, in login
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     self.session.headers.update(self._authorization_header())
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/bytes_client.py", line 153, in _authorization_header
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return {"Authorization": f"bearer {self._get_token()}"}
Mar 17 10:33:37 dcwkat kat-rocky[251814]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/bytes_client.py", line 162, in _get_token
Mar 17 10:33:37 dcwkat kat-rocky[251814]:     return response.json()["access_token"]
Mar 17 10:33:37 dcwkat kat-rocky[251814]: KeyError: 'access_token'

**Comment by underdarknl** [comment]
It looks like your Octopoes or Bytes service is not running, or cannot be accessed.
Did you do an upgrade, or a fresh install?

**Comment by ErikNoort** [comment]
Hi

Did a clean reinstall of 1.7.1 and now everything is working again.

Regards, Erik

**Comment by ErikNoort** [comment]
Hi

Did a clean reinstall of 1.7.1 and now everything is working again.

Regards, Erik
