### ISSUE TITLE
Update endpoint(s) in mula to handle GET requests without body

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#544]
This is a ticket coming from trying to update FastAPI in https://github.com/minvws/nl-kat-coordination/pull/467: the new Starlette version does not accept a body for GET requests.

**Comment by jpbruinsslot** [comment]
Would like to add that it is important to reach consensus over what rest api conventions we use within KAT. After that I'll implement/update the scheduler API

**Comment by jpbruinsslot** [comment]
Related: https://github.com/minvws/nl-kat-coordination/issues/396
