### ISSUE TITLE
"example.org" in rocky

### ISSUE THREAD

**Issue by psy0rz** [minvws/nl-kat-coordination#563]
insignificant but kind of annoyingly, it always says example.org:

![image](https://user-images.githubusercontent.com/1179017/227475158-1b3a58ca-3424-4a94-8c97-b3e52cb9292c.png)

**Comment by psy0rz** [comment]
i tried to fix it a while ago but ended up in a wild goose chase :p

**Comment by psy0rz** [comment]
also: the only clearance level you can choose is L2?

**Comment by underdarknl** [comment]
> also: the only clearance level you can choose is L2?

This is by design, to make sure that the resulting DNS report is at least somewhat predictable.
