### ISSUE TITLE
Container stoppen "exited"

### ISSUE THREAD

**Issue by HeiniscM** [minvws/nl-kat-coordination#58]
De volgende drie Containers in Docker willen niet starten:
1.) nl-kat-coordination_bytes_run_b766dcf89cca
2.) nl-kat-coordination_katalogus_run_a8f4b5a4b7d1
3.) nl-kat-coordination_katalogus_run_f2288df3ab43

**Server**
 - OS: Ubuntu 22.04.1 LTS
 - Browser Google Chrome
 - Portainer

Zelf heb ik OpenKat voor de eerste keer gebruikt en wou vragen of het normaal is dat deze drie niet willen starten.

Screenshots:
![image](https://user-images.githubusercontent.com/117154558/199209606-01a1718f-4202-4c75-97c1-1a087cd88e22.png)

**Comment by underdarknl** [comment]
Beste @HeiniscM heb je wat output van de logs van deze containers? ze horen allemaal netjes te starten, maar de reden waarom ze dat niet doen is zo nog niet te zeggen.
Wellicht is er geheugengebrek, of een andere reden.
