### ISSUE TITLE
Exception because sqlite return naive datetime even with timezone=True

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#583]
This is with the 1.7.0rc3 Debian packages which still use in-memory sqlite in the default install / if you follow the docs. As far as I can see this is because with sqlite sqlalchemy can return naive datetimes with `timezone=True`: https://mike.depalatis.net/blog/sqlalchemy-timestamps.html

```Mar 27 22:40:34 deb17 kat-mula[936690]: [2023-03-27 22:40:34 +0200] [936690] [WARNING] [boefje] [scheduler.schedulers.boefje] Could not check if grace period has passed: id='0c92a1>
Mar 27 22:40:34 deb17 kat-mula[936690]: Traceback (most recent call last):
Mar 27 22:40:34 deb17 kat-mula[936690]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/scheduler/schedulers/boefje.py", line 328, in push_tasks_for_random_objects
Mar 27 22:40:34 deb17 kat-mula[936690]:     grace_period_passed = self.has_grace_period_passed(task)
Mar 27 22:40:34 deb17 kat-mula[936690]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/scheduler/schedulers/boefje.py", line 580, in has_grace_period_passed
Mar 27 22:40:34 deb17 kat-mula[936690]:     if task_db is not None and datetime.now(timezone.utc) - task_db.modified_at < timedelta(
Mar 27 22:40:34 deb17 kat-mula[936690]: TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by dekkers** [comment]
I agree. I'm going to switch Debian packaging and Debian installation manual to PostgreSQL and write release notes for 1.7 to change this. And we should probably give an error on startup when people try to use sqlite.

**Comment by underdarknl** [comment]
@jpbruinsslot do we need to do any migrations on existing data in the sqlite tables for Mula, or will it recover automatically, (possibly with some extra load) if we just setup a clean empty database for it?

**Comment by jpbruinsslot** [comment]
As far as I can see if the database is empty it will continue populating the queue just using a Postgres database. First getting scan profile mutations, then random endpoint. The main thing is that the tasks table is empty, so historic tasks not be there. It should however take into account the grace period since it will check bytes if a certain boefje+ooi has been processed recently. So I think even the extra load should not be present.
