### ISSUE TITLE
Remove repeated mock patch decorators

### ISSUE THREAD

**Issue by jpbruinsslot** [minvws/nl-kat-coordination#591]
These lines are repeated for every test. If I'm not mistaken, you can also decorate the entire `TestCase` class.

_Originally posted by @ammar92 in https://github.com/minvws/nl-kat-coordination/pull/574#discussion_r1150319585_

**Comment by dekkers** [comment]
Using pytest fixtures it would also be possible to remove the duplication of creating the objects and setting the mock return values.

**Comment by ammar92** [comment]
> Using pytest fixtures it would also be possible to remove the duplication of creating the objects and setting the mock return values.

Unfortunately pytest fixtures don't go well with Python's `unittest.TestCase` tests. The solution would be to setup fixtures in the `setUp` method or rewrite the tests to pytest style tests
