### ISSUE TITLE
CSRF token not sent with login request

### ISSUE THREAD

**Issue by svenoq** [minvws/nl-kat-coordination#607]
Labels: bug, authentication, rocky, csrf

**Describe the bug**
hen attempting to log in to the OpenKAT application, users are presented with a 403 Forbidden error due to a failed CSRF verification. Despite the presence of the {% csrf_token %} tag in the login form HTML, the CSRF token is not being sent with the login request headers. This issue prevents users from being able to authenticate successfully.

**To Reproduce**
1. Navigate to the OpenKAT login page /account/login/
2. Enter valid login credentials
3. Submit the login form

**Expected behavior**
The login form should be submitted successfully and the user should be authenticated.

**Actual behavior** 
The login form submission results in a 403 Forbidden error due to a failed CSRF verification.

**Screenshots**
N/A

**OpenKAT version**
v1.6.2, installed using the container deployment https://docs.openkat.nl/technical_design/containers.html

**Desktop (please complete the following information if relevant):**
 - OS: macOS 13.2.1 (22D68)
 - Browser: Safari
 - Version: 16.3 (18614.4.6.1.6)

**Additional context**

- The django.middleware.csrf.CsrfViewMiddleware middleware is enabled in the project's middleware settings.
- The {% csrf_token %} tag is present in the login form HTML.
- The csrfmiddlewaretoken field is included in the form data when the login form is submitted.
- The X-CSRFToken header is not present in the request headers of the login request.
- The login view is not marked with the csrf_exempt decorator.
- The issue persists even after trying a different web browser and clearing cache and cookies.

**Comment by praseodym** [comment]
This can happen when not using HTTPS, because we require the use of secure cookies. Could you check if your browser console (in Developer Tools) logs any errors?
