### ISSUE TITLE
Ability to set up local test environment without user input

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#611]
As a developer, I'd like a setup command that initialises KAT in such a way that I do not have to perform any manual account creation, 2FA setup, or onboarding steps. This would help quickly set up a clean environment to test PRs/branches.

An approach we can use is to write a Django management command (for `manage.py`). The `setup_dev_account` is useful ~~but needs user input~~, the `setup_test_users` command doesn't need user input but is very focused on e2e testing. The management command would also need to be integrated in the Makefile in such a way that no user input is asked.

**Comment by Darwinkel** [comment]
It used to be the case that the superuser account was created automatically, but if I recall correctly this feature was removed due to security concerns (people forgetting to remove/change password for the default user)

**Comment by praseodym** [comment]
Makes sense, so we should either 1) generate a random password that we store in e.g. the .env file or 2) use a default password and _really_ make sure this is only used in local development.

**Comment by Darwinkel** [comment]
Maybe generate a random password, and print it once to stdout?
