### ISSUE TITLE
Add djLint pre-commit hook & reformat all templates

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#612]
Add djlint as pre-commit hook en reformat all templates using djlint.

After merging #626 we still need to fix and enable linting for rules:
- [x] Merge #626
- [x] H006 **ignored**: `img` tag should have `height` and `width` attributes
- [x] H013 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H014 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H016 **ignored**: Missing `title` tag in html.
- [x] H017 **ignored**: Tag should be self closing.
- [x] H019 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H020 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H023 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H025 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] H030 **ignored**: Consider adding a meta description.
- [x] H031 **ignored**: Consider adding meta keywords.
- [x] H033 https://github.com/minvws/nl-kat-coordination/pull/701
- [x] T001 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T002 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T003 https://github.com/minvws/nl-kat-coordination/pull/672
- [x] T032 https://github.com/minvws/nl-kat-coordination/pull/672

**Comment by praseodym** [comment]
#626 adds the linter and reformats templates. After that PR is merged, we need to fix ignored rules manually:

- [ ] H006
- [ ] H013
- [ ] H014
- [ ] H016
- [ ] H017
- [ ] H019
- [ ] H020
- [ ] H023
- [ ] H025
- [ ] H030
- [ ] H031
- [ ] H033
- [ ] T001
- [ ] T002
- [ ] T003
- [ ] T032
