### ISSUE TITLE
Design: Pre-defined filters so users can quickly filter tables based on pre-sets.

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#617]
Goal: 
Improving the flow for users to filter tables. 

Add pre-defined filters consisting of filter settings that are used often to filter a specific table. 

Design: 
- Which pre-defined filters we should add that will benefit our users
- Look, feel and placement of these filters (Including responsive behaviour).

**Comment by NoemiOverdijk** [comment]
This design has been finished and approved.

You can find the final design here:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=456%3A17924&t=Ka38eEoUfwPr4340-1](url)
