### ISSUE TITLE
Create new MutedFinding OOI type

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#624]
Currently, we have no way to Mute Findings.
We should allow users to Mute findings.

Given our future ambitions with Procedures on findings, creating a MuteOOI that relates to a specific finding (and possibly some other to be created AnswerOOI), would allow is to 'hide' findings from reports or other views.

Proposed is a new OOI type:

- Who (currently untracked) optional
- Which finding
- Which proof (eg, the answer) optional

In the future we can use the valid-till time on the OOI to mute findings for a give period But this is out of scope for now.

* MuteOOI's can be created from the rocky UX by binding them to the specific finding.
* MuteOOI's can be deleted from the rocky UX
* MuteOOI's can in the future be created by a normaliser acting on the Uploaded answers from a questionOOI.

**Comment by noamblitz** [comment]
Maybe we should also put who muted the finding in the actual object?

**Comment by underdarknl** [comment]
The Who is a property of the proposed OOI as mention in the issue. However, we should maybe move this to a more generic location soon, as its useful to keep track of for all manual OOI's.

I've been thinking, maybe we should make this MuteOOI (which should probably not be called an OOI, but just an O) a subclass of a new class of Object Models  called 'ControlObject' or something. Which we could use to hide/filter/query on. This could also include Objects like the proposed BitConfigObjects etc.
