### ISSUE TITLE
Crisis Room and Findings pages very slow when many findings are present

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#653]
The Crisis Room page loads very slowly (>50s) when many findings are present. This seems to be caused in part because the `get_queryset` function of the `Top10FindingListView` class in `rocky/rocky/views/finding_list.py` queries all findings only to then truncate it to the top 10. The query should be adjusted so that only the top 10 findings are retrieved from Octopoes/xtdb.

**Comment by praseodym** [comment]
This seems related to https://github.com/minvws/nl-kat-coordination/issues/555. As discussed improvements in this area will be part of Octopoes v3, which should allow us query only the data we need from xtdb.

**Comment by Lisser** [comment]
Related to:

https://github.com/minvws/nl-kat-coordination/issues/811
https://github.com/minvws/nl-kat-coordination/issues/461
https://github.com/minvws/nl-kat-coordination/issues/470
https://github.com/minvws/nl-kat-coordination/issues/152

**Comment by Lisser** [comment]
Implementation plan:
- add fields to FindingType models
- add Boefjes/Normalizers to enrich data
- replace logic in Rocky and Octopoes API to do the heavy lifting by XTDB
