### ISSUE TITLE
Documentation should have versioning for releases

### ISSUE THREAD

**Issue by praseodym** [minvws/nl-kat-coordination#654]
When installing KAT using Debian packages for v1.7.0rc3 (newest at this time) I noticed that the installation documentation refers to [the `update-mula-db` script](https://docs.openkat.nl/technical_design/debianinstall.html#mula-db) which was only added in v1.8.0. We should somehow match the package versions to documentation versions, or also include instructions for older versions in current documentation so that the documentation is always usable.

**Comment by Darwinkel** [comment]
I've investigated this in the past. ReadTheDocs has native support for versioned online docs, but this is not natively implemented in Sphinx. We probably require a third party plugin such as https://github.com/Holzhaus/sphinx-multiversion or https://github.com/sphinx-contrib/sphinxcontrib-versioning. Note that these haven't received updates in a while.

**Comment by ring-ring-ring** [comment]
Hmm this was one of the main reasons to move to sphinx and use PR's for the documentation, thanks for pointing this out @praseodym

**Comment by ring-ring-ring** [comment]
We looked at it in further detail and decided to kiss it, keep it super simple - for changes such as the one you encountered there will be a specific section in the docs, pointing to the correct version. Thanks for the issue :-)
