### ISSUE TITLE
Finding descriptions should be in the same format

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#656]
Currently, we use the descriptions from the bit definitions in Keiko's report directly. This is good, except that the format of these descriptions vary wildly. 

We should probably rewrite some of the descriptions such that they become more similar in terms of formatting. This will make the pdf reports look much cleaner. 

For example, NO-DNSSEC and INTERNETNL differ in their length, whether they include subfindings, and how they refer to the OOI in question:

![image](https://user-images.githubusercontent.com/9536436/229812558-68858fad-e50e-4503-8353-9ba3774a723d.png)

![image](https://user-images.githubusercontent.com/9536436/229812590-5c748468-e9d5-4091-a57b-f7999a75b7e1.png)

**Comment by noamblitz** [comment]
Internet.nl findings are the only exception since their discription is dependent on on what rules the ooi is not internet.nl compliant

**Comment by noamblitz** [comment]
And csp header findings by the way

**Comment by underdarknl** [comment]
> Internet.nl findings are the only exception since their discription is dependent on on what rules the ooi is not internet.nl compliant

I think we should just boil that down to, internet.nl failed. Due to: En then list the triggering findings. Doing so would also explain why, and makes it easier to develop both the overarching internet.nl bit, and to add proper descriptions with the sub-findings.

**Comment by noamblitz** [comment]
That's how it is currently implemented
