### ISSUE TITLE
Double filter buttons at object list filtering options

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#663]
There are 2 buttons for filtering:

Feature request
1. Remove one and catch what to filter based on get request or:
2. Split the 2 filtering flows, one for clearance level and one for OOI types filtering. Must find a better UX design for the splitting of filtering.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/30832687/230035670-1e01ee9b-2052-4516-8ad5-0b5f615482ec.png">

**Comment by underdarknl** [comment]
Agreed, this should be 1 form.
