### ISSUE TITLE
Show BitParams of inference on OOI detail

### ISSUE THREAD

**Issue by noamblitz** [minvws/nl-kat-coordination#665]
Show which object are input for the bit that found the OOI. Should show both the input OOI and the other BitParams

Endpoint should be implemented in OctopoesAPI and shown in OOI Detail

**Comment by NoemiOverdijk** [comment]
This is the approved design for this issue:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=333%3A13686&t=UZbdZcwK0NiJAuDw-1](url)

If you wish to comment on the design, you can do so here:
[https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=583%3A62011&t=AJB9r1q8MdAnQddW-1](url)
