### ISSUE TITLE
500 error for rocky health

### ISSUE THREAD

**Issue by trideeindhoven** [minvws/nl-kat-coordination#67]
On Debian 11.5, latest debian beta release of today, when i do:

curl http://localhost:8000/health/

I get a 500 error. In /var/log/syslog:

Nov 11 22:16:26 hostname python[1091517]: 127.0.0.1:40310 - "GET /health HTTP/1.1" 200
Nov 11 22:16:26 hostname uwsgi[1144678]: DEBUG:urllib3.connectionpool:http://localhost:8003 "GET /health HTTP/1.1" 200 99
Nov 11 22:16:26 hostname uwsgi[1144678]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8004
Nov 11 22:16:26 hostname python[1106871]: [2022-11-11 23:16:26 +0100] [1106871] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:33418 - "GET /health HTTP/1.1" 500
Nov 11 22:16:26 hostname python[1106871]: [2022-11-11 23:16:26 +0100] [1106871] [ERROR] [h11_impl] [uvicorn.error] Exception in ASGI application
Nov 11 22:16:26 hostname python[1106871]: Traceback (most recent call last):
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
Nov 11 22:16:26 hostname python[1106871]:     result = await app(self.scope, self.receive, self.send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
Nov 11 22:16:26 hostname python[1106871]:     return await self.app(scope, receive, send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
Nov 11 22:16:26 hostname python[1106871]:     await super().__call__(scope, receive, send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
Nov 11 22:16:26 hostname python[1106871]:     await self.middleware_stack(scope, receive, send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
Nov 11 22:16:26 hostname python[1106871]:     raise exc
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
Nov 11 22:16:26 hostname python[1106871]:     await self.app(scope, receive, _send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Nov 11 22:16:26 hostname python[1106871]:     raise exc
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
Nov 11 22:16:26 hostname python[1106871]:     await self.app(scope, receive, sender)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
Nov 11 22:16:26 hostname python[1106871]:     await route.handle(scope, receive, send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
Nov 11 22:16:26 hostname python[1106871]:     await self.app(scope, receive, send)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
Nov 11 22:16:26 hostname python[1106871]:     response = await func(request)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
Nov 11 22:16:26 hostname python[1106871]:     raw_response = await run_endpoint_function(
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
Nov 11 22:16:26 hostname python[1106871]:     return await run_in_threadpool(dependant.call, **values)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
Nov 11 22:16:26 hostname python[1106871]:     return await anyio.to_thread.run_sync(func, *args)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
Nov 11 22:16:26 hostname python[1106871]:     return await get_asynclib().run_sync_in_worker_thread(
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
Nov 11 22:16:26 hostname python[1106871]:     return await future
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
Nov 11 22:16:26 hostname python[1106871]:     result = context.run(func, *args)
Nov 11 22:16:26 hostname python[1106871]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/scheduler/server/server.py", line 133, in health
Nov 11 22:16:26 hostname python[1106871]:     response = models.ServiceHealth(
Nov 11 22:16:26 hostname python[1106871]:   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
Nov 11 22:16:26 hostname python[1106871]: pydantic.error_wrappers.ValidationError: 1 validation error for ServiceHealth
Nov 11 22:16:26 hostname python[1106871]: version
Nov 11 22:16:26 hostname python[1106871]:   str type expected (type=type_error.str)
Nov 11 22:16:26 hostname uwsgi[1144678]: DEBUG:urllib3.connectionpool:http://localhost:8004 "GET /health HTTP/1.1" 500 21
Nov 11 22:16:26 hostname uwsgi[1144678]: ERROR:django.request:Internal Server Error: /health/
Nov 11 22:16:26 hostname uwsgi[1144678]: Traceback (most recent call last):
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "pydantic/main.py", line 591, in pydantic.main.BaseModel.parse_raw
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
Nov 11 22:16:26 hostname uwsgi[1144678]:     return _default_decoder.decode(s)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
Nov 11 22:16:26 hostname uwsgi[1144678]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
Nov 11 22:16:26 hostname uwsgi[1144678]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Nov 11 22:16:26 hostname uwsgi[1144678]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Nov 11 22:16:26 hostname uwsgi[1144678]: During handling of the above exception, another exception occurred:
Nov 11 22:16:26 hostname uwsgi[1144678]: Traceback (most recent call last):
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Nov 11 22:16:26 hostname uwsgi[1144678]:     response = get_response(request)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Nov 11 22:16:26 hostname uwsgi[1144678]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Nov 11 22:16:26 hostname uwsgi[1144678]:     return view_func(request, *args, **kwargs)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Nov 11 22:16:26 hostname uwsgi[1144678]:     return view_func(request, *args, **kwargs)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 26, in health
Nov 11 22:16:26 hostname uwsgi[1144678]:     rocky_health = get_rocky_health(request.octopoes_api_connector)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 85, in get_rocky_health
Nov 11 22:16:26 hostname uwsgi[1144678]:     get_scheduler_health(),
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 58, in get_scheduler_health
Nov 11 22:16:26 hostname uwsgi[1144678]:     scheduler_health = client.health()
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/scheduler.py", line 121, in health
Nov 11 22:16:26 hostname uwsgi[1144678]:     return ServiceHealth.parse_raw(health_endpoint.content)
Nov 11 22:16:26 hostname uwsgi[1144678]:   File "pydantic/main.py", line 600, in pydantic.main.BaseModel.parse_raw
Nov 11 22:16:26 hostname uwsgi[1144678]: pydantic.error_wrappers.ValidationError: 1 validation error for ServiceHealth
Nov 11 22:16:26 hostname uwsgi[1144678]: __root__
Nov 11 22:16:26 hostname uwsgi[1144678]:   Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=Internal Server Error; pos=0; lineno=1; colno=1)
Nov 11 22:16:26 hostname uwsgi[1144678]: [pid: 1144678|app: 0|req: 15/33] 82.174.154.172 () {48 vars in 864 bytes} [Fri Nov 11 22:16:25 2022] GET /health/ => generated 145 bytes in 279 msecs (HTTP/1.1 500) 9 headers in 421 bytes (1 switches on core 3)

**Comment by underdarknl** [comment]
It looks like your scheduler is crashing, and for some reason this takes down Rockys health page.
Can you see if the scheduler has any logs?

**Comment by trideeindhoven** [comment]
This is pretty much the whole /var/log/syslog Is there another log i can send you?

**Comment by errieman** [comment]
If KAT has been installed using the Debian packages, you can access the log of the scheduler by executing `journalctl -u kat-mula`.

**Comment by errieman** [comment]
It seems that the scheduler now prefers to connect to rabbitmq over IPv6 instead of IPv4. The easiest solution is to add an IPv6 listener to RabbitMQ. This can be done by adding something like:
```
listeners.tcp.local6 = ::1:5672
```
To `/etc/rabbitmq/rabbitmq.conf`

**Comment by trideeindhoven** [comment]
I tried adding ipv6 to the listeners, but i still have no results:

root@hostname:/var/log# curl http://localhost:8000/health/
curl: (56) Recv failure: Connection reset by peer

journalctl -n 100 gives:
Nov 15 13:59:41 hostname python[1725125]: 127.0.0.1:35400 - "GET /v1/organisations HTTP/1.1" 200
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [WARNING] [scheduler] [scheduler.schedulers.scheduler] Queue normalizer-_dev is empty, not populating new tasks [queue_i>
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47076 - "GET /queues/normalizer-_dev/pop HTTP/1.1" 200
Nov 15 13:59:44 hostname python[1725062]: [2022-11-15 13:59:44 +0100] [1725062] [INFO] [app] Queue normalizer-_dev empty
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [WARNING] [scheduler] [scheduler.schedulers.scheduler] Queue normalizer-_dev is empty, not populating new tasks [queue_i>
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47068 - "GET /queues/normalizer-_dev/pop HTTP/1.1" 200
Nov 15 13:59:44 hostname python[1725061]: [2022-11-15 13:59:44 +0100] [1725061] [INFO] [app] Queue normalizer-_dev empty
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [WARNING] [scheduler] [scheduler.schedulers.scheduler] Queue boefje-_dev is empty, not populating new tasks [queue_id=bo>
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47098 - "GET /queues/boefje-_dev/pop HTTP/1.1" 200
Nov 15 13:59:44 hostname python[1725067]: [2022-11-15 13:59:44 +0100] [1725067] [INFO] [app] Queue boefje-_dev empty
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [WARNING] [scheduler] [scheduler.schedulers.scheduler] Queue boefje-_dev is empty, not populating new tasks [queue_id=bo>
Nov 15 13:59:44 hostname python[1725005]: [2022-11-15 13:59:44 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47092 - "GET /queues/boefje-_dev/pop HTTP/1.1" 200
Nov 15 13:59:44 hostname python[1725066]: [2022-11-15 13:59:44 +0100] [1725066] [INFO] [app] Queue boefje-_dev empty
Nov 15 13:59:45 hostname python[1725005]: [2022-11-15 13:59:45 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47076 - "GET /queues HTTP/1.1" 200
Nov 15 13:59:45 hostname python[1725062]: [2022-11-15 13:59:45 +0100] [1725062] [INFO] [app] Popping from queue normalizer-_dev
Nov 15 13:59:45 hostname python[1725005]: [2022-11-15 13:59:45 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47068 - "GET /queues HTTP/1.1" 200
Nov 15 13:59:45 hostname python[1725061]: [2022-11-15 13:59:45 +0100] [1725061] [INFO] [app] Popping from queue normalizer-_dev
Nov 15 13:59:45 hostname python[1725005]: [2022-11-15 13:59:45 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47098 - "GET /queues HTTP/1.1" 200
Nov 15 13:59:45 hostname python[1725067]: [2022-11-15 13:59:45 +0100] [1725067] [INFO] [app] Popping from queue boefje-_dev
Nov 15 13:59:45 hostname python[1725005]: [2022-11-15 13:59:45 +0100] [1725005] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:47092 - "GET /queues HTTP/1.1" 200
Nov 15 13:59:45 hostname python[1725066]: [2022-11-15 13:59:45 +0100] [1725066] [INFO] [app] Popping from queue boefje-_dev

**Comment by errieman** [comment]
The scheduler seems to be working. Rocky doesn't work over HTTP due to cookie settings. Try `curl -k https://localhost:8000/health/`

**Comment by trideeindhoven** [comment]
curl does not work (i get a 302 redirect to the login page).
When i use w3m, i log in and then visit /health:

Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8001
Nov 15 14:52:52 hostname python[1725090]: [2022-11-15 14:52:52 +0100] [1725090] [INFO] [h11_impl] 127.0.0.1:33428 - "GET /_dev/health HTTP/1.1" 200
Nov 15 14:52:52 hostname python[1725090]: [2022-11-15 14:52:52 +0100] [1725090] [INFO] [h11_impl] 127.0.0.1:33428 - "GET /_dev/health HTTP/1.1" 200
Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:http://localhost:8001 "GET /_dev/health HTTP/1.1" 200 360
Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8003
Nov 15 14:52:52 hostname python[1725125]: 127.0.0.1:54208 - "GET /health HTTP/1.1" 200
Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:http://localhost:8003 "GET /health HTTP/1.1" 200 99
Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
Nov 15 14:52:52 hostname python[1729112]: [2022-11-15 14:52:52 +0100] [1729112] [INFO] [h11_impl] [uvicorn.access] 127.0.0.1:38340 - "GET /health HTTP/1.1" 500
Nov 15 14:52:52 hostname python[1729112]: [2022-11-15 14:52:52 +0100] [1729112] [ERROR] [h11_impl] [uvicorn.error] Exception in ASGI application
Nov 15 14:52:52 hostname python[1729112]: Traceback (most recent call last):
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
Nov 15 14:52:52 hostname python[1729112]:     result = await app(self.scope, self.receive, self.send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
Nov 15 14:52:52 hostname python[1729112]:     return await self.app(scope, receive, send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
Nov 15 14:52:52 hostname python[1729112]:     await super().__call__(scope, receive, send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
Nov 15 14:52:52 hostname python[1729112]:     await self.middleware_stack(scope, receive, send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
Nov 15 14:52:52 hostname python[1729112]:     raise exc
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
Nov 15 14:52:52 hostname python[1729112]:     await self.app(scope, receive, _send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Nov 15 14:52:52 hostname python[1729112]:     raise exc
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
Nov 15 14:52:52 hostname python[1729112]:     await self.app(scope, receive, sender)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
Nov 15 14:52:52 hostname python[1729112]:     await route.handle(scope, receive, send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
Nov 15 14:52:52 hostname python[1729112]:     await self.app(scope, receive, send)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
Nov 15 14:52:52 hostname python[1729112]:     response = await func(request)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
Nov 15 14:52:52 hostname python[1729112]:     raw_response = await run_endpoint_function(
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
Nov 15 14:52:52 hostname uwsgi[1729896]: DEBUG:urllib3.connectionpool:http://localhost:8004 "GET /health HTTP/1.1" 500 21
Nov 15 14:52:52 hostname python[1729112]:     return await run_in_threadpool(dependant.call, **values)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
Nov 15 14:52:52 hostname python[1729112]:     return await anyio.to_thread.run_sync(func, *args)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
Nov 15 14:52:52 hostname python[1729112]:     return await get_asynclib().run_sync_in_worker_thread(
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
Nov 15 14:52:52 hostname python[1729112]:     return await future
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
Nov 15 14:52:52 hostname python[1729112]:     result = context.run(func, *args)
Nov 15 14:52:52 hostname python[1729112]:   File "/opt/venvs/kat-mula/lib/python3.9/site-packages/scheduler/server/server.py", line 133, in health
Nov 15 14:52:52 hostname python[1729112]:     response = models.ServiceHealth(
Nov 15 14:52:52 hostname python[1729112]:   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
Nov 15 14:52:52 hostname python[1729112]: pydantic.error_wrappers.ValidationError: 1 validation error for ServiceHealth
Nov 15 14:52:52 hostname python[1729112]: version
Nov 15 14:52:52 hostname python[1729112]:   str type expected (type=type_error.str)
Nov 15 14:52:52 hostname uwsgi[1729896]: ERROR:django.request:Internal Server Error: /health/
Nov 15 14:52:52 hostname uwsgi[1729896]: Traceback (most recent call last):
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "pydantic/main.py", line 591, in pydantic.main.BaseModel.parse_raw
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
Nov 15 14:52:52 hostname uwsgi[1729896]:     return _default_decoder.decode(s)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
Nov 15 14:52:52 hostname uwsgi[1729896]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
Nov 15 14:52:52 hostname uwsgi[1729896]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Nov 15 14:52:52 hostname uwsgi[1729896]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Nov 15 14:52:52 hostname uwsgi[1729896]: During handling of the above exception, another exception occurred:
Nov 15 14:52:52 hostname uwsgi[1729896]: Traceback (most recent call last):
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Nov 15 14:52:52 hostname uwsgi[1729896]:     response = get_response(request)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Nov 15 14:52:52 hostname uwsgi[1729896]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Nov 15 14:52:52 hostname uwsgi[1729896]:     return view_func(request, *args, **kwargs)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Nov 15 14:52:52 hostname uwsgi[1729896]:     return view_func(request, *args, **kwargs)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 26, in health
Nov 15 14:52:52 hostname uwsgi[1729896]:     rocky_health = get_rocky_health(request.octopoes_api_connector)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 85, in get_rocky_health
Nov 15 14:52:52 hostname uwsgi[1729896]:     get_scheduler_health(),
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/views/health.py", line 58, in get_scheduler_health
Nov 15 14:52:52 hostname uwsgi[1729896]:     scheduler_health = client.health()
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "/opt/venvs/kat-rocky/lib/python3.9/site-packages/rocky/scheduler.py", line 121, in health
Nov 15 14:52:52 hostname uwsgi[1729896]:     return ServiceHealth.parse_raw(health_endpoint.content)
Nov 15 14:52:52 hostname uwsgi[1729896]:   File "pydantic/main.py", line 600, in pydantic.main.BaseModel.parse_raw
Nov 15 14:52:52 hostname uwsgi[1729896]: pydantic.error_wrappers.ValidationError: 1 validation error for ServiceHealth
Nov 15 14:52:52 hostname uwsgi[1729896]: __root__
Nov 15 14:52:52 hostname uwsgi[1729896]:   Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=Internal Server Error; pos=0; lineno=1; colno=1)
Nov 15 14:52:52 hostname uwsgi[1729896]: [pid: 1729896|app: 0|req: 2/9] 127.0.0.1 () {38 vars in 632 bytes} [Tue Nov 15 13:52:51 2022] GET /health/ => generated 145 bytes in 146 msecs (HTTP/1.0 500) 9>

**Comment by RobboRob** [comment]
seems to be fixed in v1.4.0
