### ISSUE TITLE
Organisation crisis room layout not contained

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-coordination#715]
**Describe the bug**
Looks like there is a div missing:  

**To Reproduce**
Go to organisation crisis room

**Screenshots**
![Screenshot 2023-04-12 at 15 20 17](https://user-images.githubusercontent.com/9639395/231470688-46a9dbfe-90ef-4324-a919-770c7a458c6e.png)

**OpenKAT version**
Main 1.8

**Desktop (please complete the following information if relevant):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information if relevant):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by praseodym** [comment]
I think this was caused by #705 where I removed the main->section->div because I didn't think it was needed; should be simple enough to put it back in.

Can we somehow (in the future!) modify our styles so that we don't need as many container elements?
