### ISSUE TITLE
Postgres throws DiskFull during performance check

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#748]
After inserting roughly 2 million `boefje_meta` and `raw_files` into Bytes and counting the number of raw files per organization, I get a
```
bytes_1                | [2023-04-18 09:09:57 +0000] [21] [ERROR] [sql_meta_repository] An error occurred: (psycopg2.errors.DiskFull) could not resize shared memory segment "/PostgreSQL.610088736" to 33554432 bytes: No space left on device
```

Also see https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device as a reference. A greater `shm_size` seemed to resolve the issue. But as https://dba.stackexchange.com/questions/275378/dev-shm-size-recommendation-for-postgres-database-in-docker points out, another option would be to set `max_parallel_workers` to 0 for development to (hopefully) trade some performance for some fault tolerance and not eat away more memory resources. For the `docker-compose.release-example.yml` the latter is probably not a good idea though as this is not a good production setup, but also in general I think we should not be doing production resource tuning in this example file.

**Comment by underdarknl** [comment]
This happens when you do an aggregate query on the whole table?

**Comment by praseodym** [comment]
The 'Caveats' section on the [postgresql Docker image page](https://hub.docker.com/_/postgres) also suggests setting `shm_size` to 256MB, so I'd say we add that do both docker-compose config files.
