### ISSUE TITLE
Normalizers should be defined as generators

### ISSUE THREAD

**Issue by ammar92** [minvws/nl-kat-coordination#753]
Currently, the return type of a normalizer function is defined as an iterator, but in reality, it's not an iterator but a generator. Therefore it should be corrected.

**Describe the solution you'd like**
The signature of a normalizer function should be:
```python3
run(normalizer_meta: NormalizerMeta, raw: Union[bytes, str]) -> Generator[OOI]
```

**Comment by underdarknl** [comment]
Hm, maybe. in the end it doesn't really matter if they are if we are going to run them inside a sandbox as lambda functions, as they will get one shot at returning a dataset.

**Comment by ammar92** [comment]
> Hm, maybe. in the end it doesn't really matter if they are if we are going to run them inside a sandbox as lambda functions, as they will get one shot at returning a dataset.

True, it might look very different from how it's now, but for now, they're incorrect and a simple find and replace will solve this

**Comment by underdarknl** [comment]
Thanks @kshitiz305 for picking this up.

**Comment by kshitiz305** [comment]
HI @underdarknl I am looking forward to many more contributions.

Additionally, I would like to bring to your notice that I am looking for an opportunity in python/data engineering and if you come across any of a similar one in your organization please do let me know
