### ISSUE TITLE
Move 2FA checks to middleware and make it possible to disable

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#762]
The 2FA check should be moved to middleware so we don't have to this check for every view. This also makes it possible to disable 2FA for development/testing or when authentication would be done using single sign-on.

**Comment by ammar92** [comment]
Definitely looking forward to this. I do think implementing this comes with a few challenges because some views also need to be altered (e.g. the view that asks to enable 2FA during onboarding)

**Comment by praseodym** [comment]
Work on this was done in https://github.com/minvws/nl-rt-tim-abang-rocky/pull/782, we might be able to use that as a starting point.

**Comment by underdarknl** [comment]
related to: https://github.com/minvws/nl-kat-coordination/issues/57
