### ISSUE TITLE
Design plugin description section on plugin detail page

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#779]
A new boefje description template is established and the plugin detail page should provide a place and format to render this.

Information in the new description will consist of:

- Titel
- Goal
- Description
- External documentation
- Application
- Output
- Scan level
- Impact during scan
- Type

Below is an example of how that could look for Boefje NMAP TCP Top 250
![Image](https://user-images.githubusercontent.com/16188579/233600908-ba8cb619-089c-4f0f-8b62-99102f1aca7f.png)

**Comment by NoemiOverdijk** [comment]
Clarification: this issue is about designing the look and feel of the format. (Which type of heading, font size, etc.)

**Comment by NoemiOverdijk** [comment]
The design for this issue has been approved.

The approved design can be found here:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=455%3A16823&t=NSmd47cyc0LfbFDQ-1](url)
