### ISSUE TITLE
Drill down in crisis room

### ISSUE THREAD

**Issue by ErikNoort** [minvws/nl-kat-coordination#78]
### Describe the bug, issue or concern

I would like to have a drill down feature in the crisis room
Especially the option to click on the number of critical and high issues en drill down to an overview with those issues.

### To Reproduce
Go to /crisis-room/
Expand total issues
no option to click on the reported number of issues

### Expected behavior
The numbers should be a clickable link that goes to an overview of with the underlying issues that make up the number.

**Comment by underdarknl** [comment]
Dear @ErikNoort

We are working on this, and other drill down features, I expect some (but not all) to be present in the upcoming 1.4 release.
Currently, we need to first Switch to an organization, and only then can we click trough to its findings. 1.5 will probably solve this by making all paths include the url, so no more switching between them is needed. This would allow clicks from the dashboard into various organizations. Before that we will fix the Findings page itself to have more information.
