### ISSUE TITLE
Packaging OpenKAT

### ISSUE THREAD

**Issue by supakeen** [minvws/nl-kat-coordination#8]
Hi there, I've been taking a little look around the repositories for all the OpenKAT components with the eventual goal of packaging them for Fedora. I have a test build for `nl-kat-mula` which builds on the main branch (though tests fail) here: https://github.com/supakeen/fedora-package-openkat-mula (without any post-install for actually running).

To make packaging and downstreaming these packages easier I'd like to ask your opinions on a few things:

## Tag upstream releases on GitHub.

Tagging the upstream releases on GitHub allows me to refer directly to known (and tested) versions of the software. If you do decide on a versioning schema semver would be amazing, but anything goes :)

## Provide setup.py/pyproject.toml

As you can see in the above repository I added a patch to define requirements, package name, and entrypoints in `pyproject.toml` through poetry. It'd be nice if the (Python-based) repositories include either of these files.

## Package names

The package names seem to not relate to the OpenKAT project, e.g. `scheduler` for `nl-openkat-mula`. It'd be nice if they're prefixed `openkat_` (or use a namespace package I guess) to prevent collissions with other packages, e.g.: https://pypi.org/project/scheduler/

Aside from all of this I also have some general questions:

1. What are the preferred entrypoint name(s), is it `openkat-mula`, `kat-mula`, or `nl-kat-mula`?
2. What is the preferred author of packages, the repositories set the author to rdobeheer.nl, which email address would you like to use?
3. Are there plans to release this on PyPI?

**Comment by underdarknl** [comment]
Dear @supakeen 

Thank you for reaching out, and thank you for taking the time to investigate KAT, and see if you can build a version for Fedora.

We have tagged and versioned releases setup for our internal repositories, and we will do so too for the public repositories, in the process of migrating we probably skipped them, but they are forthcoming.

I will ask the developers of Mula to add the various manifest files, and ready the program to be available on Pypi. Some other packages are currently a bit too broad, and would probably be best split up into smaller parts (eg, our XTDB orm, and the data-models) which could then find their way into Pypi too.

The preferred endpoint name would be openkat-mula. where openkat itself could be the meta-package installing all sub-packages and doing the overall configuration.

We have a maintainer@openkat.nl email address specifically setup for distribution in packages.

**Comment by supakeen** [comment]
@underdarknl the tags/versions is great news. If the manifest files don't exist yet I'm happy to provide them in PRs where applicable.

I'll make the appropriate changes to make the base name `openkat` :)

**Comment by underdarknl** [comment]
@supakeen we have received a question from people if rpm packages are available. Would you still be willing to package Openkat for rpm based systems?

**Comment by underdarknl** [comment]
Dear @supakeen would you be willing to look at this together with the guys from HCS who have recently added a RedHat install guide for our dockerized development setup?
