### ISSUE TITLE
Indemnification should be a boolean field on OrganizationMember, not a model

### ISSUE THREAD

**Issue by dekkers** [minvws/nl-kat-coordination#833]
Indemnification in currently just a model with a foreign key to user and organization. There is no reason for this to be a separate model and it can just be a simple boolean field on OrganizationMember.

**Comment by TwistMeister** [comment]
Is it really best to put this on the organization member though?

The setting applies to the organization, and the only reason it's now implemented as a link table is so we know which user is responsible for setting it. I think it doesn't make sense to lookup all members and see if one has the indemnification bool set to true, needed for the organization to work with KAT.

Also, in the future, we want to be able to store multiple indemnifications, from multiple members. So when a certain member is no longer part of the organization (and therefor the associated indemnification instance gets delete) another can still be in place, associated with a member that's still part of the organization.

**Comment by dekkers** [comment]
This is duplicate of #260
