### ISSUE TITLE
Copy organization members from one organization to another

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#852]
It's practical to be able to copy all organization members in a (filtered) list at once from one organization to another.

This enables the user to copy all admins or all users with tag "lorem ipsum" to another organization in bulk.

**Comment by NoemiOverdijk** [comment]
This is the approved design for this issue:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=334%3A15354&t=UZbdZcwK0NiJAuDw-1](url)

If you want to comment on the design, you can do so here:
[https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=585%3A63762&t=AJB9r1q8MdAnQddW-1](url)
