### ISSUE TITLE
CSV upload for new users

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#853]
We want to be able to upload new users to a KAT organisation in Bulk.

The button "add new member" should become a drop down button, like "add objects" on the objects list page. Then two options can be shown: Add member manually, Upload CSV.

The following screen should explain somethings about the CSV criteria. To be determined, but I guess at least: e-mailadres, full name, account_type. Assigned clearance level could be optional. And for the password there's a decision to be made: do we want to sent invite e-mails or does the CSV have to contain passwords for each user?

For already known e-mail addresses I thinkt it's best to create new organisation members and link them to the already known users with those e-mail addresses, leaving all other info on those user accounts untouched.

Add objects button, as example:
![Screenshot 2023-06-12 at 17 32 02](https://github.com/minvws/nl-kat-coordination/assets/16188579/ad1122d2-d037-4d21-911b-8fae629177c3)

Criteria overview example for importing an OOI CSV
![Screenshot 2023-06-12 at 17 31 18](https://github.com/minvws/nl-kat-coordination/assets/16188579/8a8c8285-baf9-401b-8a65-f22fd5b2cf06)

**Comment by underdarknl** [comment]
Lets use the same flow we would use for adding multiple users to an organisation. So add users, or upload file, and then show the pending users in a list before saving them. Figma has designs for the manual flow for multiple users which can in turn send to the same CSV handler in the backend.

**Comment by Donnype** [comment]
What do we do when we have duplicate rows with different account_types? In my current setup when we have two users with different account_types, they get added to both groups, e.g. here for c@c.nl:


![Image](https://github.com/minvws/nl-kat-coordination/assets/46660228/54459b57-df3f-4529-8f55-4544a53e6a03)
