### ISSUE TITLE
Design efficient flow to add multiple users manually to organization

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-coordination#854]
When manually adding users to an organization it would be handy to have a way of adding multiple users in one go. An elegant flow should be designed for this.

**Comment by underdarknl** [comment]
https://www.figma.com/file/QRL8085Z827bNdO0bIDdFL/KAT-%7C-Design-%7C-For-review?type=design&node-id=747-90273

**Comment by NoemiOverdijk** [comment]
The following design has been approved:
[https://www.figma.com/file/8r4OSFIJt1PF4iDXf9MbqM/KAT-%7C-Design-%7C-Approved-for-implementation?type=design&node-id=721%3A13843&mode=design&t=0ii0QOwT5J4pTdQ9-1](url)
