### ISSUE TITLE
Add certificate expiry check

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-coordination#86]
## Implement certificate expiry check.

To be done:

Octopoes:
- Certificate Model: .days_until_expiry toevoegen 
  - https://github.com/minvws/nl-kat-octopoes/blob/main/octopoes/models/ooi/certificate.py#L24
- Cert expiry Bit toevoegen
  - Example: https://github.com/minvws/nl-kat-octopoes/tree/main/bits/missing_certificate
  - Input_ooi: Certificate
  - Output, potentieel: 
    - KAT-CERTIFICATE-EXPIRING-SOON
    - KAT-CERTIFICATE-EXPIRED

Rocky:
- OOI_database_seed.json aanpassen met nieuwe KAT Finding Types
  - https://github.com/minvws/nl-kat-rocky/blob/main/OOI_database_seed.json
  - KAT-CERTIFICATE-EXPIRING-SOON
     "description": "TLS certificate expiring soon"
     "risk": "Medium"
  - KAT-CERTIFICATE-EXPIRED
     "description": "TLS certificate has expired"
     "risk": "Critical"

Boefjes: 
- Normalizers die Certificates opleveren, aanvullen met .days_until_expiry
- https://github.com/minvws/nl-kat-boefjes/search?q=Certificate

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by underdarknl** [comment]
mentioning @ammar92 to make sure he's aware of this change.

**Comment by ammar92** [comment]
Good suggestion and very doable.

My only suggestion would be not to modify the model anymore but use `Certificate.valid_until` for this purpose. I also think we should clearly define what _soon_ means and mention this interval in the bit description?

**Comment by zcrt** [comment]
It is certainly preferable to use the `Certificate.valid_until` value. However, this bit must run regularly (e.g. every day) on an already existing certificate object. (If the certificate does not change the bit will not be triggered otherwise). So to make this Bit work either the datamodel must be modified or https://github.com/minvws/nl-kat-octopoes/issues/24 must be implemented.

Personally, I would say that 'soon' may be different for every user and should be a modifiable setting for the end-user (see https://github.com/minvws/nl-kat-octopoes/issues/16). Nevetheless, we could probably set a default value of e.g. two weeks though.

**Comment by underdarknl** [comment]
> It is certainly preferable to use the `Certificate.valid_until` value. However, this bit must run regularly (e.g. every day) on an already existing certificate object. (If the certificate does not change the bit will not be triggered otherwise). So to make this Bit work either the datamodel must be modified or [minvws/nl-kat-octopoes#24](https://github.com/minvws/nl-kat-octopoes/issues/24) must be implemented.
> 
> Personally, I would say that 'soon' may be different for every user and should be a modifiable setting for the end-user (see [minvws/nl-kat-octopoes#16](https://github.com/minvws/nl-kat-octopoes/issues/16)). Nevertheless, we could probably set a default value of e.g. two weeks though.

Correct, adding the remaining valid time as a property of the object will ensure that we change the object every day (when running the Boefje) and trigger any bits that need to be triggered. This is a bit of a hack until we get time sensitive bits in the system, but it will work for now.

**Comment by ammar92** [comment]
Good points. I will introduce this new field until the mentioned tickets above are implemented

**Comment by zcrt** [comment]
The boefje CRT also adds historical data to KAT. However, these certificates are treated as active resulting in a lot of false positive critical expired-certificate findings
