### ISSUE TITLE
Aggregate port findings

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#862]
**Is your feature request related to a problem? Please describe.**
When generating a .pdf report every open ports takes multiple lines such as:
```

IPPort—internet—<IP/>—tcp—<PORT/>
Port <PORT/> is not a common port and should possibly not be open

```
For multiple IPs and ports this can get cluttered. I would rather see a table with for every IP a list of open ports that is found by KAT.

**Describe the solution you'd like**
One solution is to implement a bit that aggregates all open port findingss into a single finding with a list of open ports for every IP. That would already clean up a lot of lines in the `.pdf` report.

**Comment by underdarknl** [comment]
> 

agreed

**Comment by noamblitz** [comment]
Im currently checking what implications it has for the Sources if we change input_ooi from port to ipaddress.

**Comment by noamblitz** [comment]
So it will be problematic, new sources for the ipaddress will not be created. A solution could be to change the rerun bit endpoints to first delete and recreate all sources. That will solve this. Agreed?

**Comment by noamblitz** [comment]
Draft PR: https://github.com/minvws/nl-kat-coordination/pull/1172
