### ISSUE TITLE
Missing HTTP security headers in default installation

### ISSUE THREAD

**Issue by sijmen-ruwhof** [minvws/nl-kat-coordination#87]
The default OpenKAT installation is missing various HTTP security headers, such as: 

1. Permissions-Policy
2. Pragma
3. X-DNS-Prefetch-Control
4. X-Permitted-Cross-Domain-Policies

These HTTP headers are mentioned in the [OpenKAT hardeningsguide](https://github.com/minvws/nl-kat-coordination/wiki/Installatiehandleiding:-hardening), but they should be (optionally) configured manually when installing OpenKAT via an additional reverse proxy that is put in front of OpenKAT.

### Expected behaviour
Out of the box these headers should be set by the internal OpenKAT embedded webserver, and not be configured manually when installing and configuring the infrastructure on which OpenKAT will be running.

### Reproduction
Send the following HTTP request to the server:

```
GET /account/login/ HTTP/1.1
Host: example.com:443
```

### Evidence
The server will return the following HTTP response: 

```
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Mon, 12 Dec 2022 21:58:33 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Expires: Mon, 12 Dec 2022 21:58:33 GMT
Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
Vary: Cookie, Accept-Language
Content-Security-Policy: block-all-mixed-content; style-src 'self'; form-action 'self'; default-src 'none'; img-src 'self'; frame-ancestors 'none'; font-src 'self'; script-src 'nonce-6Yb8siLybyhwhC5YQD4Z+A=='
X-Frame-Options: DENY
Content-Language: en
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: same-origin
Set-Cookie: csrftoken=[..]; expires=Mon, 11 Dec 2023 21:58:33 GMT; HttpOnly; Max-Age=31449600; Path=/; SameSite=Strict; Secure
Set-Cookie: sessionid=[..]; expires=Mon, 12 Dec 2022 23:58:33 GMT; HttpOnly; Max-Age=7200; Path=/; SameSite=Strict; Secure
Content-Length: 5058
[..]
```

**Comment by ITNerdbox** [comment]
I would like to point out the following items:

1. The Pragma header 

    This header is used in the HTTP/1.0 protocol and is considered obsolete and no longer recommended.
    Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma


2. The X-DNS-Prefetch-Control header

    This is a non-standard header and should not be used on production systems.
    Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control


3. Response headers

    When looking at the example response header, the following items are noticed that are not addressed and/or mentioned:
    
    1. X-XSS-Protection is another non-standard header that should no longer be used on production systems.
       Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
        
    2. The server header contains a version number and the used Linux distribution which is considered technology information disclosure.
