### ISSUE TITLE
OpenKAT can perform a vulnerability scan on itself 

### ISSUE THREAD

**Issue by sijmen-ruwhof** [minvws/nl-kat-coordination#88]
It is possible to create an IP address object with value `127.0.0.1`. Subsequently, it is possible to perform a scan on `127.0.0.1` via the Nmap Boefje. In addition, the hostname on which OpenKAT is installed (for example: `openkat.example.com`) could also be entered and scanned.

### Impact
OpenKAT can currently be used against itself because a red team member can scan their own infrastructure with all Boefjes. This might be desired functionality. If OpenKAT is installed in a 'as-a-service' environment, the (in time degrading) internal security of the OpenKAT installation might be something to keep away from end-users.

### Recommendation
1. It will have to be considered whether it is desirable that OpenKAT can also scan itself via the web interface. To prevent self-scanning, you can work with a blacklist of hostnames and IP addresses that are not allowed to be scanned.
2. A configuration option could also be made in OpenKAT that allows or disallows scanning of its own infrastructure.

### Reproduction
1. Go to https://openkat.example.com/objects/add/IPAddressV4/ and add a `IPAddressV4` object with value `127.0.0.1`.
2. Start a Nmap Boefje: https://openkat.example.com/kat-alogus/nmap-tcp-top250/

**Comment by underdarknl** [comment]
Yes, this is correct.
I have been thinking about this, and My suggestion would be to create documentation explaining this to the user, and also explaining that is might be remedied by firewalling around the boefje runner VM.
