### ISSUE TITLE
Mutefinding Filter/Select Improvements

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#890]
**Is your feature request related to a problem? Please describe.**
It would be nice to select multiple findings at once on the findings page and (un)mute them, just like clearance level on the object page. In addition, a filter should be added on the findings page where you can select to show muted findings.

**Describe the solution you'd like**
- Multiselect to mute/unmute findings on the findings page, with a text box as reason for all mute actions.
- A filter to show/hide muted findings on the findings page

**Comment by zcrt** [comment]
Additionally, quickly muting all DKIM/... findings for a selection of objects would be nice. This could be implemented by adding a filter on finding type on the Findings page (https://github.com/minvws/nl-kat-coordination/issues/906), when the selection option in this issue is implemented.

**Comment by underdarknl** [comment]
Its probably easier to implement the Mute finding button as a mass action on the already present object list page, as this already allows for filtering, and for mass-actions.

**Comment by underdarknl** [comment]
When muting multiple items the following scenarios come to mind:

* Not all selected objects are findings. (We could ignore those / present a info box to the user listing them)
* The user should be presented with (at least) one input field for a reason as to why the selected Findings are to be muted.
* Some findings might already be muted, which reason do we keep, the original, or the new? I'd opt for using the new reason.

**Comment by NoemiOverdijk** [comment]
I made a separate ticket to update the findings page design that includes the issues mentioned here, and unassigned myself from this issue.

#1372
