### ISSUE TITLE
Checkbox alignment

### ISSUE THREAD

**Issue by HeleenSG** [minvws/nl-kat-coordination#891]
![Screenshot 2023-05-02 at 14 59 29](https://user-images.githubusercontent.com/11405133/235673280-39e5ff8e-4829-43e5-aee0-3feeb9f6f005.png)

This has ben fixed in manon. Use new html-structure.

**Comment by TwistMeister** [comment]
![image](https://github.com/minvws/nl-kat-coordination/assets/16188579/f11b82b8-43f8-4795-8406-db5bfea3ccca)

Not quite the same as in the original screenshot, but theres still an issue with the alignment of this form.
