### ISSUE TITLE
Provide separate docker coontainers ( ghcr.io or hub.docker.com ).

### ISSUE THREAD

**Issue by dmeulen** [minvws/nl-kat-coordination#9]
I would like to run OpenKAT with a container orchestrator ( k8s or nomad ). Currently I'm using my own Dockerfile's to build my own versions of the KAT containers, because the current dockerfiles are expected to be used from the Makefile only. Individual builds are not possible.

Are there plans to provide docker containers per service and will they be available on ghcr.io or hub.docker.com ?

**Comment by underdarknl** [comment]
Dear Danny
We are currently exploring the option to push prebuild images to Docker Hub. This involves some guidelines on how en when we need and want to update those images though, and as such we want to investigate those steps before pushing out initial versions.
If you want I can connect you to the devs packaging the current builds, and we can work from there to make them more agnostic.

**Comment by underdarknl** [comment]
Dear @dmeulen
The docker containers which would be usable for you, and others should become available today, or tomorrow. If you have any remarks, let me know!

**Comment by noamblitz** [comment]
You can read more about the containers here

https://github.com/minvws/nl-kat-coordination/blob/main/docs/containers.md
