### ISSUE TITLE
Fierce boefje: subdomains get L0 indemnification

### ISSUE THREAD

**Issue by zcrt** [minvws/nl-kat-coordination#904]
**Describe the bug**
When scanning `example.com` with KAT at L4 the domain `subdomain.example.com` (sometimes) gets L0 as indemnification level, while sometimes it gets L1. There may be a difference in using `Fierce` or `DnsRecords`/`Subfinder` here.

**To Reproduce**
1. Scan (fierce?) a domain with a subdomain
2.  Notice the indemnification of the subdomain

**Expected behavior**
I would expect at least L1 for a subdomain of the first entered domain in KAT.

**OpenKAT version**
1.8rc2

**Comment by dekkers** [comment]
It looks like the reason the subdomains created by fierce don't inherit the level is because those hostnames don't have the dns_zone set.
