### ISSUE TITLE
Redteamers can scan objects from OOI detail and Boefje detail without having clearance

### ISSUE THREAD

**Issue by Rieven** [minvws/nl-kat-coordination#915]
Issue: A redteamer can still perform scans without clearance. 

The example screenshots is a redteamer with accepted and acknowledged clearance of -1 (None)

A user can scan objects at 3 locations:

onboarding - scan URL for makign a DNS-report (Also clearance needed see: https://github.com/minvws/nl-kat-coordination/issues/908)

ooi detail - from a list of objects scan 
![image](https://user-images.githubusercontent.com/30832687/236183833-094ac752-b24a-4881-ba74-d6805a01e457.png)

plugin/boefje detail:
![image](https://user-images.githubusercontent.com/30832687/236184082-98d2bb77-c29c-4a5c-a22a-b77fb7ba43d3.png)

**Comment by Darwinkel** [comment]
At least in the following two scenario's can redteamers perform scans without clearance:

# Scenario 1: redteamer without explicit permissions set

![image](https://user-images.githubusercontent.com/9536436/236190707-0f73069d-b908-48a9-837f-8b7079babe97.png)
![image](https://user-images.githubusercontent.com/9536436/236190726-4fb1f014-94fa-433f-b532-6e76d29d3303.png)
![image](https://user-images.githubusercontent.com/9536436/236190768-0ee6c3f1-8093-44fc-b8de-ae4586cf4615.png)
![image](https://user-images.githubusercontent.com/9536436/236190800-7c747bc8-f820-4538-87b8-3d4db71c80af.png)

# Scenario 2: redteamer with explicit permissions set
![image](https://user-images.githubusercontent.com/9536436/236191003-3a378845-e34d-4433-a8cd-652af6c6e92b.png)
![image](https://user-images.githubusercontent.com/9536436/236191029-930de7e5-d67e-4b22-886c-8a755aadfc31.png)

**Comment by underdarknl** [comment]
In both those scenarios the objects already have sufficient indemnifications for the requested boefje, correct?
In those cases, someone else already set the required indemnification, and performing this action as a red-teamer is no different to performing this action as a client. Both are allowed.

**Comment by Rieven** [comment]
@underdarknl To answer your question about: "In both those scenarios the objects already have sufficient indemnifications for the requested boefje, correct?"

Yes and no.

There can be also a scenario that these objects were created without starting any scan, in this case it will be a manual scan. The redteamer should have enough clearance here to start the scan, but this is not checked at the moment.

There can be also another scenario where there was already a clearance for those objects performed by another redteamer in the organization which had clearance. Now another redteamer could do a re-run without clearance, is also not checked.

The automatic scans that are runned by the scheduler are not checked either but that is another scenario, but his is by design at the moment how it is, but we can decide later to also implement clearance cheks for auto runs.
