### ISSUE TITLE
Clients and red teamers should be able to run certain manual scans

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#916]
(As of PR https://github.com/minvws/nl-kat-coordination/pull/606)

Clients can no longer initiate scans. I talked with @TwistMeister and there is something to be said for a client being able to run (some) scans, as this is also what the scheduler does in the background. It may be relevant for them to generate a more recent report with the newest information. The same essentially goes for low-clearance redteamers: shouldn't they be able to perform manual scans as long as this is something that the scheduler would trigger by itself?

_Originally posted by @Darwinkel in https://github.com/minvws/nl-kat-coordination/issues/606#issuecomment-1534682075_

**Comment by underdarknl** [comment]
Correct, Clients should be able to start scans that the scheduler would have started.

The main difference between clients and red-teamers shoud be: 
A red teamer should be able to add indemnifications on objects. (where clients cannot)
A red teamer can enable / configure boefjes, where a client cannot.

Any action that OpenKAT would do automatically, should be in reach for regular users if they want/need it to be scheduled sooner.
Some grey area is present here, as a user adding hundreds of heavy jobs could be damaging to remote systems, but this should be something we guard against in the scheduler at some point (regardless of those jobs being human or auto-generated)

**Comment by TwistMeister** [comment]
PR: https://github.com/minvws/nl-kat-coordination/pull/945
