### ISSUE TITLE
Specify core.autocrlf for windows users in dev documentation

### ISSUE THREAD

**Issue by Donnype** [minvws/nl-kat-coordination#990]
See https://github.com/minvws/nl-kat-coordination/pull/989.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

![Image](https://github.com/minvws/nl-kat-coordination/assets/46660228/7760c447-6d20-4c65-9483-348cf978a1d2)

We would want to add this to the contribution guidelines.

**Comment by ring-ring-ring** [comment]
thnx, fixed in https://github.com/minvws/nl-kat-coordination/pull/1182
