### ISSUE TITLE
Cloning the katalogus settings without specifiyng an organization causes a 500 error

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-coordination#996]
**Describe the bug**
On `en/<org>/kat-alogus/settings/`, when pressing "Clone settings" without explicitly selecting an organization in the dropdown, a 500 error is returned.

**To Reproduce**
1. Go to `en/<org>/kat-alogus/settings/`
2. Click on "Clone settings" without explicitly selecting an organization in the dropdown
3. See error

**Expected behavior**
Either good error handling or selecting an organization by default.

**Screenshots**
![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/e958c916-5375-4fde-adb7-7a1246c82733)
![image](https://github.com/minvws/nl-kat-coordination/assets/9536436/24ca4f5f-c445-41de-9b6c-86c086099f41)

**OpenKAT version**
`main` https://github.com/minvws/nl-kat-coordination/commit/6dac07a10a839ec6e02ed0246f7f2cf476f9cdf8

**Comment by underdarknl** [comment]
Please also make the field required in the frontend. (next to checking if we have a value in the backend obviously)
